from pathlib import Path
import csv,hashlib,json
p=Path('/tmp/frontend-raw-buttons-20260911');r=json.loads((p/'modal-browser-v4-result.json').read_text());focus=json.loads((p/'modal-focus-result.json').read_text());story=json.loads((p/'modal-story-result.json').read_text());assert r['status']==focus['status']==story['status']=='PASS'
with (p/'modal-comparison.csv').open('w') as f:
 cols=['width','height','dark','lang','kind','mode','amount','equivalent200Percent','required','available','fits','referenceMatched','beforeUnchanged','beforeFooterHeight','afterFooterHeight','children','afterContentInside','afterTextInside','overlaps']
 writer=csv.DictWriter(f,fieldnames=cols);writer.writeheader()
 for c in r['cases']:
  row={k:c[k] for k in cols[:8]};row.update({k:c['natural'][k] for k in ['required','available','fits']});row.update({k:c[k] for k in ['referenceMatched','beforeUnchanged']});row.update(beforeFooterHeight=c['before']['footer']['height'],afterFooterHeight=c['after']['footer']['height'],children=len(c['after']['children']),afterContentInside=all(x['insideContent'] and x['inside'] for x in c['after']['children']),afterTextInside=all(x['internalText'] for x in c['after']['children']),overlaps=len(c['after']['overlaps']));writer.writerow(row)
summary={'status':'PASS','base':r['base'],'pairs':len(r['cases']),'referenceMatched':sum(c['referenceMatched'] for c in r['cases']),'beforeUnchanged':sum(c['beforeUnchanged'] for c in r['cases']),'sameRowComparisons':sum(c['natural']['fits'] for c in r['cases']),'neededWrapConditions':sum(not c['natural']['fits'] for c in r['cases']),'amounts':sorted({c['amount'] for c in r['cases']}),'focusButtons':len(focus['focus']),'keyboardEnterSpaceCases':len(focus['keyboard']),'externalFormCases':len(r['keyboard']),'futureButtonsCases':len(r['future']),'storyCases':len(story['frames']),'errors':r['errors']+focus['errors']+story['errors'],'externalRequests':r['externalRequests']+focus['externalRequests'],'limits':['640px is 200% equivalent narrow width, not actual browser zoom','Data and currency values limited to fixture amounts; no arbitrary string guarantee','Production not accessed; APIs/auth mocked','Root executed quality commands; generator executed browser checks','Previous failed v1/v2/v3/diagnostic outputs retained']}
(p/'modal-summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n')
files=[p/n for n in ['modal-prepare.cjs','modal-browser-v4.mjs','modal-focus.mjs','modal-story.mjs','modal-summarize.py','modal-browser-v4-result.json','modal-browser-v4.log','modal-browser-v4-limited-result.json','modal-focus-result.json','modal-focus.log','modal-story-result.json','modal-story.log','modal-manifest.json','modal-summary.json','modal-comparison.csv']]
files += [q for q in (p/'modal-fixture').rglob('*') if q.is_file() and q.suffix in ['.tsx','.ts','.css','.html'] and 'node_modules' not in q.parts]
manifest={str(f.relative_to(p)):{'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'bytes':f.stat().st_size} for f in files}
(p/'modal-artifact-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n');print(json.dumps(summary,ensure_ascii=False,indent=2))
