-- dryrun.sql (same as apply.sql but ends with ROLLBACK)
-- Nothing is kept. Shows the final state inside the transaction, then rolls back.
-- Target: DB jarvis_db, schema public. Products 58, 60, 74, 75, 103, 105. Generated by gen_sql.py; do not hand-edit.
\set ON_ERROR_STOP on
BEGIN;
SET LOCAL app.is_operator = 'true';
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '60s';
DO $do$
DECLARE
  spec jsonb;
  specs jsonb := $j$[
 {
  "id": 58,
  "code": "SV9",
  "old": {
   "mark": "SV9",
   "name": "バトルパートナーズ",
   "search": [
    "バトルパートナーズ"
   ],
   "exclude": [
    "デッキビルド",
    "デッキビルドBOX バトルパートナーズ"
   ]
  },
  "new": {
   "mark": "SV9",
   "name": "バトルパートナーズ",
   "search": [
    "バトルパートナーズ"
   ],
   "exclude": [
    "デッキビルド"
   ]
  }
 },
 {
  "id": 60,
  "code": "SVN",
  "old": {
   "mark": "SV9",
   "name": "バトルパートナーズ",
   "search": [
    "バトルパートナーズ デッキビルド"
   ],
   "exclude": []
  },
  "new": {
   "mark": "SVN",
   "name": "バトルパートナーズ デッキビルドBOX",
   "search": [
    "バトルパートナーズ デッキビルド",
    "SV9 デッキビルド"
   ],
   "exclude": []
  }
 },
 {
  "id": 74,
  "code": "SV7",
  "old": {
   "mark": "SV7",
   "name": "ステラミラクル",
   "search": [
    "ステラミラクル"
   ],
   "exclude": [
    "デッキビルド",
    "デッキビルドBOX ステラミラクル"
   ]
  },
  "new": {
   "mark": "SV7",
   "name": "ステラミラクル",
   "search": [
    "ステラミラクル"
   ],
   "exclude": [
    "デッキビルド"
   ]
  }
 },
 {
  "id": 75,
  "code": "SVK",
  "old": {
   "mark": "SV7",
   "name": "ステラミラクル",
   "search": [
    "デッキビルド ステラミラクル"
   ],
   "exclude": []
  },
  "new": {
   "mark": "SVK",
   "name": "ステラミラクル デッキビルドBOX",
   "search": [
    "ステラミラクル デッキビルド",
    "SV7 デッキビルド"
   ],
   "exclude": []
  }
 },
 {
  "id": 103,
  "code": "SV3",
  "old": {
   "mark": "SV3",
   "name": "黒炎の支配者",
   "search": [
    "黒炎",
    "黒炎の支配者"
   ],
   "exclude": [
    "デッキビルド",
    "デッキビルドBOX"
   ]
  },
  "new": {
   "mark": "SV3",
   "name": "黒炎の支配者",
   "search": [
    "黒炎",
    "黒炎の支配者"
   ],
   "exclude": [
    "デッキビルド"
   ]
  }
 },
 {
  "id": 105,
  "code": "SVF",
  "old": {
   "mark": "SV3",
   "name": "黒炎の支配者",
   "search": [
    "黒炎の支配者 デッキビルド"
   ],
   "exclude": []
  },
  "new": {
   "mark": "SVF",
   "name": "黒炎の支配者 デッキビルドBOX",
   "search": [
    "黒炎の支配者 デッキビルド",
    "黒炎 デッキビルド",
    "SV3 デッキビルド"
   ],
   "exclude": []
  }
 }
]$j$::jsonb;
  pid int; c int; r record;
  cur_s text[]; cur_e text[]; from_s text[]; from_e text[]; to_s text[]; to_e text[];
  before_snap jsonb; after_snap jsonb; touched int := 0;
BEGIN
  FOR spec IN SELECT * FROM jsonb_array_elements(specs) LOOP
    pid := (spec->>'id')::int;
    -- lock + guard on the values we expect to replace (mirrors FOR UPDATE + revision check in update_product_detail)
    SELECT * INTO r FROM public.products WHERE id = pid FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'product % not found', pid; END IF;
    cur_s := ARRAY(SELECT keyword FROM public.product_search_keywords WHERE product_id = pid ORDER BY position, id);
    cur_e := ARRAY(SELECT keyword FROM public.product_exclude_keywords WHERE product_id = pid ORDER BY position, id);
    from_s := ARRAY(SELECT jsonb_array_elements_text(spec->'old'->'search'));
    from_e := ARRAY(SELECT jsonb_array_elements_text(spec->'old'->'exclude'));
    to_s := ARRAY(SELECT jsonb_array_elements_text(spec->'new'->'search'));
    to_e := ARRAY(SELECT jsonb_array_elements_text(spec->'new'->'exclude'));
    IF r.product_code IS DISTINCT FROM spec->>'code' OR r.mark IS DISTINCT FROM spec->'old'->>'mark'
       OR r.name IS DISTINCT FROM spec->'old'->>'name' OR r.is_active IS NOT TRUE
       OR cur_s IS DISTINCT FROM from_s OR cur_e IS DISTINCT FROM from_e THEN
      RAISE EXCEPTION 'GUARD id=%: unexpected current state code=% mark=% name=% search=% exclude=%',
        pid, r.product_code, r.mark, r.name, cur_s, cur_e;
    END IF;

    before_snap := jsonb_build_object(
      'product', (SELECT to_jsonb(p) FROM public.products p WHERE p.id = pid),
      'search_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_search_keywords k WHERE k.product_id = pid), '[]'::jsonb),
      'exclude_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_exclude_keywords k WHERE k.product_id = pid), '[]'::jsonb));

    UPDATE public.products SET name = spec->'new'->>'name', mark = spec->'new'->>'mark'
     WHERE id = pid AND name = spec->'old'->>'name' AND mark = spec->'old'->>'mark';
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> 1 THEN RAISE EXCEPTION 'UPDATE products id=% affected % rows (expected 1)', pid, c; END IF;
    RAISE NOTICE 'id=% products UPDATE rows=%: mark % -> %, name % -> %', pid, c, spec->'old'->>'mark', spec->'new'->>'mark', spec->'old'->>'name', spec->'new'->>'name';

    -- keyword lists: only the lists that change; delete all rows of the product, re-insert with position 1..n (as the app does)
    IF to_s IS DISTINCT FROM from_s THEN
      DELETE FROM public.product_search_keywords WHERE product_id = pid;
      GET DIAGNOSTICS c = ROW_COUNT;
      IF c <> COALESCE(array_length(from_s, 1), 0) THEN RAISE EXCEPTION 'search delete id=% rows=% (expected %)', pid, c, COALESCE(array_length(from_s, 1), 0); END IF;
      RAISE NOTICE 'id=% search_keywords deleted rows=%', pid, c;
      INSERT INTO public.product_search_keywords (product_id, keyword, position)
        SELECT pid, t.w, t.o FROM unnest(to_s) WITH ORDINALITY AS t(w, o);
      GET DIAGNOSTICS c = ROW_COUNT;
      IF c <> COALESCE(array_length(to_s, 1), 0) THEN RAISE EXCEPTION 'search insert id=% rows=% (expected %)', pid, c, COALESCE(array_length(to_s, 1), 0); END IF;
      RAISE NOTICE 'id=% search_keywords inserted rows=%', pid, c;
    END IF;
    IF to_e IS DISTINCT FROM from_e THEN
      DELETE FROM public.product_exclude_keywords WHERE product_id = pid;
      GET DIAGNOSTICS c = ROW_COUNT;
      IF c <> COALESCE(array_length(from_e, 1), 0) THEN RAISE EXCEPTION 'exclude delete id=% rows=% (expected %)', pid, c, COALESCE(array_length(from_e, 1), 0); END IF;
      RAISE NOTICE 'id=% exclude_keywords deleted rows=%', pid, c;
      INSERT INTO public.product_exclude_keywords (product_id, keyword, position)
        SELECT pid, t.w, t.o FROM unnest(to_e) WITH ORDINALITY AS t(w, o);
      GET DIAGNOSTICS c = ROW_COUNT;
      IF c <> COALESCE(array_length(to_e, 1), 0) THEN RAISE EXCEPTION 'exclude insert id=% rows=% (expected %)', pid, c, COALESCE(array_length(to_e, 1), 0); END IF;
      RAISE NOTICE 'id=% exclude_keywords inserted rows=%', pid, c;
    END IF;

    -- final state of this product must equal the target
    SELECT * INTO r FROM public.products WHERE id = pid;
    cur_s := ARRAY(SELECT keyword FROM public.product_search_keywords WHERE product_id = pid ORDER BY position, id);
    cur_e := ARRAY(SELECT keyword FROM public.product_exclude_keywords WHERE product_id = pid ORDER BY position, id);
    IF r.mark IS DISTINCT FROM spec->'new'->>'mark' OR r.name IS DISTINCT FROM spec->'new'->>'name'
       OR cur_s IS DISTINCT FROM to_s OR cur_e IS DISTINCT FROM to_e THEN
      RAISE EXCEPTION 'FINAL STATE id=% differs from target: mark=% name=% search=% exclude=%', pid, r.mark, r.name, cur_s, cur_e;
    END IF;

    after_snap := jsonb_build_object(
      'product', (SELECT to_jsonb(p) FROM public.products p WHERE p.id = pid),
      'search_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_search_keywords k WHERE k.product_id = pid), '[]'::jsonb),
      'exclude_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_exclude_keywords k WHERE k.product_id = pid), '[]'::jsonb));

    -- same shape as update_product_detail's audit row (record_id is a fresh uuid there too; old/new are TEXT)
    INSERT INTO public.audit_log (table_name, record_id, action, changed_by, old_values, new_values)
    VALUES ('products', gen_random_uuid(), 'UPDATE', 'claude-opus (PO承認 2026-10-04)', before_snap::text, after_snap::text);
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> 1 THEN RAISE EXCEPTION 'audit_log insert id=% rows=% (expected 1)', pid, c; END IF;
    touched := touched + 1;
  END LOOP;
  IF touched <> 6 THEN RAISE EXCEPTION 'touched % products (expected 6)', touched; END IF;
  RAISE NOTICE 'DONE: % products changed, % audit_log rows', touched, touched;
END
$do$;
SELECT p.id, p.product_code, p.mark, p.name, p.is_active,
       (SELECT string_agg(k.position || ':' || k.keyword, ' | ' ORDER BY k.position, k.id)
          FROM public.product_search_keywords k WHERE k.product_id = p.id) AS search_keywords,
       (SELECT string_agg(k.position || ':' || k.keyword, ' | ' ORDER BY k.position, k.id)
          FROM public.product_exclude_keywords k WHERE k.product_id = p.id) AS exclude_keywords
  FROM public.products p WHERE p.id IN (58, 60, 74, 75, 103, 105) ORDER BY p.id;
ROLLBACK;
