-- postcheck.sql (READ-ONLY)
-- RAISES unless all 6 products equal the target; also lists the audit rows written by apply.sql.
-- Target: DB jarvis_db, schema public. Products 58, 60, 74, 75, 103, 105. Generated by gen_sql.py; do not hand-edit.
\set ON_ERROR_STOP on
BEGIN READ ONLY;
SELECT p.id, p.product_code, p.mark, p.name, p.is_active,
       (SELECT string_agg(k.position || ':' || k.keyword, ' | ' ORDER BY k.position, k.id)
          FROM public.product_search_keywords k WHERE k.product_id = p.id) AS search_keywords,
       (SELECT string_agg(k.position || ':' || k.keyword, ' | ' ORDER BY k.position, k.id)
          FROM public.product_exclude_keywords k WHERE k.product_id = p.id) AS exclude_keywords
  FROM public.products p WHERE p.id IN (58, 60, 74, 75, 103, 105) ORDER BY p.id;
DO $do$
DECLARE
  spec jsonb;
  specs jsonb := $j$[
 {
  "id": 58,
  "code": "SV9",
  "old": {
   "mark": "SV9",
   "name": "バトルパートナーズ",
   "search": [
    "バトルパートナーズ"
   ],
   "exclude": [
    "デッキビルド",
    "デッキビルドBOX バトルパートナーズ"
   ]
  },
  "new": {
   "mark": "SV9",
   "name": "バトルパートナーズ",
   "search": [
    "バトルパートナーズ"
   ],
   "exclude": [
    "デッキビルド"
   ]
  }
 },
 {
  "id": 60,
  "code": "SVN",
  "old": {
   "mark": "SV9",
   "name": "バトルパートナーズ",
   "search": [
    "バトルパートナーズ デッキビルド"
   ],
   "exclude": []
  },
  "new": {
   "mark": "SVN",
   "name": "バトルパートナーズ デッキビルドBOX",
   "search": [
    "バトルパートナーズ デッキビルド",
    "SV9 デッキビルド"
   ],
   "exclude": []
  }
 },
 {
  "id": 74,
  "code": "SV7",
  "old": {
   "mark": "SV7",
   "name": "ステラミラクル",
   "search": [
    "ステラミラクル"
   ],
   "exclude": [
    "デッキビルド",
    "デッキビルドBOX ステラミラクル"
   ]
  },
  "new": {
   "mark": "SV7",
   "name": "ステラミラクル",
   "search": [
    "ステラミラクル"
   ],
   "exclude": [
    "デッキビルド"
   ]
  }
 },
 {
  "id": 75,
  "code": "SVK",
  "old": {
   "mark": "SV7",
   "name": "ステラミラクル",
   "search": [
    "デッキビルド ステラミラクル"
   ],
   "exclude": []
  },
  "new": {
   "mark": "SVK",
   "name": "ステラミラクル デッキビルドBOX",
   "search": [
    "ステラミラクル デッキビルド",
    "SV7 デッキビルド"
   ],
   "exclude": []
  }
 },
 {
  "id": 103,
  "code": "SV3",
  "old": {
   "mark": "SV3",
   "name": "黒炎の支配者",
   "search": [
    "黒炎",
    "黒炎の支配者"
   ],
   "exclude": [
    "デッキビルド",
    "デッキビルドBOX"
   ]
  },
  "new": {
   "mark": "SV3",
   "name": "黒炎の支配者",
   "search": [
    "黒炎",
    "黒炎の支配者"
   ],
   "exclude": [
    "デッキビルド"
   ]
  }
 },
 {
  "id": 105,
  "code": "SVF",
  "old": {
   "mark": "SV3",
   "name": "黒炎の支配者",
   "search": [
    "黒炎の支配者 デッキビルド"
   ],
   "exclude": []
  },
  "new": {
   "mark": "SVF",
   "name": "黒炎の支配者 デッキビルドBOX",
   "search": [
    "黒炎の支配者 デッキビルド",
    "黒炎 デッキビルド",
    "SV3 デッキビルド"
   ],
   "exclude": []
  }
 }
]$j$::jsonb;
  pid int; r record; cur_s text[]; cur_e text[]; want_s text[]; want_e text[];
BEGIN
  FOR spec IN SELECT * FROM jsonb_array_elements(specs) LOOP
    pid := (spec->>'id')::int;
    SELECT * INTO r FROM public.products WHERE id = pid;
    IF NOT FOUND THEN RAISE EXCEPTION 'product % not found', pid; END IF;
    cur_s := ARRAY(SELECT keyword FROM public.product_search_keywords WHERE product_id = pid ORDER BY position, id);
    cur_e := ARRAY(SELECT keyword FROM public.product_exclude_keywords WHERE product_id = pid ORDER BY position, id);
    want_s := ARRAY(SELECT jsonb_array_elements_text(spec->'new'->'search'));
    want_e := ARRAY(SELECT jsonb_array_elements_text(spec->'new'->'exclude'));
    IF r.product_code IS DISTINCT FROM spec->>'code' OR r.mark IS DISTINCT FROM spec->'new'->>'mark'
       OR r.name IS DISTINCT FROM spec->'new'->>'name' OR r.is_active IS NOT TRUE
       OR cur_s IS DISTINCT FROM want_s OR cur_e IS DISTINCT FROM want_e THEN
      RAISE EXCEPTION 'MISMATCH (new) id=%: code=% mark=% name=% active=% search=% exclude=%',
        pid, r.product_code, r.mark, r.name, r.is_active, cur_s, cur_e;
    END IF;
    RAISE NOTICE 'OK (new) id=% code=% mark=% name=%', pid, r.product_code, r.mark, r.name;
  END LOOP;
END
$do$;
SELECT id, table_name, action, changed_by, changed_at, length(old_values) AS old_len, length(new_values) AS new_len
  FROM public.audit_log WHERE table_name = 'products' AND changed_by = 'claude-opus (PO承認 2026-10-04)' ORDER BY id DESC LIMIT 12;
ROLLBACK;
