#!/usr/bin/env python3
"""Generate precheck/dryrun/apply/rollback/postcheck .sql for the one-time data step:
set roles.system_key = 'owner' on the role named オーナー and 'admin' on システム管理者 in the 5 existing tenant schemas.
One spec table -> five files (same style as docs/handoff/dup-product-merge/gen_sql.py). Nothing here touches a database.
Usage: python3 gen_sql.py   (writes next to this file)

NOT a migration: it runs once, under a PO psql-write ticket, after the roles.system_key column migration is deployed.
Counts are NOT hard-coded from memory: every file re-reads them from the database and RAISEs on any mismatch.
Rollback: apply.sql stores the changed role ids in public.audit_log (marked by STEP_ID); rollback.sql restores exactly those.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
STEP_ID = "roles-system-key-20261005"
ACTOR_APPLY = "claude-opus (PO承認 2026-10-05)"
ACTOR_ROLLBACK = "claude-opus (rollback; PO decision required)"

# schema, tenant number (roles.tenant_id), role display name, system_key
SPECS = [
    {"schema": f"tenant_{n:03d}", "tid": n, "role": role, "key": key}
    for n in (1, 3, 4, 5, 6)
    for role, key in (("オーナー", "owner"), ("システム管理者", "admin"))
]
SCHEMAS = sorted({s["schema"] for s in SPECS})

HEADER = """-- {title}
-- Target: DB jarvis_db. Schemas: {schemas}. Generated by gen_sql.py; do not hand-edit.
\\set ON_ERROR_STOP on
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '60s';
"""

# shared guard block: re-reads the live state and raises on any difference from the spec
GUARD = """  FOR spec IN SELECT * FROM jsonb_array_elements(specs) LOOP
    sch := spec->>'schema';
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = sch AND table_name = 'roles' AND column_name = 'system_key') THEN
      RAISE EXCEPTION '% has no roles.system_key column (deploy the column migration first)', sch;
    END IF;
    EXECUTE format('SELECT count(*) FROM %I.roles WHERE name = $1', sch) INTO n USING spec->>'role';
    IF n <> 1 THEN RAISE EXCEPTION '% role % count = % (expected 1)', sch, spec->>'role', n; END IF;
    EXECUTE format('SELECT count(*) FROM %I.roles WHERE name = $1 AND system_key IS NULL AND is_system IS TRUE AND tenant_id = $2', sch)
      INTO n USING spec->>'role', (spec->>'tid')::int;
    IF n <> 1 THEN RAISE EXCEPTION '% role % is not (system_key NULL, is_system TRUE, tenant_id %)', sch, spec->>'role', spec->>'tid'; END IF;
  END LOOP;
  FOR sch IN SELECT DISTINCT value->>'schema' FROM jsonb_array_elements(specs) LOOP
    EXECUTE format('SELECT count(*) FROM %I.roles WHERE system_key IS NOT NULL', sch) INTO n;
    IF n <> 0 THEN RAISE EXCEPTION '% already has % roles with system_key set', sch, n; END IF;
    EXECUTE format('SELECT count(*) FROM %I.roles', sch) INTO n;
    RAISE NOTICE '% roles total = %', sch, n;
  END LOOP;
"""

SPECS_JSON = "[" + ",".join(
    '{"schema":"%s","tid":%d,"role":"%s","key":"%s"}' % (s["schema"], s["tid"], s["role"], s["key"]) for s in SPECS
) + "]"


def precheck_sql() -> str:
    return HEADER.format(title="precheck.sql (READ ONLY; raises on any mismatch)", schemas=", ".join(SCHEMAS)) + """DO $do$
DECLARE
  specs jsonb := $j$@SPECS@$j$::jsonb;
  spec jsonb; sch text; n int;
BEGIN
@GUARD@  RAISE NOTICE 'precheck OK: % spec rows', jsonb_array_length(specs);
END
$do$;
ROLLBACK;
""".replace("@SPECS@", SPECS_JSON).replace("@GUARD@", GUARD)


def apply_body(actor: str) -> str:
    return """DO $do$
DECLARE
  specs jsonb := $j$@SPECS@$j$::jsonb;
  spec jsonb; sch text; n int; c int; rid int; ids jsonb; touched int := 0;
BEGIN
@GUARD@  FOR sch IN SELECT DISTINCT value->>'schema' FROM jsonb_array_elements(specs) LOOP
    ids := '[]'::jsonb;
    FOR spec IN SELECT * FROM jsonb_array_elements(specs) WHERE value->>'schema' = sch LOOP
      EXECUTE format('UPDATE %I.roles SET system_key = $1, updated_at = NOW() WHERE name = $2 AND system_key IS NULL RETURNING id', sch)
        INTO rid USING spec->>'key', spec->>'role';
      GET DIAGNOSTICS c = ROW_COUNT;
      IF c <> 1 THEN RAISE EXCEPTION '% update of role % rows=% (expected 1)', sch, spec->>'role', c; END IF;
      ids := ids || jsonb_build_array(jsonb_build_object('id', rid, 'role', spec->>'role', 'old', NULL, 'new', spec->>'key'));
      touched := touched + 1;
    END LOOP;
    INSERT INTO public.audit_log (table_name, record_id, action, changed_by, old_values, new_values)
    VALUES ('roles', gen_random_uuid(), 'UPDATE', '@ACTOR@',
            jsonb_build_object('schema', sch, 'system_key', 'NULL for all changed rows')::text,
            jsonb_build_object('system_key_step', '@STEP@', 'schema', sch, 'roles', ids)::text);
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> 1 THEN RAISE EXCEPTION 'audit_log insert for % rows=% (expected 1)', sch, c; END IF;
  END LOOP;
  IF touched <> @N@ THEN RAISE EXCEPTION 'touched % roles (expected @N@)', touched; END IF;
  RAISE NOTICE 'DONE: % roles updated, % audit_log rows', touched, touched / 2;
END
$do$;
""".replace("@SPECS@", SPECS_JSON).replace("@GUARD@", GUARD).replace("@ACTOR@", actor).replace("@STEP@", STEP_ID).replace("@N@", str(len(SPECS)))


def apply_like(end: str, title: str) -> str:
    return HEADER.format(title=title, schemas=", ".join(SCHEMAS)) + apply_body(ACTOR_APPLY) + end


def dryrun_sql() -> str:
    return apply_like("ROLLBACK;\n", "dryrun.sql (same as apply.sql; ends in ROLLBACK so nothing is kept)")


def apply_sql() -> str:
    return apply_like("COMMIT;\n", "apply.sql (WRITES; needs a PO psql-write ticket; one transaction; ends in COMMIT)")


def rollback_sql() -> str:
    return HEADER.format(title="rollback.sql (WRITES; needs a NEW PO decision before running)", schemas=", ".join(SCHEMAS)) + """DO $do$
DECLARE
  a record; r jsonb; c int; undone int := 0; sch text;
BEGIN
  FOR a IN SELECT id, new_values FROM public.audit_log
            WHERE table_name = 'roles' AND new_values LIKE '{%' AND (new_values::jsonb->>'system_key_step') = '@STEP@'
              AND NOT EXISTS (SELECT 1 FROM public.audit_log rb WHERE rb.table_name = 'roles' AND rb.new_values LIKE '{%'
                              AND (rb.new_values::jsonb->>'rolled_back_audit_id')::bigint = audit_log.id)
            ORDER BY id LOOP
    sch := a.new_values::jsonb->>'schema';
    FOR r IN SELECT * FROM jsonb_array_elements(a.new_values::jsonb->'roles') LOOP
      EXECUTE format('UPDATE %I.roles SET system_key = NULL, updated_at = NOW() WHERE id = $1 AND system_key = $2', sch)
        USING (r->>'id')::int, r->>'new';
      GET DIAGNOSTICS c = ROW_COUNT;
      IF c <> 1 THEN RAISE EXCEPTION 'rollback of % role id % rows=% (expected 1)', sch, r->>'id', c; END IF;
      undone := undone + 1;
    END LOOP;
    INSERT INTO public.audit_log (table_name, record_id, action, changed_by, old_values, new_values)
    VALUES ('roles', gen_random_uuid(), 'UPDATE', '@ACTOR@', a.new_values,
            jsonb_build_object('rolled_back_audit_id', a.id, 'system_key_step', '@STEP@-rollback')::text);
  END LOOP;
  IF undone <> @N@ THEN RAISE EXCEPTION 'rolled back % roles (expected @N@)', undone; END IF;
  RAISE NOTICE 'ROLLED BACK: % roles', undone;
END
$do$;
COMMIT;
""".replace("@STEP@", STEP_ID).replace("@ACTOR@", ACTOR_ROLLBACK).replace("@N@", str(len(SPECS)))


def postcheck_sql() -> str:
    return HEADER.format(title="postcheck.sql (READ ONLY)", schemas=", ".join(SCHEMAS)) + """DO $do$
DECLARE
  specs jsonb := $j$@SPECS@$j$::jsonb;
  spec jsonb; sch text; n int; total int := 0;
BEGIN
  FOR spec IN SELECT * FROM jsonb_array_elements(specs) LOOP
    sch := spec->>'schema';
    EXECUTE format('SELECT count(*) FROM %I.roles WHERE name = $1 AND system_key = $2 AND is_system IS TRUE', sch)
      INTO n USING spec->>'role', spec->>'key';
    IF n <> 1 THEN RAISE EXCEPTION '% role % system_key % count = % (expected 1)', sch, spec->>'role', spec->>'key', n; END IF;
  END LOOP;
  FOR sch IN SELECT DISTINCT value->>'schema' FROM jsonb_array_elements(specs) LOOP
    EXECUTE format('SELECT count(*) FROM %I.roles WHERE system_key IS NOT NULL', sch) INTO n;
    IF n <> 2 THEN RAISE EXCEPTION '% has % roles with system_key (expected 2)', sch, n; END IF;
    total := total + n;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = sch AND indexname = 'uq_roles_system_key') THEN
      RAISE EXCEPTION '% is missing index uq_roles_system_key', sch;
    END IF;
  END LOOP;
  IF total <> @N@ THEN RAISE EXCEPTION 'total system_key rows % (expected @N@)', total; END IF;
  RAISE NOTICE 'postcheck OK: % roles with system_key', total;
END
$do$;
SELECT id, table_name, changed_by, changed_at, length(new_values) AS new_len
  FROM public.audit_log WHERE table_name = 'roles' AND new_values LIKE '%@STEP@%' ORDER BY id;
ROLLBACK;
""".replace("@SPECS@", SPECS_JSON).replace("@N@", str(len(SPECS))).replace("@STEP@", STEP_ID)


def main() -> None:
    files = {
        "precheck.sql": precheck_sql(), "dryrun.sql": dryrun_sql(), "apply.sql": apply_sql(),
        "rollback.sql": rollback_sql(), "postcheck.sql": postcheck_sql(),
    }
    for name, body in files.items():
        (HERE / name).write_text(body, encoding="utf-8")
        print("wrote", name, len(body.splitlines()), "lines")


if __name__ == "__main__":
    main()
