-- postcheck.sql (READ ONLY)
-- Target: DB jarvis_db. Schemas: tenant_001, tenant_003, tenant_004, tenant_005, tenant_006. Generated by gen_sql.py; do not hand-edit.
\set ON_ERROR_STOP on
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '60s';
DO $do$
DECLARE
  specs jsonb := $j$[{"schema":"tenant_001","tid":1,"role":"オーナー","key":"owner"},{"schema":"tenant_001","tid":1,"role":"システム管理者","key":"admin"},{"schema":"tenant_003","tid":3,"role":"オーナー","key":"owner"},{"schema":"tenant_003","tid":3,"role":"システム管理者","key":"admin"},{"schema":"tenant_004","tid":4,"role":"オーナー","key":"owner"},{"schema":"tenant_004","tid":4,"role":"システム管理者","key":"admin"},{"schema":"tenant_005","tid":5,"role":"オーナー","key":"owner"},{"schema":"tenant_005","tid":5,"role":"システム管理者","key":"admin"},{"schema":"tenant_006","tid":6,"role":"オーナー","key":"owner"},{"schema":"tenant_006","tid":6,"role":"システム管理者","key":"admin"}]$j$::jsonb;
  spec jsonb; sch text; n int; total int := 0;
BEGIN
  FOR spec IN SELECT * FROM jsonb_array_elements(specs) LOOP
    sch := spec->>'schema';
    EXECUTE format('SELECT count(*) FROM %I.roles WHERE name = $1 AND system_key = $2 AND is_system IS TRUE', sch)
      INTO n USING spec->>'role', spec->>'key';
    IF n <> 1 THEN RAISE EXCEPTION '% role % system_key % count = % (expected 1)', sch, spec->>'role', spec->>'key', n; END IF;
  END LOOP;
  FOR sch IN SELECT DISTINCT value->>'schema' FROM jsonb_array_elements(specs) LOOP
    EXECUTE format('SELECT count(*) FROM %I.roles WHERE system_key IS NOT NULL', sch) INTO n;
    IF n <> 2 THEN RAISE EXCEPTION '% has % roles with system_key (expected 2)', sch, n; END IF;
    total := total + n;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = sch AND indexname = 'uq_roles_system_key') THEN
      RAISE EXCEPTION '% is missing index uq_roles_system_key', sch;
    END IF;
  END LOOP;
  IF total <> 10 THEN RAISE EXCEPTION 'total system_key rows % (expected 10)', total; END IF;
  RAISE NOTICE 'postcheck OK: % roles with system_key', total;
END
$do$;
SELECT id, table_name, changed_by, changed_at, length(new_values) AS new_len
  FROM public.audit_log WHERE table_name = 'roles' AND new_values LIKE '%roles-system-key-20261005%' ORDER BY id;
ROLLBACK;
