-- precheck.sql (READ ONLY; raises on any mismatch)
-- Target: DB jarvis_db. Schemas: tenant_001, tenant_003, tenant_004, tenant_005, tenant_006. Generated by gen_sql.py; do not hand-edit.
\set ON_ERROR_STOP on
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '60s';
DO $do$
DECLARE
  specs jsonb := $j$[{"schema":"tenant_001","tid":1,"role":"オーナー","key":"owner"},{"schema":"tenant_001","tid":1,"role":"システム管理者","key":"admin"},{"schema":"tenant_003","tid":3,"role":"オーナー","key":"owner"},{"schema":"tenant_003","tid":3,"role":"システム管理者","key":"admin"},{"schema":"tenant_004","tid":4,"role":"オーナー","key":"owner"},{"schema":"tenant_004","tid":4,"role":"システム管理者","key":"admin"},{"schema":"tenant_005","tid":5,"role":"オーナー","key":"owner"},{"schema":"tenant_005","tid":5,"role":"システム管理者","key":"admin"},{"schema":"tenant_006","tid":6,"role":"オーナー","key":"owner"},{"schema":"tenant_006","tid":6,"role":"システム管理者","key":"admin"}]$j$::jsonb;
  spec jsonb; sch text; n int;
BEGIN
  FOR spec IN SELECT * FROM jsonb_array_elements(specs) LOOP
    sch := spec->>'schema';
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = sch AND table_name = 'roles' AND column_name = 'system_key') THEN
      RAISE EXCEPTION '% has no roles.system_key column (deploy the column migration first)', sch;
    END IF;
    EXECUTE format('SELECT count(*) FROM %I.roles WHERE name = $1', sch) INTO n USING spec->>'role';
    IF n <> 1 THEN RAISE EXCEPTION '% role % count = % (expected 1)', sch, spec->>'role', n; END IF;
    EXECUTE format('SELECT count(*) FROM %I.roles WHERE name = $1 AND system_key IS NULL AND is_system IS TRUE AND tenant_id = $2', sch)
      INTO n USING spec->>'role', (spec->>'tid')::int;
    IF n <> 1 THEN RAISE EXCEPTION '% role % is not (system_key NULL, is_system TRUE, tenant_id %)', sch, spec->>'role', spec->>'tid'; END IF;
  END LOOP;
  FOR sch IN SELECT DISTINCT value->>'schema' FROM jsonb_array_elements(specs) LOOP
    EXECUTE format('SELECT count(*) FROM %I.roles WHERE system_key IS NOT NULL', sch) INTO n;
    IF n <> 0 THEN RAISE EXCEPTION '% already has % roles with system_key set', sch, n; END IF;
    EXECUTE format('SELECT count(*) FROM %I.roles', sch) INTO n;
    RAISE NOTICE '% roles total = %', sch, n;
  END LOOP;
  RAISE NOTICE 'precheck OK: % spec rows', jsonb_array_length(specs);
END
$do$;
ROLLBACK;
