-- rollback.sql (WRITES; needs a NEW PO decision before running)
-- Target: DB jarvis_db. Schemas: tenant_001, tenant_003, tenant_004, tenant_005, tenant_006. Generated by gen_sql.py; do not hand-edit.
\set ON_ERROR_STOP on
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '60s';
DO $do$
DECLARE
  a record; r jsonb; c int; undone int := 0; sch text;
BEGIN
  FOR a IN SELECT id, new_values FROM public.audit_log
            WHERE table_name = 'roles' AND new_values LIKE '{%' AND (new_values::jsonb->>'system_key_step') = 'roles-system-key-20261005'
              AND NOT EXISTS (SELECT 1 FROM public.audit_log rb WHERE rb.table_name = 'roles' AND rb.new_values LIKE '{%'
                              AND (rb.new_values::jsonb->>'rolled_back_audit_id')::bigint = audit_log.id)
            ORDER BY id LOOP
    sch := a.new_values::jsonb->>'schema';
    FOR r IN SELECT * FROM jsonb_array_elements(a.new_values::jsonb->'roles') LOOP
      EXECUTE format('UPDATE %I.roles SET system_key = NULL, updated_at = NOW() WHERE id = $1 AND system_key = $2', sch)
        USING (r->>'id')::int, r->>'new';
      GET DIAGNOSTICS c = ROW_COUNT;
      IF c <> 1 THEN RAISE EXCEPTION 'rollback of % role id % rows=% (expected 1)', sch, r->>'id', c; END IF;
      undone := undone + 1;
    END LOOP;
    INSERT INTO public.audit_log (table_name, record_id, action, changed_by, old_values, new_values)
    VALUES ('roles', gen_random_uuid(), 'UPDATE', 'claude-opus (rollback; PO decision required)', a.new_values,
            jsonb_build_object('rolled_back_audit_id', a.id, 'system_key_step', 'roles-system-key-20261005-rollback')::text);
  END LOOP;
  IF undone <> 10 THEN RAISE EXCEPTION 'rolled back % roles (expected 10)', undone; END IF;
  RAISE NOTICE 'ROLLED BACK: % roles', undone;
END
$do$;
COMMIT;
