import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { createInstance } from 'i18next';
import { I18nextProvider } from 'react-i18next';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import PurchaseOrdersFormModal from '../pages/purchase-orders/PurchaseOrdersFormModal';
import DexTab from '../pages/super-admin/DexTab';
import TcgSeriesTab from '../pages/super-admin/TcgSeriesTab';
import en from '../locales/en.json';

const mock = vi.hoisted(() => ({ get: vi.fn(), post: vi.fn(), patch: vi.fn(), put: vi.fn(), delete: vi.fn() }));
vi.mock('../lib/api', () => ({ api: mock }));
let instance = createInstance(); const tr = (key: string) => String(instance.t(key));
const dex = { id: 2, dex_number: 25, name_ja: 'Pikachu', name_en: 'Pikachu', generation: 1, region: 'Kanto', era: null };
const type = { id: 4, code: 'pokemon', name_ja: 'Pokemon', name_en: null, sort_order: 1, is_active: true };
const series = { id: 5, tcg_type: 'pokemon', series_code: 'S5', name_ja: 'Series fixture', name_en: 'Series', release_date: '2026-01-01', category: 'box' };
function deferred() { let resolve!: (v: unknown) => void; let reject!: (e: Error) => void; const promise = new Promise((r, j) => { resolve = r; reject = j; }); return { promise, resolve, reject }; }
function wrap(node: React.ReactNode) { return <I18nextProvider i18n={instance}><MemoryRouter>{node}</MemoryRouter></I18nextProvider>; }

beforeEach(async () => {
  vi.resetAllMocks(); instance = createInstance(); await instance.init({ lng: 'en', resources: { en: { translation: en } }, interpolation: { escapeValue: false } }); vi.stubGlobal('fetch', vi.fn(() => { throw new Error('Unexpected network'); }));
  mock.get.mockImplementation(async (url: string) => { if (url === '/suppliers/catalog') return [{ id: 7, name: 'Supplier', is_active: true }]; if (url === '/super-admin/dex/pokemon') return [dex]; if (url.startsWith('/super-admin/dex/import-jobs')) return []; if (url === '/super-admin/tcg/types') return [type]; if (url === '/super-admin/tcg/series?tcg_type=pokemon') return [series]; throw new Error(`Unexpected GET ${url}`); });
  for (const method of ['post', 'patch', 'put', 'delete'] as const) mock[method].mockImplementation(() => { throw new Error(`Unexpected ${method}`); });
});
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); });

describe('purchase and admin master save Button migration', () => {
  it('PO exact payload blocks pending repeats and calls success callbacks in order', async () => {
    const events: string[] = [], pending = deferred(); mock.post.mockReturnValue(pending.promise); render(wrap(<PurchaseOrdersFormModal open onCreated={() => events.push('created')} onClose={() => events.push('closed')} initialSupplierId={7} initialItems={[{ product_id: 8, product_name: 'Product', quantity: 2, unit_cost: 100 }, { product_id: 9, product_name: 'Second', quantity: 3, unit_cost: 50 }]} pickerless />)); await screen.findByRole('option', { name: 'Supplier' }); const dialog = screen.getByRole('dialog'); fireEvent.change(dialog.querySelector('textarea')!, { target: { value: ' note ' } }); const save = within(dialog).getByRole('button', { name: tr('common.save') }) as HTMLButtonElement; const cancel = within(dialog).getByRole('button', { name: tr('common.cancel') }) as HTMLButtonElement;
    fireEvent.click(save); expect(mock.post).toHaveBeenCalledExactlyOnceWith('/purchase-orders', { supplier_id: 7, notes: ' note ', items: [{ product_id: 8, quantity: 2, unit_cost: 100 }, { product_id: 9, quantity: 3, unit_cost: 50 }] }); expect(save.disabled).toBe(true); expect(cancel.disabled).toBe(true); fireEvent.click(save); fireEvent.click(cancel); expect(mock.post).toHaveBeenCalledTimes(1); expect(events).toEqual([]);
    await act(async () => pending.resolve({})); await waitFor(() => expect(events).toEqual(['created', 'closed']));
  });

  it('PO guards at zero writes and retains values for failure retry', async () => {
    render(wrap(<PurchaseOrdersFormModal open onCreated={vi.fn()} onClose={vi.fn()} />)); await screen.findByRole('option', { name: 'Supplier' }); fireEvent.submit(document.getElementById('po-form')!); expect(mock.post).not.toHaveBeenCalled(); fireEvent.change(screen.getByRole('combobox'), { target: { value: '7' } }); fireEvent.submit(document.getElementById('po-form')!); expect(mock.post).not.toHaveBeenCalled(); expect(await screen.findByText(tr('purchaseOrders.itemsRequired'))).toBeTruthy();
    cleanup(); const events: string[] = []; mock.post.mockRejectedValueOnce(new Error('PO failed')).mockResolvedValueOnce({}); render(wrap(<PurchaseOrdersFormModal open onCreated={() => events.push('created')} onClose={() => events.push('closed')} initialSupplierId={7} initialItems={[{ product_id: 8, product_name: 'Product', quantity: 1, unit_cost: 10 }]} pickerless />)); await screen.findByRole('option', { name: 'Supplier' }); const notes = document.querySelector('textarea')!; fireEvent.change(notes, { target: { value: 'retained note' } }); fireEvent.click(screen.getByRole('button', { name: tr('common.save') })); expect(await screen.findByText('PO failed')).toBeTruthy(); expect((screen.getByRole('combobox') as HTMLSelectElement).value).toBe('7'); expect(notes.value).toBe('retained note'); expect((screen.getByDisplayValue('Product') as HTMLInputElement).value).toBe('Product'); expect(events).toEqual([]); const firstPayload = mock.post.mock.calls[0]; fireEvent.click(screen.getByRole('button', { name: tr('common.save') })); await waitFor(() => expect(mock.post).toHaveBeenCalledTimes(2)); expect(mock.post.mock.calls[1]).toEqual(firstPayload); await waitFor(() => expect(events).toEqual(['created', 'closed']));
  });

  it('Dex saves exact pokemon fields, reloads, and retains values across failure retry', async () => {
    render(wrap(<DexTab />)); await screen.findAllByText('Pikachu'); fireEvent.click(screen.getAllByRole('button', { name: tr('common.edit') })[0]); const name = screen.getByPlaceholderText(tr('superAdmin.dex.fields.nameJa')) as HTMLInputElement; fireEvent.change(name, { target: { value: 'Raichu' } }); mock.patch.mockRejectedValueOnce(new Error('Dex save failed')).mockResolvedValueOnce({}); const save = screen.getByRole('button', { name: tr('common.save') }); fireEvent.click(save); expect(mock.patch).toHaveBeenNthCalledWith(1, '/super-admin/dex/pokemon/2', { dex_number: 25, name_ja: 'Raichu', name_en: 'Pikachu', generation: 1, region: 'Kanto', era: '' }); expect(await screen.findByText('Dex save failed')).toBeTruthy(); expect(name.value).toBe('Raichu'); const reads = mock.get.mock.calls.filter(c => c[0] === '/super-admin/dex/pokemon').length; fireEvent.click(save); await waitFor(() => expect(mock.get.mock.calls.filter(c => c[0] === '/super-admin/dex/pokemon')).toHaveLength(reads + 1)); expect(screen.queryByPlaceholderText(tr('superAdmin.dex.fields.nameJa'))).toBeNull();
  });

  it('Dex keeps its unlocked repeated-submit behavior while pending and settles both writes', async () => {
    render(wrap(<DexTab />)); await screen.findAllByText('Pikachu'); fireEvent.click(screen.getAllByRole('button', { name: tr('common.edit') })[0]); const first = deferred(), second = deferred(); mock.patch.mockReturnValueOnce(first.promise).mockReturnValueOnce(second.promise); const save = screen.getByRole('button', { name: tr('common.save') }) as HTMLButtonElement; const reads = mock.get.mock.calls.filter(c => c[0] === '/super-admin/dex/pokemon').length; fireEvent.click(save); fireEvent.click(save); expect(save.disabled).toBe(false); expect(save.getAttribute('aria-busy')).toBeNull(); expect(mock.patch).toHaveBeenCalledTimes(2); await act(async () => { first.resolve({}); second.resolve({}); }); await waitFor(() => expect(mock.get.mock.calls.filter(c => c[0] === '/super-admin/dex/pokemon')).toHaveLength(reads + 2)); expect(screen.queryByPlaceholderText(tr('superAdmin.dex.fields.nameJa'))).toBeNull();
  });

  it('Dex trainer edit sends the trainer schema and reloads its exact list', async () => {
    const trainer = { id: 6, dex_number: 1, name_ja: 'Trainer', name_en: 'Trainer', era: 'Modern' }; mock.get.mockImplementation(async (url: string) => { if (url === '/super-admin/dex/pokemon') return [dex]; if (url === '/super-admin/dex/trainer') return [trainer]; if (url.startsWith('/super-admin/dex/import-jobs')) return []; throw new Error(`Unexpected GET ${url}`); }); mock.patch.mockResolvedValue({});
    render(wrap(<DexTab />)); await screen.findAllByText('Pikachu'); fireEvent.change(screen.getByRole('combobox'), { target: { value: 'trainer' } }); await screen.findAllByText('Trainer'); fireEvent.click(screen.getAllByRole('button', { name: tr('common.edit') })[0]); fireEvent.change(screen.getByPlaceholderText(tr('superAdmin.dex.fields.era')), { target: { value: 'Classic' } }); const reads = mock.get.mock.calls.filter(c => c[0] === '/super-admin/dex/trainer').length; fireEvent.click(screen.getByRole('button', { name: tr('common.save') })); await waitFor(() => expect(mock.patch).toHaveBeenCalledExactlyOnceWith('/super-admin/dex/trainer/6', { dex_number: 1, name_ja: 'Trainer', name_en: 'Trainer', generation: null, region: '', era: 'Classic' })); await waitFor(() => expect(mock.get.mock.calls.filter(c => c[0] === '/super-admin/dex/trainer')).toHaveLength(reads + 1));
  });

  it('TCG type and series submits send exact normalized payloads and reload', async () => {
    mock.post.mockResolvedValue({}); mock.patch.mockResolvedValue({}); render(wrap(<TcgSeriesTab />)); await screen.findByText('Series fixture'); fireEvent.click(screen.getByRole('button', { name: tr('superAdmin.tcg.typeManager.title') })); const manager = screen.getByTestId('tcg-type-manager'); const typeInputs = within(manager).getAllByRole('textbox') as HTMLInputElement[]; fireEvent.change(typeInputs[0], { target: { value: ' New type ' } }); fireEvent.change(typeInputs[1], { target: { value: ' English ' } }); const typeReads = mock.get.mock.calls.filter(c => c[0] === '/super-admin/tcg/types').length; fireEvent.click(within(manager).getByRole('button', { name: tr('superAdmin.tcg.typeManager.addBtn') })); await waitFor(() => expect(mock.post).toHaveBeenCalledExactlyOnceWith('/super-admin/tcg/types', { name_ja: 'New type', name_en: 'English', sort_order: 100, is_active: true })); await waitFor(() => expect(mock.get.mock.calls.filter(c => c[0] === '/super-admin/tcg/types')).toHaveLength(typeReads + 1));
    expect(typeInputs[0].value).toBe(''); expect(typeInputs[1].value).toBe(''); fireEvent.click(screen.getByRole('button', { name: tr('common.edit') })); const code = screen.getByPlaceholderText(tr('superAdmin.tcg.fields.seriesCode')) as HTMLInputElement; fireEvent.change(code, { target: { value: 'S6' } }); const seriesReads = mock.get.mock.calls.filter(c => c[0] === '/super-admin/tcg/series?tcg_type=pokemon').length; fireEvent.click(screen.getByRole('button', { name: tr('common.update') })); await waitFor(() => expect(mock.patch).toHaveBeenCalledExactlyOnceWith('/super-admin/tcg/series/5', { tcg_type: 'pokemon', series_code: 'S6', name_ja: 'Series fixture', name_en: 'Series', release_date: '2026-01-01', category: 'box' })); await waitFor(() => expect(mock.get.mock.calls.filter(c => c[0] === '/super-admin/tcg/series?tcg_type=pokemon')).toHaveLength(seriesReads + 1)); expect((screen.getByPlaceholderText(tr('superAdmin.tcg.fields.seriesCode')) as HTMLInputElement).value).toBe('');
  });

  it('TCG save failure retains inputs and pending remains unlocked for repeat writes', async () => {
    render(wrap(<TcgSeriesTab />)); await screen.findByText('Series fixture'); fireEvent.click(screen.getByRole('button', { name: tr('common.edit') })); const code = screen.getByPlaceholderText(tr('superAdmin.tcg.fields.seriesCode')) as HTMLInputElement; fireEvent.change(code, { target: { value: 'Retained' } }); mock.patch.mockRejectedValueOnce(new Error('TCG failed')); fireEvent.click(screen.getByRole('button', { name: tr('common.update') })); expect(await screen.findByText('TCG failed')).toBeTruthy(); expect(code.value).toBe('Retained');
    const first = deferred(), second = deferred(); mock.patch.mockReturnValueOnce(first.promise).mockReturnValueOnce(second.promise); const save = screen.getByRole('button', { name: tr('common.update') }) as HTMLButtonElement; const reads = mock.get.mock.calls.filter(c => c[0] === '/super-admin/tcg/series?tcg_type=pokemon').length; const calls = mock.patch.mock.calls.length; fireEvent.click(save); fireEvent.click(save); expect(save.disabled).toBe(false); expect(save.getAttribute('aria-busy')).toBeNull(); expect(mock.patch).toHaveBeenCalledTimes(calls + 2); await act(async () => { first.resolve({}); second.resolve({}); }); await waitFor(() => expect(mock.get.mock.calls.filter(c => c[0] === '/super-admin/tcg/series?tcg_type=pokemon')).toHaveLength(reads + 2)); expect((screen.getByPlaceholderText(tr('superAdmin.tcg.fields.seriesCode')) as HTMLInputElement).value).toBe('');
  });

  it('TCG required fields prevent writes and series create sends all normalized keys', async () => {
    render(wrap(<TcgSeriesTab />)); await screen.findByText('Series fixture'); const newSeries = screen.getByRole('button', { name: tr('superAdmin.tcg.newSeries') }); fireEvent.click(newSeries); expect(mock.post).not.toHaveBeenCalled(); fireEvent.change(screen.getByPlaceholderText(tr('superAdmin.tcg.fields.seriesCode')), { target: { value: 'NEW' } }); fireEvent.change(screen.getByPlaceholderText(tr('superAdmin.tcg.fields.nameJa')), { target: { value: 'New series' } }); mock.post.mockResolvedValue({}); const reads = mock.get.mock.calls.filter(c => c[0] === '/super-admin/tcg/series?tcg_type=pokemon').length; fireEvent.click(newSeries); await waitFor(() => expect(mock.post).toHaveBeenCalledExactlyOnceWith('/super-admin/tcg/series', { tcg_type: 'pokemon', series_code: 'NEW', name_ja: 'New series', name_en: null, release_date: null, category: null })); await waitFor(() => expect(mock.get.mock.calls.filter(c => c[0] === '/super-admin/tcg/series?tcg_type=pokemon')).toHaveLength(reads + 1));
  });

  it('TCG type failure retains values and its pending save remains unlocked', async () => {
    render(wrap(<TcgSeriesTab />)); await screen.findByText('Series fixture'); fireEvent.click(screen.getByRole('button', { name: tr('superAdmin.tcg.typeManager.title') })); const manager = screen.getByTestId('tcg-type-manager'); const inputs = within(manager).getAllByRole('textbox') as HTMLInputElement[]; const add = within(manager).getByRole('button', { name: tr('superAdmin.tcg.typeManager.addBtn') }) as HTMLButtonElement; fireEvent.click(add); expect(mock.post).not.toHaveBeenCalled(); fireEvent.change(inputs[0], { target: { value: ' Retained type ' } }); mock.post.mockRejectedValueOnce(new Error('type failed')); fireEvent.click(add); expect(await screen.findByText('type failed')).toBeTruthy(); expect(inputs[0].value).toBe(' Retained type ');
    const first = deferred(), second = deferred(); mock.post.mockReturnValueOnce(first.promise).mockReturnValueOnce(second.promise); const reads = mock.get.mock.calls.filter(c => c[0] === '/super-admin/tcg/types').length; fireEvent.click(add); fireEvent.click(add); expect(add.disabled).toBe(false); expect(add.getAttribute('aria-busy')).toBeNull(); expect(mock.post).toHaveBeenCalledTimes(3); await act(async () => { first.resolve({}); second.resolve({}); }); await waitFor(() => expect(mock.get.mock.calls.filter(c => c[0] === '/super-admin/tcg/types')).toHaveLength(reads + 2)); expect(inputs[0].value).toBe(''); expect(inputs[1].value).toBe('');
  });
});
