-- postcheck.sql (READ-ONLY)
-- RAISES unless the merge is in place (retired inactive, 0 references left, saved ids on the survivors, flips in place).
-- Target: DB jarvis_db, schema public. Retire 440561/440572/440571 into 226/625/626. Generated by gen_sql.py; do not hand-edit.
\set ON_ERROR_STOP on
BEGIN READ ONLY;
SELECT p.id, p.product_code, p.mark, p.name, p.is_active,
       (SELECT count(*) FROM public.analysis_results ar WHERE ar.product_id = p.id) AS analysis_results,
       (SELECT count(*) FROM public.extraction_items ei WHERE ei.resolved_product_code = p.id::text) AS extraction_items,
       (SELECT count(*) FROM public.buyback_shop_products b WHERE b.product_id = p.id) AS buyback_shop_products,
       (SELECT count(*) FROM public.product_search_keywords k WHERE k.product_id = p.id) AS search_kw_rows
  FROM public.products p WHERE p.id IN (440561, 226, 440572, 625, 440571, 626) ORDER BY p.id;
DO $do$
DECLARE
  a record; nv jsonb; spec jsonb; n int; bad int; seen int := 0;
BEGIN
  FOR a IN SELECT id, new_values FROM public.audit_log
            WHERE table_name = 'products' AND changed_by = 'claude-opus (PO承認 2026-10-05)' AND new_values LIKE '%dup-merge-20261005%' ORDER BY id LOOP
    nv := a.new_values::jsonb;
    seen := seen + 1;
    IF EXISTS (SELECT 1 FROM public.products WHERE id = (nv#>>'{merge,retired}')::int AND is_active) THEN RAISE EXCEPTION 'retired % is still active', nv#>>'{merge,retired}'; END IF;
    IF NOT EXISTS (SELECT 1 FROM public.products WHERE id = (nv#>>'{merge,survivor}')::int AND is_active) THEN RAISE EXCEPTION 'survivor % is not active', nv#>>'{merge,survivor}'; END IF;
    SELECT count(*) INTO n FROM public.analysis_results WHERE product_id = (nv#>>'{merge,retired}')::int;
    IF n <> 0 THEN RAISE EXCEPTION 'analysis_results still point at retired %: %', nv#>>'{merge,retired}', n; END IF;
    SELECT count(*) INTO n FROM public.extraction_items WHERE resolved_product_code = nv#>>'{merge,retired}';
    IF n <> 0 THEN RAISE EXCEPTION 'extraction_items still hold retired %: %', nv#>>'{merge,retired}', n; END IF;
    SELECT count(*) INTO n FROM public.buyback_shop_products WHERE product_id = (nv#>>'{merge,retired}')::int;
    IF n <> 0 THEN RAISE EXCEPTION 'buyback_shop_products still point at retired %: %', nv#>>'{merge,retired}', n; END IF;
    SELECT count(*) INTO n FROM public.analysis_results WHERE product_id = (nv#>>'{merge,survivor}')::int AND id::text IN (SELECT jsonb_array_elements_text(nv#>'{merge,ids,analysis_results}'));
    IF n <> jsonb_array_length(nv#>'{merge,ids,analysis_results}') THEN RAISE EXCEPTION 'repointed analysis_results not all on survivor %: % of %', nv#>>'{merge,survivor}', n, jsonb_array_length(nv#>'{merge,ids,analysis_results}'); END IF;
    SELECT count(*) INTO bad FROM jsonb_array_elements(nv#>'{merge,ids,is_current_flips}') f
      JOIN public.analysis_results ar ON ar.id::text = f->>'id' WHERE ar.is_current IS DISTINCT FROM (f->>'to')::boolean;
    IF bad <> 0 THEN RAISE EXCEPTION 'is_current flips not in place for survivor %: % rows differ', nv#>>'{merge,survivor}', bad; END IF;
    RAISE NOTICE 'OK % -> %: retired inactive, 0 references left, % repointed rows on the survivor, % flips in place', nv#>>'{merge,retired}', nv#>>'{merge,survivor}', n, jsonb_array_length(nv#>'{merge,ids,is_current_flips}');
  END LOOP;
  IF seen <> 3 THEN RAISE EXCEPTION 'expected 3 audit rows, found %', seen; END IF;
END
$do$;
SELECT id, changed_by, changed_at, length(old_values) AS old_len, length(new_values) AS new_len
  FROM public.audit_log WHERE table_name = 'products' AND new_values LIKE '%dup-merge-20261005%' ORDER BY id;
ROLLBACK;
