-- precheck.sql (READ-ONLY)
-- RAISES unless the six products and every count (and the predicted is_current flips) equal the expected numbers.
-- Target: DB jarvis_db, schema public. Retire 440561/440572/440571 into 226/625/626. Generated by gen_sql.py; do not hand-edit.
\set ON_ERROR_STOP on
BEGIN READ ONLY;
SELECT p.id, p.product_code, p.mark, p.name, p.is_active,
       (SELECT count(*) FROM public.analysis_results ar WHERE ar.product_id = p.id) AS analysis_results,
       (SELECT count(*) FROM public.extraction_items ei WHERE ei.resolved_product_code = p.id::text) AS extraction_items,
       (SELECT count(*) FROM public.buyback_shop_products b WHERE b.product_id = p.id) AS buyback_shop_products,
       (SELECT count(*) FROM public.product_search_keywords k WHERE k.product_id = p.id) AS search_kw_rows
  FROM public.products p WHERE p.id IN (440561, 226, 440572, 625, 440571, 626) ORDER BY p.id;
DO $do$
DECLARE
  specs jsonb := $j$[
 {
  "retired": 440561,
  "retired_code": "PM0226",
  "survivor": 226,
  "survivor_code": "DB-FB09",
  "ar": 82,
  "flips": 8,
  "flips_to_true": 0,
  "ei": 1,
  "bb": 0
 },
 {
  "retired": 440572,
  "retired_code": "PM0224",
  "survivor": 625,
  "survivor_code": "YGO-LOCR",
  "ar": 53,
  "flips": 6,
  "flips_to_true": 0,
  "ei": 6,
  "bb": 1
 },
 {
  "retired": 440571,
  "retired_code": "PM0223",
  "survivor": 626,
  "survivor_code": "YGO-LOCH",
  "ar": 32,
  "flips": 4,
  "flips_to_true": 0,
  "ei": 10,
  "bb": 0
 }
]$j$::jsonb;
  spec jsonb; r record; s record; n int; f_false int; f_true int;
BEGIN
  FOR spec IN SELECT * FROM jsonb_array_elements(specs) LOOP
    SELECT * INTO r FROM public.products WHERE id = (spec->>'retired')::int;
    SELECT * INTO s FROM public.products WHERE id = (spec->>'survivor')::int;
    IF r.id IS NULL OR s.id IS NULL THEN RAISE EXCEPTION 'product missing for pair %', spec; END IF;
    IF r.product_code IS DISTINCT FROM spec->>'retired_code' OR s.product_code IS DISTINCT FROM spec->>'survivor_code'
       OR r.is_active IS NOT TRUE OR s.is_active IS NOT TRUE THEN
      RAISE EXCEPTION 'PAIR state differs: retired % (%, active %), survivor % (%, active %)', r.id, r.product_code, r.is_active, s.id, s.product_code, s.is_active;
    END IF;
    SELECT count(*) INTO n FROM public.analysis_results WHERE product_id = r.id;
    IF n <> (spec->>'ar')::int THEN RAISE EXCEPTION 'analysis_results for % = % (expected %)', r.id, n, spec->>'ar'; END IF;
    SELECT count(*) INTO n FROM public.extraction_items WHERE resolved_product_code = r.id::text;
    IF n <> (spec->>'ei')::int THEN RAISE EXCEPTION 'extraction_items for % = % (expected %)', r.id, n, spec->>'ei'; END IF;
    SELECT count(*) INTO n FROM public.buyback_shop_products WHERE product_id = r.id;
    IF n <> (spec->>'bb')::int THEN RAISE EXCEPTION 'buyback_shop_products for % = % (expected %)', r.id, n, spec->>'bb'; END IF;
    -- predicted is_current flips under the app rule (tcg_analyzer_svc.py:1759-1791), computed as if the retired rows already pointed at the survivor
    WITH x AS (
      SELECT ar.id, ar.condition_id, ar.is_current, ar.computed_at, sm.received_at, sm.supplier_channel_id AS ch,
             (ar.product_id = r.id) AS is_retired
        FROM public.analysis_results ar
        JOIN public.extraction_items ei ON ei.id = ar.extraction_item_id
        JOIN public.extraction_jobs ej ON ej.id = ei.extraction_job_id
        JOIN public.source_messages sm ON sm.id = ej.source_message_id
       WHERE ar.product_id IN (r.id, s.id) AND ar.pid_resolved = TRUE),
    aff AS (SELECT DISTINCT ch, condition_id FROM x WHERE is_retired AND condition_id IS NOT NULL),
    ranked AS (
      SELECT x.id, x.is_current,
             (row_number() OVER (PARTITION BY x.ch, x.condition_id ORDER BY x.received_at DESC, x.computed_at DESC) = 1) AS should
        FROM x WHERE EXISTS (SELECT 1 FROM aff WHERE aff.ch IS NOT DISTINCT FROM x.ch AND aff.condition_id = x.condition_id))
    SELECT count(*) FILTER (WHERE is_current AND NOT should), count(*) FILTER (WHERE NOT is_current AND should)
      INTO f_false, f_true FROM ranked;
    IF f_false <> (spec->>'flips')::int OR f_true <> (spec->>'flips_to_true')::int THEN
      RAISE EXCEPTION 'predicted flips for survivor % = to_false % / to_true % (expected % / %)', s.id, f_false, f_true, spec->>'flips', spec->>'flips_to_true';
    END IF;
    RAISE NOTICE 'OK pair % -> %: ar % / flips % / ei % / bb %', r.product_code, s.product_code, spec->>'ar', spec->>'flips', spec->>'ei', spec->>'bb';
  END LOOP;
END
$do$;
ROLLBACK;
