-- Phase 1 再設計 / Migration 023: システム管理者・オーナーの is_system フラグ修正
--
-- 背景:
--   Migration 021 の INSERT ... ON CONFLICT (tenant_id, name) DO NOTHING は、
--   既にテナント内に同名のロールが存在する場合、新しい値（is_system=TRUE）を
--   無視して旧値を保持する。本番 VPS の一部テナントで「システム管理者」/
--   「オーナー」が is_system=FALSE のまま残っていた。
--
-- 冪等性:
--   - 非テンプレート（{schema} プレースホルダなし）。psql 直実行可能。
--   - WHERE is_system = FALSE により既に TRUE のロールは no-op。
--   - DO ブロック内で pg_namespace を走査し、全 tenant_NNN スキーマに自動適用。
--   - 複数回実行しても副作用なし（deploy.yml で自動実行される場合も安全）。
--
-- 実行方法:
--   docker exec -i astro-webapp-postgres-1 \
--     psql -U jarvis -d jarvis_db -v ON_ERROR_STOP=1 \
--     < migrations/023_fix_system_admin_is_system_flag.sql
--
-- 変更履歴:
--   2026-04-23: 初版作成（Phase 1 再設計 軽微課題）
--   2026-04-23: 非テンプレート化（reviewer PR #99 Major 1 対応）

--
-- NEUTRALIZED (ADR-1007 / ADR-155, 2026-10-07):
-- 商品マスタ・権限などの値はアプリ画面/CSVで管理する。migrationは構造変更のみ。
-- is_system の一括更新（全テナントの UPDATE）を外した。新テナントは作成コードが is_system=True で作る。
-- 元の内容は git history で参照可能。
--

DO $$ BEGIN RAISE NOTICE 'migration 023 neutralized (ADR-1007 / ADR-155): is_system flag is written by tenant creation'; END $$;
