-- Phase 1 再設計 / Migration 025: オーナー/システム管理者に全権限を再割当
--
-- 背景:
--   migrate_phase1.py の seed_system_roles() は初期テナント作成時に1回だけ
--   オーナーに全権限を INSERT する（SELECT id FROM public.permissions）。
--   その後 migration 018（menu.* 19件）や 024（staff.*/bots.* 8件）で
--   permissions が追加されたが、オーナー・システム管理者にはまだ紐付いていない。
--
-- 修正内容:
--   全テナントの「オーナー」「システム管理者」ロールに対して、現時点で
--   public.permissions に存在する権限を INSERT（ON CONFLICT DO NOTHING）。
--   tenant.py の _assign_permissions_to_role() 契約に合わせる:
--     オーナー        : ALL（system.manage を含む全権限）
--     システム管理者  : ALL_EXCEPT_SYSTEM_MANAGE（system.manage を除外）
--   既存の割当は保持、不足分のみ追加される。
--
-- 冪等性:
--   ON CONFLICT (role_id, permission_id) DO NOTHING で再実行しても副作用なし。
--   DO block で pg_namespace を走査、非テンプレートのため psql 直実行可能。
--
-- 変更履歴:
--   2026-04-23: 初版作成（Phase 1 再設計 follow-up）

--
-- NEUTRALIZED (ADR-1007 / ADR-155, 2026-10-07):
-- 商品マスタ・権限などの値はアプリ画面/CSVで管理する。migrationは構造変更のみ。
-- オーナー/システム管理者への権限の再付与を外した。権限は load_user_permissions が権限マスタから計算する（system_key）。
-- 元の内容は git history で参照可能。
--

DO $$ BEGIN RAISE NOTICE 'migration 025 neutralized (ADR-1007 / ADR-155): owner/admin permissions are computed at check time'; END $$;
