-- Phase 1-D Sprint 1 / Migration 042: Meta Inbox 用の permissions を seed
--
-- 背景:
--   Phase 1-D（Meta Inbox UI）で必要な 4 つの権限キーを public.permissions に追加し、
--   既存テナントの「オーナー」「システム管理者」ロールに role_permissions として紐付ける。
--
-- 関連:
--   spec.md §5-8（権限定義）
--   migrations/002_add_permissions_master.sql（既存パターン）
--   migrations/025_resync_owner_admin_all_permissions.sql（owner/admin への ALL 同期パターン）
--
-- 追加される権限:
--   channels.view    : Channels 設定画面の閲覧
--   channels.manage  : Facebook Page / Instagram の OAuth 接続・切断
--   messaging.view   : Inbox の閲覧、メッセージ履歴取得、既読マーク
--   messaging.send   : メッセージ送信
--
-- 冪等性:
--   - permissions: ON CONFLICT (key) DO NOTHING
--   - role_permissions: ON CONFLICT (role_id, permission_id) DO NOTHING
--   再実行しても副作用なし。
--
-- 実行方法:
--   docker compose exec postgres psql -U <user> -d <db> -f /migrations/042_seed_meta_inbox_permissions.sql
--
-- 変更履歴:
--   2026-04-30: 初版（しんごさん依頼、Phase 1-D Sprint 1）

-- NEUTRALIZED (ADR-1007 / ADR-155, 2026-10-07):
-- Meta Inbox の権限 4 キーの seed と、オーナー／システム管理者への付与を外した。値は本番に入っている。
-- 新しいテナントの作成（backend/app/services/tenant.py の seed_system_roles）は、その時点の権限を付与する。
-- 元の内容は git history で参照可能。
DO $$ BEGIN RAISE NOTICE 'ADR-1007 neutralized: meta inbox permissions seed removed (042)'; END $$;
