-- ============================================================================
-- Migration 20260615_235900: ポケモンカードゲーム MEGA シリーズ 商品マスタ投入
--
-- 対象: ポケモンカードゲーム MEGA（2025年8月1日 シリーズ開始）
--   - リンクあり商品 14 件（product_code = 'PKM-<略称>'）
--   - リンクなし商品 11 件（product_code NULL）
--
-- 出典:
--   - 略称(product_code): wiki.pokemonwiki.com 各商品ページの「略称」フィールド
--   - 英語名(name_en): Bulbapedia（公式英語名がない商品は NULL）
--   - 発売日・価格: wiki.pokemonwiki.com 各商品ページ
--
-- 冪等:
--   Phase 1: 既存の短縮名エントリに product_code を付与（重複 INSERT 防止）
--   Phase 2: INSERT ON CONFLICT (product_code) WHERE product_code IS NOT NULL DO UPDATE
--   Phase 3: リンクなし商品は WHERE NOT EXISTS で重複回避
-- ============================================================================
--
-- NEUTRALIZED (ADR-155, 2026-09-18):
-- 商品マスタデータはアプリ画面/CSVで管理する。migrationは構造変更のみ。
-- 元の内容は git history で参照可能。
--

DO $$ BEGIN RAISE NOTICE 'ADR-155 neutralized: Pokemon MEGA product seed removed — manage via app/CSV'; END $$;
