-- 試作版 v102: 「単位にしない言い回し」マスタ（構造のみ。値は管理画面から登録する）
-- 例: ONE PIECE は単位の別名 PIECE を含むが単位ではない。
-- パターン: public + 運営者管理（public.line_units と同じ置き場所・line_ 接頭辞）
-- 値の INSERT/UPDATE/DELETE は含めない（ADR-1007 / ADR-155 の方針）

CREATE TABLE IF NOT EXISTS public.line_unit_ignore_phrases (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase      TEXT NOT NULL,
    note        TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_line_unit_ignore_phrases_phrase UNIQUE (phrase)
);

COMMENT ON TABLE public.line_unit_ignore_phrases
    IS 'LINE解析用 単位にしない言い回しマスタ（単位の別名を含むが単位ではない語。運営者管理）';
COMMENT ON COLUMN public.line_unit_ignore_phrases.id
    IS '主キー（自動採番）';
COMMENT ON COLUMN public.line_unit_ignore_phrases.phrase
    IS '登録した言い回し（例: ONE PIECE）。重複不可';
COMMENT ON COLUMN public.line_unit_ignore_phrases.note
    IS '登録理由（例: 作品名）。NULL可';
COMMENT ON COLUMN public.line_unit_ignore_phrases.is_active
    IS '有効フラグ。falseの言い回しは解析で使わない';
COMMENT ON COLUMN public.line_unit_ignore_phrases.created_at
    IS '作成日時';
COMMENT ON COLUMN public.line_unit_ignore_phrases.updated_at
    IS '最終更新日時（APIが更新時にNOW()を設定）';
