-- ============================================================================
-- ADR-090 PR5c フォローアップ: 既存 public.products の unit / condition を
-- 受信通知の解析結果(parse_result_json)から名前一致で backfill する — 無効化済み
--
-- incident 2026-10-03 (deploy run 37130920016): この UPDATE は public.products.unit /
-- .condition に無条件（列存在ガード無し）でアクセスする。20260602_000000 / 20260602_030000
-- で unit / condition の ADD を削除したため、ガード無しで残すと
-- 「column unit/condition does not exist」でデプロイが失敗する。
--
-- 本番事実（設計担当 Opus が 2026-10-03 に本番 DB を読み取り確認）: この UPDATE は本番で実行済み（deploy run
-- 37130920016 は line 220 のこの migration を通過し、line 230 で失敗）だが、実行後も
-- public.products の unit/condition は count=0（1347行中）であり、書き込むべき対象データが
-- 無かった。この backfill の本来目的（在庫表の「-」表示を埋める）は 2026-06-29 の
-- 20260629_010000（本番 UPDATE 62 件確認済み、public.inventory.unit 側で完了）で
-- 既に果たされている。よって無効化しても挙動に変化はない。
--
-- デプロイ時は何もしない（冪等: 実行するSQL文なし）。登録は維持する（registration check 用）。
-- 詳細: docs/handoff/products-column-churn/design.md
-- ============================================================================
SELECT 1; -- no-op: 1600列上限インシデントのため無効化（対象列は既に public.products から削除・本来目的は本番で達成済み）
