-- ============================================================================
-- Migration 20260919_020000: マスタ SSOT Step 1-4 — public スキーマへ 9 テーブル作成
--
-- 背景:
--   LINE取り込みマスタ（units / conditions / tcg_note_master 等）が
--   tenant_004 スキーマに UUID PK で存在し、SSOT 違反となっている。
--   public スキーマに INTEGER PK の統合テーブルを新設し、
--   全テナントが共用できる単一の真実の源（SSOT）を確立する。
--   仕入元マスタ（public.suppliers）と同方式の設計を踏襲。
--
-- 変更内容（DDLのみ — 値操作は SSH 手動実行で別途実施）:
--   Step 1-4 として以下 9 テーブルを public スキーマに新設:
--     1. public.units              （現: tenant_004.units）
--     2. public.unit_aliases       （現: tenant_004.unit_aliases）
--     3. public.conditions         （現: tenant_004.conditions）
--     4. public.condition_aliases  （現: tenant_004.condition_aliases）
--     5. public.tcg_note_master    （現: tenant_004.tcg_note_master）
--     6. public.tcg_status_master  （現: tenant_004.tcg_status_master）
--     7. public.tcg_product_categories（現: tenant_004.tcg_product_categories）
--     8. public.product_search_keywords （現: tenant_004.product_search_keywords）
--     9. public.product_exclude_keywords（現: tenant_004.product_exclude_keywords）
--
-- 設計判断:
--   - UUID id → INTEGER GENERATED BY DEFAULT AS IDENTITY に統一
--   - text id / status_id → INTEGER GENERATED BY DEFAULT AS IDENTITY
--   - updated_at TIMESTAMPTZ NOT NULL DEFAULT now() を全テーブルに追加（supplier SSOT 踏襲）
--   - FK: unit_aliases→units, condition_aliases→conditions,
--         product_*_keywords→products は本 migration で設定
--   - FK: tcg_type_master は Phase 2 で追加（現時点では未設計）
--   - product_id（search/exclude keywords）は INTEGER のまま維持（既に public.products.id 参照）
--
-- 事後実行（SSH手動・PO許可・本 migration 適用後）:
--   - tenant_004 テーブルから public テーブルへデータコピー（ID マッピング含む）
--   - アプリの参照先を tenant_004.* → public.* に切り替え
--   - tenant_004 旧テーブルの DROP（Phase 2 以降・PO確認後）
--
-- 冪等性:
--   - CREATE TABLE IF NOT EXISTS で全テーブル作成
--   - CREATE INDEX IF NOT EXISTS で全インデックス作成
--   - DO $$ ガードで VIEW の場合はインデックス作成をスキップ（20260922_080000 との共存）
--
-- 注意（ADR-155 migration-guard 制約）:
--   - INSERT/UPDATE/DELETE on 保護テーブルは禁止（Check 7）→ DDL のみ
--   - SELECT on 保護テーブルは禁止（Check 8）→ 存在確認不要（IF NOT EXISTS 使用）
--   - DROP TABLE は本 migration では実施しない（Phase 2 以降・別 migration）
--
-- 背景（VIEW ガード追加・2026-09-22）:
--   20260922_080000_rename_line_analysis_tables.sql が本番環境で先行実行された結果、
--   public.units / public.unit_aliases / public.conditions / public.condition_aliases が
--   VIEW として存在する場合がある。VIEW に対して CREATE INDEX を実行するとエラーになるため、
--   pg_class.relkind='r'（BASE TABLE）のときのみ INDEX を作成するガードを追加。
--
-- 作成日: 2026-09-19
-- 設計: docs/specs/master-ssot-migration/design.md
-- ============================================================================

-- ============================================================================
-- Step 1: public.units
-- 単位マスタ（例: 枚, 冊, 個, BOX 等）
-- 現: tenant_004.units (8 rows, UUID PK)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.units (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR NOT NULL,
    canonical   TEXT NOT NULL,
    kubun       VARCHAR,
    is_active   BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- INDEX ガード: public.units が VIEW の場合はスキップ（20260922_080000 との共存）
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relname = 'units' AND c.relkind = 'r'
    ) THEN
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'units' AND indexname = 'uq_units_code') THEN
            CREATE UNIQUE INDEX uq_units_code ON public.units (code);
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'units' AND indexname = 'idx_units_is_active') THEN
            CREATE INDEX idx_units_is_active ON public.units (is_active);
        END IF;
    ELSE
        RAISE NOTICE 'public.units は TABLE ではありません（VIEW の可能性）— インデックス作成をスキップ';
    END IF;
END $$;

-- ============================================================================
-- Step 2: public.unit_aliases
-- 単位別名マスタ（例: 枚→sheet / 冊→volume 等の多言語対応）
-- 現: tenant_004.unit_aliases (39 rows, UUID PK, UUID FK→units)
-- 注: public.units が VIEW の場合、FK 制約は作成不可のため TABLE の場合のみ作成
-- ============================================================================
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relname = 'units' AND c.relkind = 'r'
    ) THEN
        CREATE TABLE IF NOT EXISTS public.unit_aliases (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            unit_id     INTEGER NOT NULL REFERENCES public.units (id),
            alias_text  TEXT NOT NULL,
            lang        VARCHAR NOT NULL,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
        );
    ELSE
        -- units が VIEW の場合、FK なしで unit_aliases を作成（FK は後続 migration で追加）
        CREATE TABLE IF NOT EXISTS public.unit_aliases (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            unit_id     INTEGER NOT NULL,
            alias_text  TEXT NOT NULL,
            lang        VARCHAR NOT NULL,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        RAISE NOTICE 'public.units は VIEW のため unit_aliases の FK なしで作成';
    END IF;
END $$;

-- INDEX ガード: public.unit_aliases が VIEW の場合はスキップ
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relname = 'unit_aliases' AND c.relkind = 'r'
    ) THEN
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'unit_aliases' AND indexname = 'idx_unit_aliases_unit_id') THEN
            CREATE INDEX idx_unit_aliases_unit_id ON public.unit_aliases (unit_id);
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'unit_aliases' AND indexname = 'uq_unit_aliases_unit_lang') THEN
            CREATE UNIQUE INDEX uq_unit_aliases_unit_lang ON public.unit_aliases (unit_id, lang, alias_text);
        END IF;
    ELSE
        RAISE NOTICE 'public.unit_aliases は TABLE ではありません（VIEW の可能性）— インデックス作成をスキップ';
    END IF;
END $$;

-- ============================================================================
-- Step 3: public.conditions
-- 状態マスタ（例: 新品, 美品, 中古 等）
-- 現: tenant_004.conditions (11 rows, UUID PK)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.conditions (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR NOT NULL,
    canonical   TEXT NOT NULL,
    app_kubun   VARCHAR,
    is_active   BOOLEAN NOT NULL DEFAULT true,
    priority    INTEGER,
    search_kw   TEXT NOT NULL DEFAULT '',
    exclude_kw  TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- INDEX ガード: public.conditions が VIEW の場合はスキップ（20260922_080000 との共存）
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relname = 'conditions' AND c.relkind = 'r'
    ) THEN
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'conditions' AND indexname = 'uq_conditions_code') THEN
            CREATE UNIQUE INDEX uq_conditions_code ON public.conditions (code);
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'conditions' AND indexname = 'idx_conditions_is_active') THEN
            CREATE INDEX idx_conditions_is_active ON public.conditions (is_active);
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'conditions' AND indexname = 'idx_conditions_priority') THEN
            CREATE INDEX idx_conditions_priority ON public.conditions (priority);
        END IF;
    ELSE
        RAISE NOTICE 'public.conditions は TABLE ではありません（VIEW の可能性）— インデックス作成をスキップ';
    END IF;
END $$;

-- ============================================================================
-- Step 4: public.condition_aliases
-- 状態別名マスタ（例: 新品→new / 中古→used 等の多言語対応）
-- 現: tenant_004.condition_aliases (31 rows, UUID PK, UUID FK→conditions)
-- 注: public.conditions が VIEW の場合、FK 制約は作成不可のため TABLE の場合のみ作成
-- ============================================================================
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relname = 'conditions' AND c.relkind = 'r'
    ) THEN
        CREATE TABLE IF NOT EXISTS public.condition_aliases (
            id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            condition_id  INTEGER NOT NULL REFERENCES public.conditions (id),
            alias_text    TEXT NOT NULL,
            lang          VARCHAR NOT NULL,
            updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
        );
    ELSE
        -- conditions が VIEW の場合、FK なしで condition_aliases を作成（FK は後続 migration で追加）
        CREATE TABLE IF NOT EXISTS public.condition_aliases (
            id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            condition_id  INTEGER NOT NULL,
            alias_text    TEXT NOT NULL,
            lang          VARCHAR NOT NULL,
            updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        RAISE NOTICE 'public.conditions は VIEW のため condition_aliases の FK なしで作成';
    END IF;
END $$;

-- INDEX ガード: public.condition_aliases が VIEW の場合はスキップ
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relname = 'condition_aliases' AND c.relkind = 'r'
    ) THEN
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'condition_aliases' AND indexname = 'idx_condition_aliases_condition_id') THEN
            CREATE INDEX idx_condition_aliases_condition_id ON public.condition_aliases (condition_id);
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'condition_aliases' AND indexname = 'uq_condition_aliases_cond_lang') THEN
            CREATE UNIQUE INDEX uq_condition_aliases_cond_lang ON public.condition_aliases (condition_id, lang, alias_text);
        END IF;
    ELSE
        RAISE NOTICE 'public.condition_aliases は TABLE ではありません（VIEW の可能性）— インデックス作成をスキップ';
    END IF;
END $$;

-- ============================================================================
-- Step 5: public.tcg_note_master
-- TCG 備考マスタ（例: 初版, ホログラム加工, 傷あり 等）
-- 現: tenant_004.tcg_note_master (74 rows, text PK)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.tcg_note_master (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label_ja         TEXT NOT NULL,
    label_en         TEXT NOT NULL,
    enabled          BOOLEAN NOT NULL DEFAULT true,
    search_keywords  TEXT NOT NULL DEFAULT '',
    exclude_keywords TEXT NOT NULL DEFAULT '',
    category         TEXT NOT NULL DEFAULT '',
    priority         INTEGER NOT NULL,
    match_type       TEXT NOT NULL DEFAULT 'LITERAL',
    search_pattern   TEXT,
    label_template   TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tcg_note_master_enabled   ON public.tcg_note_master (enabled);
CREATE INDEX IF NOT EXISTS idx_tcg_note_master_priority  ON public.tcg_note_master (priority);
CREATE INDEX IF NOT EXISTS idx_tcg_note_master_category  ON public.tcg_note_master (category);

-- ============================================================================
-- Step 6: public.tcg_status_master
-- TCG ステータスマスタ（例: SOLDOUT, LIMITED, SALE 等）
-- 現: tenant_004.tcg_status_master (9 rows, text PK)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.tcg_status_master (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_id       VARCHAR NOT NULL,
    canonical       TEXT NOT NULL,
    search_pattern  TEXT NOT NULL DEFAULT '',
    exclude_pattern TEXT NOT NULL DEFAULT '',
    priority        INTEGER NOT NULL,
    enabled         BOOLEAN NOT NULL DEFAULT true,
    note            TEXT NOT NULL DEFAULT '',
    match_type      TEXT NOT NULL,
    effect          TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tcg_status_master_status_id ON public.tcg_status_master (status_id);
CREATE INDEX IF NOT EXISTS idx_tcg_status_master_enabled  ON public.tcg_status_master (enabled);
CREATE INDEX IF NOT EXISTS idx_tcg_status_master_priority ON public.tcg_status_master (priority);

-- ============================================================================
-- Step 7: public.tcg_product_categories
-- TCG 商品カテゴリマスタ（例: シングル, BOX 等）
-- 現: tenant_004.tcg_product_categories (2 rows, UUID PK)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.tcg_product_categories (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR NOT NULL,
    display_name  TEXT NOT NULL,
    kubun_type    VARCHAR NOT NULL,
    is_active     BOOLEAN NOT NULL DEFAULT true,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tcg_product_categories_code ON public.tcg_product_categories (code);
CREATE INDEX IF NOT EXISTS idx_tcg_product_categories_is_active ON public.tcg_product_categories (is_active);

-- ============================================================================
-- Step 8: public.product_search_keywords
-- 商品検索キーワードマスタ（現: tenant_004、product_id は既に INTEGER で public.products 参照）
-- 現: tenant_004.product_search_keywords (708 rows, UUID PK)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.product_search_keywords (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword     TEXT NOT NULL,
    position    INTEGER NOT NULL,
    product_id  INTEGER NOT NULL REFERENCES public.products (id),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_product_search_keywords_product_id ON public.product_search_keywords (product_id);
CREATE INDEX IF NOT EXISTS idx_product_search_keywords_position   ON public.product_search_keywords (product_id, position);

-- ============================================================================
-- Step 9: public.product_exclude_keywords
-- 商品除外キーワードマスタ（現: tenant_004、product_id は既に INTEGER で public.products 参照）
-- 現: tenant_004.product_exclude_keywords (291 rows, UUID PK)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.product_exclude_keywords (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword     TEXT NOT NULL,
    position    INTEGER NOT NULL,
    product_id  INTEGER NOT NULL REFERENCES public.products (id),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_product_exclude_keywords_product_id ON public.product_exclude_keywords (product_id);
CREATE INDEX IF NOT EXISTS idx_product_exclude_keywords_position   ON public.product_exclude_keywords (product_id, position);
