-- Foundation F1: public.countries 国台帳（全テナント共有・追加のみ）
-- SSOT: frontend/src/constants/countries.ts
-- 目的: ISO alpha-2 国コード一覧を共有マスタとして提供し、後続 PR で
--       lead.country / company.country_code の統制・backfill に繋ぐ。

CREATE TABLE IF NOT EXISTS public.countries (
    code CHAR(2) PRIMARY KEY,
    name TEXT NOT NULL,
    dial_code TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_countries_active_name
    ON public.countries (is_active, name, code);

CREATE OR REPLACE FUNCTION public.set_updated_at_countries()
RETURNS TRIGGER AS $upd$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$upd$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_set_updated_at_countries ON public.countries;
CREATE TRIGGER trigger_set_updated_at_countries
    BEFORE UPDATE ON public.countries
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_countries();

INSERT INTO public.countries (code, name, dial_code, is_active) VALUES
    ('AF', 'Afghanistan', '+93', TRUE),
    ('AL', 'Albania', '+355', TRUE),
    ('DZ', 'Algeria', '+213', TRUE),
    ('AD', 'Andorra', '+376', TRUE),
    ('AO', 'Angola', '+244', TRUE),
    ('AR', 'Argentina', '+54', TRUE),
    ('AM', 'Armenia', '+374', TRUE),
    ('AU', 'Australia', '+61', TRUE),
    ('AT', 'Austria', '+43', TRUE),
    ('AZ', 'Azerbaijan', '+994', TRUE),
    ('BS', 'Bahamas', '+1', TRUE),
    ('BH', 'Bahrain', '+973', TRUE),
    ('BD', 'Bangladesh', '+880', TRUE),
    ('BB', 'Barbados', '+1', TRUE),
    ('BY', 'Belarus', '+375', TRUE),
    ('BE', 'Belgium', '+32', TRUE),
    ('BZ', 'Belize', '+501', TRUE),
    ('BJ', 'Benin', '+229', TRUE),
    ('BT', 'Bhutan', '+975', TRUE),
    ('BO', 'Bolivia', '+591', TRUE),
    ('BA', 'Bosnia and Herzegovina', '+387', TRUE),
    ('BW', 'Botswana', '+267', TRUE),
    ('BR', 'Brazil', '+55', TRUE),
    ('BN', 'Brunei', '+673', TRUE),
    ('BG', 'Bulgaria', '+359', TRUE),
    ('BF', 'Burkina Faso', '+226', TRUE),
    ('BI', 'Burundi', '+257', TRUE),
    ('KH', 'Cambodia', '+855', TRUE),
    ('CM', 'Cameroon', '+237', TRUE),
    ('CA', 'Canada', '+1', TRUE),
    ('CV', 'Cape Verde', '+238', TRUE),
    ('CF', 'Central African Republic', '+236', TRUE),
    ('TD', 'Chad', '+235', TRUE),
    ('CL', 'Chile', '+56', TRUE),
    ('CN', 'China', '+86', TRUE),
    ('CO', 'Colombia', '+57', TRUE),
    ('KM', 'Comoros', '+269', TRUE),
    ('CG', 'Congo (Brazzaville)', '+242', TRUE),
    ('CD', 'Congo (Kinshasa)', '+243', TRUE),
    ('CR', 'Costa Rica', '+506', TRUE),
    ('HR', 'Croatia', '+385', TRUE),
    ('CU', 'Cuba', '+53', TRUE),
    ('CY', 'Cyprus', '+357', TRUE),
    ('CZ', 'Czech Republic', '+420', TRUE),
    ('DK', 'Denmark', '+45', TRUE),
    ('DJ', 'Djibouti', '+253', TRUE),
    ('DO', 'Dominican Republic', '+1', TRUE),
    ('TL', 'East Timor', '+670', TRUE),
    ('EC', 'Ecuador', '+593', TRUE),
    ('EG', 'Egypt', '+20', TRUE),
    ('SV', 'El Salvador', '+503', TRUE),
    ('GQ', 'Equatorial Guinea', '+240', TRUE),
    ('ER', 'Eritrea', '+291', TRUE),
    ('EE', 'Estonia', '+372', TRUE),
    ('SZ', 'Eswatini', '+268', TRUE),
    ('ET', 'Ethiopia', '+251', TRUE),
    ('FJ', 'Fiji', '+679', TRUE),
    ('FI', 'Finland', '+358', TRUE),
    ('FR', 'France', '+33', TRUE),
    ('GA', 'Gabon', '+241', TRUE),
    ('GM', 'Gambia', '+220', TRUE),
    ('GE', 'Georgia', '+995', TRUE),
    ('DE', 'Germany', '+49', TRUE),
    ('GH', 'Ghana', '+233', TRUE),
    ('GR', 'Greece', '+30', TRUE),
    ('GT', 'Guatemala', '+502', TRUE),
    ('GN', 'Guinea', '+224', TRUE),
    ('GW', 'Guinea-Bissau', '+245', TRUE),
    ('GY', 'Guyana', '+592', TRUE),
    ('HT', 'Haiti', '+509', TRUE),
    ('HN', 'Honduras', '+504', TRUE),
    ('HK', 'Hong Kong', '+852', TRUE),
    ('HU', 'Hungary', '+36', TRUE),
    ('IS', 'Iceland', '+354', TRUE),
    ('IN', 'India', '+91', TRUE),
    ('ID', 'Indonesia', '+62', TRUE),
    ('IR', 'Iran', '+98', TRUE),
    ('IQ', 'Iraq', '+964', TRUE),
    ('IE', 'Ireland', '+353', TRUE),
    ('IL', 'Israel', '+972', TRUE),
    ('IT', 'Italy', '+39', TRUE),
    ('CI', 'Ivory Coast', '+225', TRUE),
    ('JM', 'Jamaica', '+1', TRUE),
    ('JP', 'Japan', '+81', TRUE),
    ('JO', 'Jordan', '+962', TRUE),
    ('KZ', 'Kazakhstan', '+7', TRUE),
    ('KE', 'Kenya', '+254', TRUE),
    ('KI', 'Kiribati', '+686', TRUE),
    ('KW', 'Kuwait', '+965', TRUE),
    ('KG', 'Kyrgyzstan', '+996', TRUE),
    ('LA', 'Laos', '+856', TRUE),
    ('LV', 'Latvia', '+371', TRUE),
    ('LB', 'Lebanon', '+961', TRUE),
    ('LS', 'Lesotho', '+266', TRUE),
    ('LR', 'Liberia', '+231', TRUE),
    ('LY', 'Libya', '+218', TRUE),
    ('LI', 'Liechtenstein', '+423', TRUE),
    ('LT', 'Lithuania', '+370', TRUE),
    ('LU', 'Luxembourg', '+352', TRUE),
    ('MO', 'Macau', '+853', TRUE),
    ('MG', 'Madagascar', '+261', TRUE),
    ('MW', 'Malawi', '+265', TRUE),
    ('MY', 'Malaysia', '+60', TRUE),
    ('MV', 'Maldives', '+960', TRUE),
    ('ML', 'Mali', '+223', TRUE),
    ('MT', 'Malta', '+356', TRUE),
    ('MH', 'Marshall Islands', '+692', TRUE),
    ('MR', 'Mauritania', '+222', TRUE),
    ('MU', 'Mauritius', '+230', TRUE),
    ('MX', 'Mexico', '+52', TRUE),
    ('FM', 'Micronesia', '+691', TRUE),
    ('MD', 'Moldova', '+373', TRUE),
    ('MC', 'Monaco', '+377', TRUE),
    ('MN', 'Mongolia', '+976', TRUE),
    ('ME', 'Montenegro', '+382', TRUE),
    ('MA', 'Morocco', '+212', TRUE),
    ('MZ', 'Mozambique', '+258', TRUE),
    ('MM', 'Myanmar', '+95', TRUE),
    ('NA', 'Namibia', '+264', TRUE),
    ('NR', 'Nauru', '+674', TRUE),
    ('NP', 'Nepal', '+977', TRUE),
    ('NL', 'Netherlands', '+31', TRUE),
    ('NZ', 'New Zealand', '+64', TRUE),
    ('NI', 'Nicaragua', '+505', TRUE),
    ('NE', 'Niger', '+227', TRUE),
    ('NG', 'Nigeria', '+234', TRUE),
    ('KP', 'North Korea', '+850', TRUE),
    ('MK', 'North Macedonia', '+389', TRUE),
    ('NO', 'Norway', '+47', TRUE),
    ('OM', 'Oman', '+968', TRUE),
    ('PK', 'Pakistan', '+92', TRUE),
    ('PW', 'Palau', '+680', TRUE),
    ('PA', 'Panama', '+507', TRUE),
    ('PG', 'Papua New Guinea', '+675', TRUE),
    ('PY', 'Paraguay', '+595', TRUE),
    ('PE', 'Peru', '+51', TRUE),
    ('PH', 'Philippines', '+63', TRUE),
    ('PL', 'Poland', '+48', TRUE),
    ('PT', 'Portugal', '+351', TRUE),
    ('QA', 'Qatar', '+974', TRUE),
    ('RO', 'Romania', '+40', TRUE),
    ('RU', 'Russia', '+7', TRUE),
    ('RW', 'Rwanda', '+250', TRUE),
    ('WS', 'Samoa', '+685', TRUE),
    ('SM', 'San Marino', '+378', TRUE),
    ('SA', 'Saudi Arabia', '+966', TRUE),
    ('SN', 'Senegal', '+221', TRUE),
    ('RS', 'Serbia', '+381', TRUE),
    ('SC', 'Seychelles', '+248', TRUE),
    ('SL', 'Sierra Leone', '+232', TRUE),
    ('SG', 'Singapore', '+65', TRUE),
    ('SK', 'Slovakia', '+421', TRUE),
    ('SI', 'Slovenia', '+386', TRUE),
    ('SB', 'Solomon Islands', '+677', TRUE),
    ('SO', 'Somalia', '+252', TRUE),
    ('ZA', 'South Africa', '+27', TRUE),
    ('KR', 'South Korea', '+82', TRUE),
    ('SS', 'South Sudan', '+211', TRUE),
    ('ES', 'Spain', '+34', TRUE),
    ('LK', 'Sri Lanka', '+94', TRUE),
    ('SD', 'Sudan', '+249', TRUE),
    ('SR', 'Suriname', '+597', TRUE),
    ('SE', 'Sweden', '+46', TRUE),
    ('CH', 'Switzerland', '+41', TRUE),
    ('SY', 'Syria', '+963', TRUE),
    ('TW', 'Taiwan', '+886', TRUE),
    ('TJ', 'Tajikistan', '+992', TRUE),
    ('TZ', 'Tanzania', '+255', TRUE),
    ('TH', 'Thailand', '+66', TRUE),
    ('TG', 'Togo', '+228', TRUE),
    ('TO', 'Tonga', '+676', TRUE),
    ('TT', 'Trinidad and Tobago', '+1', TRUE),
    ('TN', 'Tunisia', '+216', TRUE),
    ('TR', 'Turkey', '+90', TRUE),
    ('TM', 'Turkmenistan', '+993', TRUE),
    ('TV', 'Tuvalu', '+688', TRUE),
    ('UG', 'Uganda', '+256', TRUE),
    ('UA', 'Ukraine', '+380', TRUE),
    ('AE', 'United Arab Emirates', '+971', TRUE),
    ('GB', 'United Kingdom', '+44', TRUE),
    ('US', 'United States', '+1', TRUE),
    ('UY', 'Uruguay', '+598', TRUE),
    ('UZ', 'Uzbekistan', '+998', TRUE),
    ('VU', 'Vanuatu', '+678', TRUE),
    ('VA', 'Vatican City', '+379', TRUE),
    ('VE', 'Venezuela', '+58', TRUE),
    ('VN', 'Vietnam', '+84', TRUE),
    ('YE', 'Yemen', '+967', TRUE),
    ('ZM', 'Zambia', '+260', TRUE),
    ('ZW', 'Zimbabwe', '+263', TRUE)
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    dial_code = EXCLUDED.dial_code,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

COMMENT ON TABLE public.countries IS '国マスタ（ISO 3166-1 alpha-2 / 全テナント共有）';
