-- §D01: 決済手数料設定マスタ
-- パターン: public + NULLパターン（public.unitsと同一方式）
-- tenant_id IS NULL = 共用デフォルト（運営者管理）
-- tenant_id = X    = テナント独自設定
-- 初期データは管理画面（super-admin API）から投入すること

CREATE TABLE IF NOT EXISTS public.payment_fee_settings (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       INTEGER REFERENCES public.tenants(id),
    service         VARCHAR(30)    NOT NULL,
    fee_type        VARCHAR(50)    NOT NULL,
    rate_pct        NUMERIC(8,4)   NOT NULL DEFAULT 0,
    fixed_amount    NUMERIC(14,2)  NOT NULL DEFAULT 0,
    threshold       NUMERIC(14,2),
    threshold_rule  VARCHAR(10),
    currency        VARCHAR(3)     NOT NULL DEFAULT 'JPY',
    effective_from  DATE           NOT NULL,
    effective_to    DATE,
    source_url      TEXT,
    note            TEXT,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_fee_setting
        UNIQUE (tenant_id, service, fee_type, currency, effective_from)
);

CREATE OR REPLACE FUNCTION public.set_updated_at_payment_fee_settings()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_updated_at_payment_fee_settings
    BEFORE UPDATE ON public.payment_fee_settings
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_payment_fee_settings();

COMMENT ON TABLE public.payment_fee_settings
    IS '決済サービスの手数料設定マスタ（共用デフォルト＋テナント独自追加）';
