-- ============================================================================
-- Migration 20260604_040000: 8 TCG シリーズの商品マスタを中央カタログへ投入
--
-- 対象 8 シリーズ（計 1049 件）:
--   ユニオンアリーナ / 遊戯王 / ガンダム / ヴァイスシュヴァルツ /
--   デジモン / ホロライブ / ディズニーロルカナ / ポケモン(SV)
--
-- ADR-090: 在庫(products)は public 中央カタログ（tenant_id=NULL）。在庫数は 0
-- （実在庫は仕入元オファーで管理）。dragonball seed(20260603_030000) を踏襲。
--
-- 冪等: product_code の partial UNIQUE (uq_public_products_code) で
--       ON CONFLICT(product_code) WHERE product_code IS NOT NULL DO UPDATE。
--       tcg_type_master は ON CONFLICT(code) DO NOTHING。再走しても重複しない。
--
-- ⚠ 朝ひとし確認: ポケモン(SV) 45 件は product_code='PKM-<略称>' で投入する。
--   既存 public.products に同一 PKM- コードがあれば ON CONFLICT で「活かして更新」される
--   （二重登録はしない）。既存に PKM- が無ければ新規。現行 migrations には PKM- seed は
--   無いが、本番 public.products の手投入分と衝突する可能性は残るため要目視確認。
--
-- ⚠ 重複 product_code の扱い: 入力の 'PKM-SVD'（exスタートデッキ）10 件は同一 mark='SVD' で
--   product_code が重複する。各々別商品なので 'PKM-SVD-01'〜'PKM-SVD-10' へ決定的にリネーム
--   して全件保持する（同一 INSERT 内の ON CONFLICT 二重更新エラー回避 + 商品の取りこぼし防止）。
--
-- 型番未確定(note='型番未確定') 27 件（遊戯王15 / ホロライブ1 / ロルカナ11）は
--   mark フォールバック値のまま投入する。
--
-- 本ファイルは Python(/tmp/gen_tcg_products_migration.py)で JSON から自動生成。手書き禁止。
-- ============================================================================
--
-- NEUTRALIZED (ADR-155, 2026-09-18):
-- 商品マスタデータはアプリ画面/CSVで管理する。migrationは構造変更のみ。
-- 元の内容は git history で参照可能。
--

DO $$ BEGIN RAISE NOTICE 'ADR-155 neutralized: 8-series 1049 product seed removed — manage via app/CSV'; END $$;
