-- ============================================================================
-- Migration 20260616_000000: tcg_type_master 重複 code 統合
--
-- 問題:
--   migration 085 で pokemon_booster_box（ポケモンカード）を登録済み。
--   migration 086 で weiss_schwarz（ヴァイスシュヴァルツ）を登録済み。
--   20260604_040000_seed_tcg_products_8series.sql が上記と重複する
--   pokemon（ポケモンカードゲーム）/ weiss（ヴァイスシュヴァルツ）を追加したため
--   UI の絞り込みドロップダウンに同名種別が2件ずつ表示されていた。
--
-- 修正:
--   1. products.tcg_type を正規 code へ統一
--      'pokemon' → 'pokemon_booster_box'
--      'weiss'   → 'weiss_schwarz'
--   2. 重複 tcg_type_master 行（pokemon / weiss）を削除
--
-- 冪等: WHERE 句が一致しない場合は何も変わらない。
-- ============================================================================

-- NEUTRALIZED (ADR-1007 / ADR-155, 2026-10-07):
-- products.tcg_type の付け替えと type_master の旧コード削除を外した（本番は 0 行）。
-- 元の内容は git history で参照可能。
DO $$ BEGIN RAISE NOTICE 'ADR-1007 neutralized: tcg_type dedup update/delete removed'; END $$;
