from __future__ import annotations

import os
from contextlib import ExitStack
from unittest.mock import AsyncMock, patch

import pytest
from fastapi import FastAPI
from httpx import ASGITransport, AsyncClient
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

from app.auth.dependencies import get_current_tenant, get_current_user
from app.database import get_db
from app.models import User
from app.routers import leads as leads_router
from app.services import tenant as tenant_service
from app.services.channel_masters import DEFAULT_CHANNEL_MASTERS
from scripts.migrate_20260621_030000_backfill_lead_channel_type import backfill_schema

ADMIN_PG_URL = os.getenv("RLS_ADMIN_DATABASE_URL") or os.getenv("TEST_PG_URL")
APP_PG_URL = os.getenv("RLS_TEST_DATABASE_URL")


def _mock_user(tenant_id: int = 999):
    user = User()
    user.id = 999
    user.tenant_id = tenant_id
    user.username = "channel-tester"
    user.email = "channel@test.example.com"
    user.role = "admin"
    user.is_active = True
    return user


async def _ensure_tenant_006_schema(
    admin_engine,
) -> None:
    async with admin_engine.connect() as conn:
        schema_exists = await conn.scalar(
            text(
                "SELECT 1 FROM information_schema.schemata "
                "WHERE schema_name = 'tenant_006'"
            )
        )
    if schema_exists:
        return

    async with admin_engine.begin() as conn:
        await conn.execute(text("CREATE SCHEMA IF NOT EXISTS tenant_006"))
        await conn.execute(text("""
            CREATE TABLE IF NOT EXISTS tenant_006.leads (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id INTEGER NOT NULL DEFAULT 999,
                lead_code VARCHAR(20),
                customer_name VARCHAR(255) NOT NULL,
                company_name VARCHAR(255),
                email VARCHAR(255),
                phone VARCHAR(50),
                channel_type VARCHAR(30),
                initiative VARCHAR(10),
                type VARCHAR(50),
                status VARCHAR(50) DEFAULT 'lead',
                temperature VARCHAR(20),
                estimated_scale VARCHAR(20),
                customer_type VARCHAR(50),
                response_speed VARCHAR(20),
                monthly_forecast NUMERIC(15, 2),
                prospect_rank VARCHAR(10),
                assigned_to INTEGER,
                converted_deal_id INTEGER,
                notes TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                next_action VARCHAR(500),
                next_action_date DATE,
                challenge TEXT,
                meeting_memo TEXT,
                meeting_impression VARCHAR(50),
                cs_memo TEXT,
                sales_form VARCHAR(50),
                competitor_check BOOLEAN NOT NULL DEFAULT 0,
                per_order_amount NUMERIC(15, 2),
                monthly_frequency NUMERIC(10, 2),
                nickname VARCHAR(255),
                country VARCHAR(100),
                target_titles VARCHAR(500),
                messenger_link VARCHAR(1000),
                discord_id VARCHAR(255),
                instagram_link VARCHAR(1000),
                whatsapp_link VARCHAR(1000),
                discord_user_id VARCHAR(50),
                discord_dm_channel_id VARCHAR(50),
                discord_role_sync_status VARCHAR(20),
                discord_role_sync_at TIMESTAMP,
                discord_guild_channel_id VARCHAR(50)
            )
        """))
        await conn.execute(text("""
            CREATE TABLE IF NOT EXISTS tenant_006.channel_masters (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id INTEGER NOT NULL DEFAULT 999,
                platform VARCHAR(30) NOT NULL UNIQUE,
                display_name VARCHAR(100) NOT NULL,
                connection_type VARCHAR(10) NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """))
        for platform, display_name, connection_type in DEFAULT_CHANNEL_MASTERS:
            await conn.execute(
                text("""
                    INSERT INTO tenant_006.channel_masters
                        (tenant_id, platform, display_name, connection_type, is_active)
                    VALUES (6, :platform, :display_name, :connection_type, 1)
                    ON CONFLICT (platform) DO NOTHING
                """),
                {
                    "platform": platform,
                    "display_name": display_name,
                    "connection_type": connection_type,
                },
            )


@pytest.mark.asyncio
async def test_channel_masters_seeded_and_lead_channel_type_is_dropdown_friendly(client):
    channel_res = await client.get("/api/v1/channel-masters")
    assert channel_res.status_code == 200, channel_res.text
    channels = channel_res.json()
    platforms = [row["platform"] for row in channels]
    assert "whatsapp" in platforms
    assert "messenger" in platforms
    assert "instagram" in platforms
    assert "discord" in platforms
    assert "phone" in platforms
    assert "in_person" in platforms

    create_res = await client.post(
        "/api/v1/leads",
        json={
            "customer_name": "Channel Control Lead",
            "channel_type": "whatsapp_personal",
        },
    )
    assert create_res.status_code == 201, create_res.text
    body = create_res.json()
    assert body["channel_type"] == "whatsapp"

    lead_id = body["id"]
    patch_res = await client.patch(
        f"/api/v1/leads/{lead_id}",
        json={
            "notes": "updated through controlled dropdown",
            "channel_type": "phone",
        },
    )
    assert patch_res.status_code == 200, patch_res.text
    assert patch_res.json()["channel_type"] == "phone"

    invalid = await client.post(
        "/api/v1/leads",
        json={
            "customer_name": "Invalid Channel Lead",
            "channel_type": "unknown_platform",
        },
    )
    assert invalid.status_code == 422


@pytest.mark.asyncio
async def test_create_tenant_schema_seeds_channel_masters(monkeypatch):
    db = AsyncMock()
    ddl_db = AsyncMock()

    async def noop(*args, **kwargs):
        return None

    monkeypatch.setattr(tenant_service, "_execute_statements_preserving_do_blocks", noop)
    monkeypatch.setattr(tenant_service, "seed_system_roles", AsyncMock())
    seed_mock = AsyncMock()
    monkeypatch.setattr(tenant_service, "seed_default_channel_masters", seed_mock)
    monkeypatch.setattr(tenant_service, "_META_PAGE_ROUTING_TRIGGER_SQL", "SELECT 1")
    monkeypatch.setattr(ddl_db, "execute", AsyncMock())
    monkeypatch.setattr(db, "execute", AsyncMock())

    schema = await tenant_service.create_tenant_schema(db, 7, admin_db=ddl_db)
    assert schema == "tenant_007"
    seed_mock.assert_awaited_once_with(db, 7, "tenant_007")


@pytest.mark.skipif(
    not ADMIN_PG_URL or not APP_PG_URL,
    reason="実 PostgreSQL 環境が必要 (RLS_ADMIN_DATABASE_URL / RLS_TEST_DATABASE_URL / TEST_PG_URL 未設定)。",
)
@pytest.mark.asyncio
async def test_channel_type_backfill_normalizes_and_seeds_whatsapp_under_tenant_006():
    admin_engine = create_async_engine(ADMIN_PG_URL, echo=False)
    app_engine = create_async_engine(APP_PG_URL, echo=False)
    app_session_factory = sessionmaker(app_engine, class_=AsyncSession, expire_on_commit=False)

    async def override_get_db():
        async with app_session_factory() as session:
            yield session

    lead_ids: list[int] = []

    try:
        tenant_id = 6
        await _ensure_tenant_006_schema(admin_engine)

        async with admin_engine.begin() as conn:
            result = await conn.execute(
                text(
                    """
                    INSERT INTO tenant_006.leads (tenant_id, customer_name, status, channel_type)
                    VALUES (:tenant_id, :customer_name, 'lead', :channel_type)
                    RETURNING id
                    """
                ),
                {"tenant_id": tenant_id, "customer_name": "Channel Backfill WhatsApp", "channel_type": "whatsapp_personal"},
            )
            lead_ids.append(result.scalar_one())

            result = await conn.execute(
                text(
                    """
                    INSERT INTO tenant_006.leads (tenant_id, customer_name, status, channel_type)
                    VALUES (:tenant_id, :customer_name, 'lead', :channel_type)
                    RETURNING id
                    """
                ),
                {"tenant_id": tenant_id, "customer_name": "Channel Backfill Rare", "channel_type": "cold_call"},
            )
            lead_ids.append(result.scalar_one())

            result = await conn.execute(
                text(
                    """
                    INSERT INTO tenant_006.leads (tenant_id, customer_name, status, channel_type)
                    VALUES (:tenant_id, :customer_name, 'lead', :channel_type)
                    RETURNING id
                    """
                ),
                {"tenant_id": tenant_id, "customer_name": "Channel Backfill Messenger", "channel_type": "messenger"},
            )
            lead_ids.append(result.scalar_one())

        async with admin_engine.begin() as conn:
            counts = await backfill_schema(conn, "tenant_006", int(tenant_id), dry_run=False)

        assert int(counts["normalized"]) >= 1
        assert int(counts["nulled"]) >= 1

        app = FastAPI()
        app.include_router(leads_router.router, prefix="/api/v1")
        app.dependency_overrides[get_db] = override_get_db
        app.dependency_overrides[get_current_user] = lambda: _mock_user(tenant_id=int(tenant_id))
        app.dependency_overrides[get_current_tenant] = lambda: int(tenant_id)

        with ExitStack() as stack:
            stack.enter_context(
                patch("app.routers.leads.invalidate_dashboard_cache", new=AsyncMock(return_value=None))
            )
            transport = ASGITransport(app=app)
            async with AsyncClient(transport=transport, base_url="http://test") as ac:
                lead_res = await ac.get(f"/api/v1/leads/{lead_ids[0]}")
                assert lead_res.status_code == 200, lead_res.text
                assert lead_res.json()["channel_type"] == "whatsapp"

        async with app_session_factory() as session:
            async with session.begin():
                await session.execute(
                    text("SELECT set_config('app.tenant_id', :tenant_id, true)"),
                    {"tenant_id": str(tenant_id)},
                )
                channel_rows = (
                    await session.execute(
                        text(
                            "SELECT platform, display_name, connection_type "
                            "FROM tenant_006.channel_masters ORDER BY platform"
                        )
                    )
                ).mappings().all()
                assert {row["platform"] for row in channel_rows} >= {
                    "messenger",
                    "instagram",
                    "discord",
                    "phone",
                    "in_person",
                    "whatsapp",
                }

                lead_rows = []
                for lead_id in lead_ids:
                    row = await session.execute(
                        text("SELECT channel_type FROM tenant_006.leads WHERE id = :id"),
                        {"id": lead_id},
                    )
                    lead_rows.append(row.scalar_one_or_none())
                assert set(lead_rows) == {"whatsapp", None, "messenger"}
    finally:
        async with admin_engine.begin() as conn:
            for lead_id in lead_ids:
                await conn.execute(
                    text("DELETE FROM tenant_006.leads WHERE id = :id"),
                    {"id": lead_id},
                )
        await admin_engine.dispose()
        await app_engine.dispose()
