from __future__ import annotations

import os
from contextlib import suppress

import pytest
from fastapi import FastAPI
from httpx import ASGITransport, AsyncClient
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

from app.auth.dependencies import get_current_tenant, get_current_user
from app.database import get_db
from app.models import User
from app.routers import analytics as analytics_router
from app.routers.analytics import conversion_by_attribute_summary

ADMIN_PG_URL = os.getenv("RLS_ADMIN_DATABASE_URL") or os.getenv("TEST_PG_URL")
APP_PG_URL = os.getenv("RLS_TEST_DATABASE_URL")

app = FastAPI()
app.include_router(analytics_router.router, prefix="/api/v1")
WORK_SCHEMA = "tenant_006_w2_attr"
FOREIGN_SCHEMA = "tenant_998_w2_attr"


def _build_user(user_id: int, tenant_id: int, role: str = "admin") -> User:
    user = User()
    user.id = user_id
    user.tenant_id = tenant_id
    user.username = "analytics-rls"
    user.email = "analytics-rls@example.com"
    user.role = role
    user.is_active = True
    return user


async def _ensure_foreign_schema(admin_engine) -> None:
    async with admin_engine.begin() as conn:
        await conn.execute(text(f"CREATE SCHEMA IF NOT EXISTS {FOREIGN_SCHEMA}"))
        await conn.execute(text(f"""
            CREATE TABLE IF NOT EXISTS {FOREIGN_SCHEMA}.leads (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id INTEGER NOT NULL DEFAULT 998,
                customer_name VARCHAR(255) NOT NULL,
                channel_type VARCHAR(30),
                country VARCHAR(100),
                sales_form VARCHAR(50),
                temperature VARCHAR(20),
                response_speed VARCHAR(20),
                assigned_to INTEGER,
                converted_deal_id INTEGER,
                monthly_forecast NUMERIC(15, 2),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """))
        await conn.execute(text(f"ALTER TABLE {FOREIGN_SCHEMA}.leads ENABLE ROW LEVEL SECURITY"))
        await conn.execute(text(f"ALTER TABLE {FOREIGN_SCHEMA}.leads FORCE ROW LEVEL SECURITY"))
        await conn.execute(text(f"DROP POLICY IF EXISTS tenant_isolation_leads ON {FOREIGN_SCHEMA}.leads"))
        await conn.execute(text(f"""
            CREATE POLICY tenant_isolation_leads ON {FOREIGN_SCHEMA}.leads
                USING (tenant_id = current_setting('app.tenant_id', true)::INTEGER)
        """))
        await conn.execute(text(f"GRANT USAGE ON SCHEMA {FOREIGN_SCHEMA} TO salesanchor_app"))
        await conn.execute(text(f"GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {FOREIGN_SCHEMA} TO salesanchor_app"))


async def _ensure_work_schema(admin_engine) -> None:
    async with admin_engine.begin() as conn:
        await conn.execute(text(f"CREATE SCHEMA IF NOT EXISTS {WORK_SCHEMA}"))
        await conn.execute(text(f"""
            CREATE TABLE IF NOT EXISTS {WORK_SCHEMA}.leads (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id INTEGER NOT NULL,
                customer_name VARCHAR(255) NOT NULL,
                channel_type VARCHAR(30),
                country VARCHAR(100),
                sales_form VARCHAR(50),
                temperature VARCHAR(20),
                response_speed VARCHAR(20),
                assigned_to INTEGER,
                converted_deal_id INTEGER,
                monthly_forecast NUMERIC(15, 2),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """))
        await conn.execute(text(f"ALTER TABLE {WORK_SCHEMA}.leads ENABLE ROW LEVEL SECURITY"))
        await conn.execute(text(f"ALTER TABLE {WORK_SCHEMA}.leads FORCE ROW LEVEL SECURITY"))
        await conn.execute(text(f"DROP POLICY IF EXISTS tenant_isolation_leads ON {WORK_SCHEMA}.leads"))
        await conn.execute(text(f"""
            CREATE POLICY tenant_isolation_leads ON {WORK_SCHEMA}.leads
                USING (tenant_id = current_setting('app.tenant_id', true)::INTEGER)
        """))
        await conn.execute(text(f"GRANT USAGE ON SCHEMA {WORK_SCHEMA} TO salesanchor_app"))
        await conn.execute(text(f"GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {WORK_SCHEMA} TO salesanchor_app"))


@pytest.mark.skipif(
    not ADMIN_PG_URL or not APP_PG_URL,
    reason="実 PostgreSQL 環境が必要 (RLS_ADMIN_DATABASE_URL / RLS_TEST_DATABASE_URL / TEST_PG_URL 未設定)。",
)
@pytest.mark.asyncio
async def test_conversion_by_attribute_rls_team_and_mine_under_tenant_006():
    admin_engine = create_async_engine(ADMIN_PG_URL, echo=False)
    app_engine = create_async_engine(APP_PG_URL, echo=False)
    app_session_factory = sessionmaker(app_engine, class_=AsyncSession, expire_on_commit=False)

    async def override_get_db():
        async with app_session_factory() as session:
            async with session.begin():
                await session.execute(text(f"SET search_path = {WORK_SCHEMA}, public"))
                await session.execute(text("SET app.tenant_id = '6'"))
                await session.execute(text("SET app.is_operator = ''"))
                yield session

    inserted_rows: list[int] = []
    foreign_rows: list[int] = []

    try:
        tenant_id = 6
        current_user = _build_user(999, tenant_id, "admin")

        async def override_get_current_user():
            return current_user

        async def override_get_current_tenant():
            return tenant_id

        app.dependency_overrides[get_db] = override_get_db
        app.dependency_overrides[get_current_user] = override_get_current_user
        app.dependency_overrides[get_current_tenant] = override_get_current_tenant
        await _ensure_work_schema(admin_engine)
        await _ensure_foreign_schema(admin_engine)

        async with admin_engine.begin() as conn:
            lead_result = await conn.execute(
                text("""
                    INSERT INTO tenant_006_w2_attr.leads (
                        tenant_id, customer_name, channel_type, country, sales_form,
                        temperature, response_speed, assigned_to, converted_deal_id, monthly_forecast, created_at
                    )
                    VALUES
                        (:tenant_id, 'RLS-Lead-1', 'instagram', 'JP', 'physical_store', 'Hot', '24h以内', :uid, 1001, 100, NOW()),
                        (:tenant_id, 'RLS-Lead-2', 'instagram', 'JP', 'physical_store', 'Hot', '24h以内', :uid, NULL, 300, NOW()),
                        (:tenant_id, 'RLS-Lead-3', 'cold_call', 'US', NULL, 'Cold', '3日超', :uid, NULL, NULL, NOW()),
                        (:tenant_id, 'RLS-Lead-4', 'messenger', 'CA', 'online', 'Warm', '3日以内', :other_uid, NULL, 900, NOW())
                    RETURNING id
                """),
                {
                    "tenant_id": tenant_id,
                    "uid": current_user.id,
                    "other_uid": current_user.id + 1,
                },
            )
            inserted_rows.extend(int(row_id) for row_id in lead_result.scalars().all())

        async with app_session_factory() as session:
            async with session.begin():
                await session.execute(text(f"SET LOCAL search_path = {WORK_SCHEMA}, public"))
                await session.execute(text("SET LOCAL app.tenant_id = '6'"))
                await session.execute(text("SET LOCAL app.is_operator = ''"))

                # FastAPI dependency 解決を介さず、同一 session の RLS クエリを直接検証する。
                team = await conversion_by_attribute_summary(
                    scope="team",
                    db=session,
                    tenant_id=tenant_id,
                    current_user=current_user,
                )
                assert team.channel_type.overall_rate == pytest.approx(0.25, abs=1e-4)
                team_channels = {row.value: row for row in team.channel_type.items}
                assert team_channels["instagram"].n == 2
                assert team_channels["instagram"].conversions == 1
                assert team_channels["cold_call"].n == 1
                assert team_channels["cold_call"].conversions == 0
                assert team_channels["cold_call"].smoothed_rate == pytest.approx((10 * 0.25) / 11, abs=1e-4)

                mine = await conversion_by_attribute_summary(
                    scope="mine",
                    db=session,
                    tenant_id=tenant_id,
                    current_user=current_user,
                )
                assert mine.channel_type.overall_rate == pytest.approx(1 / 3, abs=1e-4)

        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://test") as ac:
            priority_res = await ac.get("/api/v1/analytics/priority-prospects?scope=mine")
            assert priority_res.status_code == 200, priority_res.text
            priority = priority_res.json()

            assert priority["scope"] == "mine"
            assert len(priority["items"]) == 3
            ordered_ids = [item["lead_id"] for item in priority["items"]]
            assert ordered_ids == [inserted_rows[1], inserted_rows[2], inserted_rows[0]]

            items = {item["lead_id"]: item for item in priority["items"]}
            assert set(items) == set(inserted_rows[:3])
            assert all(item["type"] == "priority_prospect" for item in items.values())

            for lead_id, item in items.items():
                expected_ease = sum(b["smoothed_rate"] for b in item["axis_breakdown"]) / len(item["axis_breakdown"])
                assert item["ease_pct"] == pytest.approx(expected_ease * 100, abs=1e-4)
                assert item["rank_score"] == pytest.approx(item["ease_pct"] * item["monthly_forecast"], abs=1e-4)
                assert any(flag.endswith(":low_sample") for flag in item["low_sample_flags"])
                if lead_id == inserted_rows[2]:
                    assert len(item["axis_breakdown"]) == 4
                    assert "monthly_forecast_unset" in item["low_sample_flags"]
                    assert item["monthly_forecast"] == pytest.approx(200, abs=1e-4)
                else:
                    assert len(item["axis_breakdown"]) == 5
                    assert "monthly_forecast_unset" not in item["low_sample_flags"]

        async with admin_engine.begin() as conn:
            foreign_result = await conn.execute(
                text("""
                    INSERT INTO tenant_998_w2_attr.leads (
                        tenant_id, customer_name, channel_type, country, sales_form,
                        temperature, response_speed, assigned_to, converted_deal_id, monthly_forecast, created_at
                    )
                    VALUES (
                        998, 'RLS-Other-Lead', 'messenger', 'CA', 'online',
                        'Warm', '3日以内', :other_uid, 2001, 9999, NOW()
                    )
                    RETURNING id
                """),
                {"other_uid": current_user.id + 1},
            )
            foreign_rows.extend(int(row_id) for row_id in foreign_result.scalars().all())

        async with app_session_factory() as session:
            async with session.begin():
                await session.execute(
                    text("SELECT set_config('app.tenant_id', :tenant_id, true)"),
                    {"tenant_id": str(tenant_id)},
                )
                tenant_count = (await session.execute(text(f"SELECT COUNT(*) FROM {WORK_SCHEMA}.leads"))).scalar_one()
                assert tenant_count == 4
                foreign_count = (
                    await session.execute(text(f"SELECT COUNT(*) FROM {FOREIGN_SCHEMA}.leads"))
                ).scalar_one()
                assert foreign_count == 0
    finally:
        app.dependency_overrides.clear()
        with suppress(Exception):
            async with admin_engine.begin() as conn:
                for row_id in inserted_rows:
                    await conn.execute(
                        text(f"DELETE FROM {WORK_SCHEMA}.leads WHERE id = :id"),
                        {"id": row_id},
                    )
                for row_id in foreign_rows:
                    await conn.execute(
                        text(f"DELETE FROM {FOREIGN_SCHEMA}.leads WHERE id = :id"),
                        {"id": row_id},
                    )
                await conn.execute(text(f"DROP SCHEMA IF EXISTS {WORK_SCHEMA} CASCADE"))
                await conn.execute(text(f"DROP SCHEMA IF EXISTS {FOREIGN_SCHEMA} CASCADE"))
        await admin_engine.dispose()
        await app_engine.dispose()
