import { render, screen } from "@testing-library/react";
import { vi, describe, expect, it, beforeEach } from "vitest";
import i18n from "../../i18n";
import { ImportWorkflowPanel } from "./ImportWorkflowPanel";
import { useImportWorkflow } from "./useImportWorkflow";

vi.mock("./useImportWorkflow", () => ({ useImportWorkflow: vi.fn() }));
const base = { scope:{type:"import" as const,import_job_id:"a"},as_of:"2026-09-10T00:00:00Z",coverage:"complete" as const,review_status:"ok",reason:null,messages:{unit:"source_message" as const,total:0},extraction:{unit:"extraction_job" as const,total:0,completed:0,pending:0,running:0,unknown:0,succeeded:0,empty:0,failed:0,residual_results_on_error:0},analysis:{unit:"extraction_item" as const,total:0,results_present:0,results_missing:0,needs_review:0}, };
function mock(overrides: object = {}) { vi.mocked(useImportWorkflow).mockReturnValue({progress:base,items:{...base,total:0,items:[],limit:25,offset:0,filter:"all",unit:"extraction_item" as const},error:null,loading:false,refresh:vi.fn(),lastAsOf:base.as_of,...overrides} as ReturnType<typeof useImportWorkflow>); }
describe("ImportWorkflowPanel",()=>{beforeEach(()=>{void i18n.changeLanguage("en");});it("distinguishes complete zero from legacy unknown",()=>{mock();const {rerender}=render(<ImportWorkflowPanel importJobId="a"/>);expect(screen.getAllByText("There are no extraction targets").length).toBeGreaterThan(0);mock({progress:{...base,coverage:"legacy_unknown",reason:"message_association_not_recorded",messages:{unit:"source_message",total:null,reason:"message_association_not_recorded"}},items:{...base,coverage:"legacy_unknown",reason:"message_association_not_recorded",total:null,items:null,limit:25,offset:0,filter:"all",unit:"extraction_item"}});rerender(<ImportWorkflowPanel importJobId="a"/>);expect(screen.getAllByText(/Not recorded/).length).toBeGreaterThan(0);});it("treats incomplete numeric payload as unknown",()=>{mock({progress:{...base,extraction:{...base.extraction,completed:undefined}}});render(<ImportWorkflowPanel importJobId="a"/>);expect(screen.getAllByText("Extraction status is not recorded").length).toBeGreaterThan(0);expect(screen.queryByRole("img")).toBeNull();});it("shows failure and residual results without success",()=>{mock({progress:{...base,extraction:{...base.extraction,total:57,completed:57,failed:57,succeeded:0,residual_results_on_error:166}}});render(<ImportWorkflowPanel importJobId="a"/>);expect(screen.getAllByText(/Extraction error: 57/).length).toBeGreaterThan(0);expect(screen.getByText(/166/)).toBeTruthy();});it("keeps empty items distinct and disables next at total 25",()=>{mock({items:{...base,total:25,items:[],limit:25,offset:0,filter:"all",unit:"extraction_item"}});render(<ImportWorkflowPanel importJobId="a"/>);expect((screen.getByRole("button",{name:"Next"}) as HTMLButtonElement).disabled).toBe(true);});});
describe("ImportWorkflowPanel",()=>{beforeEach(()=>{void i18n.changeLanguage("en");});it("distinguishes complete zero from legacy unknown",()=>{mock();const {rerender}=render(<ImportWorkflowPanel importJobId="a"/>);expect(screen.getAllByText("There are no extraction targets").length).toBeGreaterThan(0);mock({progress:{...base,coverage:"legacy_unknown",reason:"message_association_not_recorded",messages:{unit:"source_message",total:null,reason:"message_association_not_recorded"}},items:{...base,coverage:"legacy_unknown",reason:"message_association_not_recorded",total:null,items:null,limit:25,offset:0,filter:"all",unit:"extraction_item"}});rerender(<ImportWorkflowPanel importJobId="a"/>);expect(screen.getAllByText(/Not recorded/).length).toBeGreaterThan(0);});it("shows the completed overview and review action",()=>{mock({progress:{...base,messages:{...base.messages,total:51},extraction:{...base.extraction,total:51,completed:51,succeeded:37,empty:14},analysis:{...base.analysis,results_present:1019,needs_review:313}}});render(<ImportWorkflowPanel importJobId="a"/>);expect(screen.getAllByText("Extraction finished").length).toBeGreaterThan(0);expect(screen.getByRole("button",{name:"Review 313 flagged item(s)"})).toBeTruthy();expect(screen.getByText(/Extraction successful/)).toBeTruthy();expect(screen.getByText("1,019")).toBeTruthy();});it("shows known pending and running counts",()=>{mock({progress:{...base,extraction:{...base.extraction,total:3,completed:1,succeeded:1,pending:1,running:1}}});render(<ImportWorkflowPanel importJobId="a"/>);expect(screen.getAllByText(/Pending: 1/).length).toBeGreaterThan(0);expect(screen.getAllByText(/Running: 1/).length).toBeGreaterThan(0);});it.each([{unknown:1},{completed:1.5},{completed:-1},{total:2,completed:1,succeeded:1,pending:0,running:0,unknown:0}])("does not render progress for inconsistent numeric data",(extraction)=>{mock({progress:{...base,extraction:{...base.extraction,...extraction}}});render(<ImportWorkflowPanel importJobId="a"/>);expect(screen.queryByRole("img")).toBeNull();expect(screen.getAllByText("Extraction status is not recorded").length).toBeGreaterThan(0);});it("keeps a known failed count visible when other values are missing",()=>{mock({progress:{...base,extraction:{...base.extraction,completed:undefined,failed:57}}});render(<ImportWorkflowPanel importJobId="a"/>);expect(screen.getAllByText(/Extraction error: 57/).length).toBeGreaterThan(0);});it("keeps empty items distinct and disables next at total 25",()=>{mock({items:{...base,total:25,items:[],limit:25,offset:0,filter:"all",unit:"extraction_item"}});render(<ImportWorkflowPanel importJobId="a"/>);expect((screen.getByRole("button",{name:"Next"}) as HTMLButtonElement).disabled).toBe(true);});});
describe("ImportWorkflowPanel errors",()=>{it("distinguishes initial failure from stale retained data",()=>{mock({progress:null,items:null,error:"network",lastAsOf:null});const {rerender}=render(<ImportWorkflowPanel importJobId="a"/>);expect(screen.getByText(/^Fetch failed\./)).toBeTruthy();expect(screen.queryByText(i18n.t("pmgWorkflow.stale"))).toBeNull();mock({error:"network"});rerender(<ImportWorkflowPanel importJobId="a"/>);expect(screen.getByText(new RegExp(i18n.t("pmgWorkflow.stale")))).toBeTruthy();expect(screen.getByText((_, element) => element?.textContent?.startsWith(i18n.t("pmgWorkflow.asOf")) ?? false)).toBeTruthy();});});
