import { act, cleanup, renderHook, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { useImportWorkflow } from "./useImportWorkflow";
import * as api from "./importWorkflowApi";

vi.mock("./importWorkflowApi", async () => ({ ...(await vi.importActual<typeof api>("./importWorkflowApi")), getImportProgress: vi.fn(), getImportItems: vi.fn() }));
const progress = { scope:{type:"import" as const,import_job_id:"a"},as_of:"2026-01-01",coverage:"legacy_unknown" as const,review_status:"x",reason:null,messages:{unit:"source_message" as const,total:null},extraction:{unit:"extraction_job" as const,total:null},analysis:{unit:"extraction_item" as const,total:null,execution_state:"unrecorded" as const} };
const items = { scope:{type:"import" as const,import_job_id:"a"},as_of:"2026-01-01",coverage:"legacy_unknown" as const,review_status:"x",reason:null,total:null,items:null,limit:25,offset:0,filter:"all" as const,unit:"extraction_item" as const };
const deferred = <T,>() => { let resolve!: (value:T)=>void; let reject!: (reason?:unknown)=>void; const promise = new Promise<T>((res,rej)=>{resolve=res;reject=rej}); return {promise,resolve,reject}; };
beforeEach(()=>vi.resetAllMocks());
afterEach(()=>{cleanup();vi.useRealTimers()});
describe("useImportWorkflow",()=>{
 it("keeps one inflight pair until both settle",async()=>{vi.useFakeTimers();const pending=deferred<typeof items>();vi.mocked(api.getImportProgress).mockRejectedValue(new Error("failed"));vi.mocked(api.getImportItems).mockReturnValue(pending.promise);const {result}=renderHook(()=>useImportWorkflow("a","all",0));await act(async()=>{vi.advanceTimersByTime(5000);result.current.refresh()});expect(api.getImportProgress).toHaveBeenCalledTimes(1);expect(api.getImportItems).toHaveBeenCalledTimes(1)});
 it("does not let late A overwrite B",async()=>{const ap=deferred<typeof progress>(),ai=deferred<typeof items>();vi.mocked(api.getImportProgress).mockImplementationOnce(()=>ap.promise).mockResolvedValueOnce({...progress,scope:{type:"import",import_job_id:"b"}});vi.mocked(api.getImportItems).mockImplementationOnce(()=>ai.promise).mockResolvedValueOnce({...items,scope:{type:"import",import_job_id:"b"}});const {result,rerender}=renderHook(({id})=>useImportWorkflow(id,"all",0),{initialProps:{id:"a"}});rerender({id:"b"});await waitFor(()=>expect(result.current.progress?.scope.import_job_id).toBe("b"));await act(async()=>{ap.resolve(progress);ai.resolve(items)});expect(result.current.progress?.scope.import_job_id).toBe("b")});
 it("does not load while hidden and loads on visible",async()=>{let state="hidden";vi.spyOn(document,"visibilityState","get").mockImplementation(()=>state as DocumentVisibilityState);vi.mocked(api.getImportProgress).mockResolvedValue(progress);vi.mocked(api.getImportItems).mockResolvedValue(items);renderHook(()=>useImportWorkflow("a","all",0));expect(api.getImportProgress).not.toHaveBeenCalled();state="visible";act(()=>document.dispatchEvent(new Event("visibilitychange")));await waitFor(()=>expect(api.getImportProgress).toHaveBeenCalledTimes(1))});
 it("discards a response that crosses hidden state and reloads after visible while inflight",async()=>{let state="visible";const visibilitySpy=vi.spyOn(document,"visibilityState","get").mockImplementation(()=>state as DocumentVisibilityState);const firstProgress=deferred<typeof progress>(),firstItems=deferred<typeof items>(),secondProgress=deferred<typeof progress>(),secondItems=deferred<typeof items>();const refreshedProgress={...progress,as_of:"2026-01-02"},refreshedItems={...items,as_of:"2026-01-02"};vi.mocked(api.getImportProgress).mockImplementationOnce(()=>firstProgress.promise).mockImplementationOnce(()=>secondProgress.promise);vi.mocked(api.getImportItems).mockImplementationOnce(()=>firstItems.promise).mockImplementationOnce(()=>secondItems.promise);const {result}=renderHook(()=>useImportWorkflow("a","all",0));expect(api.getImportProgress).toHaveBeenCalledTimes(1);state="hidden";act(()=>document.dispatchEvent(new Event("visibilitychange")));state="visible";act(()=>document.dispatchEvent(new Event("visibilitychange")));await act(async()=>{firstProgress.resolve(progress);firstItems.resolve(items)});await waitFor(()=>expect(api.getImportProgress).toHaveBeenCalledTimes(2));expect(result.current.progress).toBeNull();expect(result.current.items).toBeNull();await act(async()=>{secondProgress.resolve(refreshedProgress);secondItems.resolve(refreshedItems)});await waitFor(()=>expect(result.current.lastAsOf).toBe("2026-01-02"));expect(result.current.progress).toEqual(refreshedProgress);expect(result.current.items).toEqual(refreshedItems);visibilitySpy.mockRestore()});
 it("hides A data while B is unresolved",async()=>{let resolve!: (v:typeof progress)=>void;vi.mocked(api.getImportProgress).mockResolvedValueOnce(progress).mockImplementationOnce(()=>new Promise(r=>{resolve=r}));vi.mocked(api.getImportItems).mockResolvedValue(items);const {result,rerender}=renderHook(({id})=>useImportWorkflow(id,"all",0),{initialProps:{id:"a"}});await waitFor(()=>expect(result.current.progress).toEqual(progress));rerender({id:"b"});expect(result.current.progress).toBeNull();expect(result.current.items).toBeNull();expect(result.current.lastAsOf).toBeNull();await act(async()=>resolve({...progress,scope:{type:"import",import_job_id:"b"}}))});
 it("does not request with null id",()=>{renderHook(()=>useImportWorkflow(null,"all",0));expect(api.getImportProgress).not.toHaveBeenCalled();expect(api.getImportItems).not.toHaveBeenCalled()});
 it("keeps null legacy values and refreshes",async()=>{vi.mocked(api.getImportProgress).mockResolvedValue(progress);vi.mocked(api.getImportItems).mockResolvedValue(items);const {result}=renderHook(()=>useImportWorkflow("a","all",0));await waitFor(()=>expect(result.current.progress).toEqual(progress));expect(result.current.items?.total).toBeNull();act(()=>result.current.refresh());await waitFor(()=>expect(api.getImportProgress).toHaveBeenCalledTimes(2))});
 it("retains data on polling error",async()=>{vi.useFakeTimers();vi.mocked(api.getImportProgress).mockResolvedValueOnce(progress).mockRejectedValueOnce(new Error("poll"));vi.mocked(api.getImportItems).mockResolvedValue(items);const {result}=renderHook(()=>useImportWorkflow("a","all",0));await act(async()=>{});await act(async()=>{vi.advanceTimersByTime(5000)});expect(result.current.progress).toEqual(progress);expect(result.current.lastAsOf).toBe("2026-01-01");vi.useRealTimers()});
});
