-- dryrun.sql (same as apply.sql but ends with ROLLBACK)
-- Nothing is kept. Shows the final state inside the transaction, then rolls back.
-- Target: DB jarvis_db, schema public. Merge 2 (merge_id dup-merge-2-20261005): 10 duplicate pairs, see specs.json. Generated by gen_sql.py; do not hand-edit.
\set ON_ERROR_STOP on
BEGIN;
SET LOCAL app.is_operator = 'true';
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';
DO $do$
DECLARE
  specs jsonb := $j$[
 {
  "retired": 440573,
  "retired_code": "PM0225",
  "survivor": 398,
  "survivor_code": "UA-PC02BT",
  "ar": 10,
  "flips": 0,
  "flips_to_true": 0,
  "ei": 0,
  "bb": 0,
  "sh": 0,
  "r_skw": 2,
  "r_ekw": 3,
  "s_skw": 2,
  "s_ekw": 0,
  "s_ar": 4,
  "kw": [
   {
    "kind": "search",
    "keyword": "UNION ARENA 勝利の女神NIKKE【PC02BT】"
   },
   {
    "kind": "exclude",
    "keyword": "WS"
   },
   {
    "kind": "exclude",
    "keyword": "ヴァイス"
   },
   {
    "kind": "exclude",
    "keyword": "ヴァイスシュヴァルツ"
   }
  ]
 },
 {
  "retired": 1386,
  "retired_code": "LOR-the-first-chapter",
  "survivor": 440434,
  "survivor_code": "PM0232",
  "ar": 11,
  "flips": 1,
  "flips_to_true": 0,
  "ei": 14,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 14,
  "kw": [
   {
    "kind": "search",
    "keyword": "THE FIRST CHAPTER 物語のはじまり"
   }
  ]
 },
 {
  "retired": 1385,
  "retired_code": "LOR-rise-of-the-floodborn",
  "survivor": 440435,
  "survivor_code": "PM0233",
  "ar": 7,
  "flips": 1,
  "flips_to_true": 0,
  "ei": 4,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 7,
  "kw": [
   {
    "kind": "search",
    "keyword": "RISE OF THE FLOODBORN フラッドボーンの渾沌"
   }
  ]
 },
 {
  "retired": 1384,
  "retired_code": "LOR-into-the-inklands",
  "survivor": 440578,
  "survivor_code": "PM0234",
  "ar": 8,
  "flips": 2,
  "flips_to_true": 0,
  "ei": 8,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 9,
  "kw": [
   {
    "kind": "search",
    "keyword": "INTO THE INKLANDS インクランド探訪"
   }
  ]
 },
 {
  "retired": 1383,
  "retired_code": "LOR-ursulas-return",
  "survivor": 440579,
  "survivor_code": "PM0235",
  "ar": 4,
  "flips": 1,
  "flips_to_true": 0,
  "ei": 4,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 4,
  "kw": [
   {
    "kind": "search",
    "keyword": "URSULA'S RETURN 逆襲のアースラ"
   }
  ]
 },
 {
  "retired": 1382,
  "retired_code": "LOR-shimmering-skies",
  "survivor": 440580,
  "survivor_code": "PM0236",
  "ar": 18,
  "flips": 2,
  "flips_to_true": 0,
  "ei": 22,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 15,
  "kw": [
   {
    "kind": "search",
    "keyword": "SHIMMERING SKIES 星々の輝き"
   }
  ]
 },
 {
  "retired": 1381,
  "retired_code": "LOR-azurite-sea",
  "survivor": 440581,
  "survivor_code": "PM0237",
  "ar": 12,
  "flips": 1,
  "flips_to_true": 0,
  "ei": 16,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 11,
  "kw": [
   {
    "kind": "search",
    "keyword": "AZURITE SEA 大いなるアズライト"
   }
  ]
 },
 {
  "retired": 1380,
  "retired_code": "LOR-archazias-island",
  "survivor": 440582,
  "survivor_code": "PM0238",
  "ar": 4,
  "flips": 1,
  "flips_to_true": 0,
  "ei": 4,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 4,
  "kw": [
   {
    "kind": "search",
    "keyword": "ARCHAZIAS ISLAND アーケイジアと魔法の島"
   }
  ]
 },
 {
  "retired": 1379,
  "retired_code": "LOR-reign-of-jafar",
  "survivor": 440583,
  "survivor_code": "PM0239",
  "ar": 1,
  "flips": 0,
  "flips_to_true": 0,
  "ei": 1,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 0,
  "kw": [
   {
    "kind": "search",
    "keyword": "REIGN OF JAFAR ジャファーの王権"
   }
  ]
 },
 {
  "retired": 1376,
  "retired_code": "LOR-wilds-unknown",
  "survivor": 440587,
  "survivor_code": "PM0243",
  "ar": 0,
  "flips": 0,
  "flips_to_true": 0,
  "ei": 0,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 3,
  "kw": [
   {
    "kind": "search",
    "keyword": "WILDS UNKNOWN 未知なる彼方へ!"
   }
  ]
 }
]$j$::jsonb;
  spec jsonb; r_id int; s_id int; r record; s record; kw jsonb;
  ar_ids jsonb; ei_ids jsonb; bb_ids jsonb; sh_ids jsonb; flips jsonb; kw_ids jsonb; new_kw_id int; next_pos int;
  c int; n_to_true int; s_before int;
  before_snap jsonb; after_snap jsonb; merge_info jsonb; touched int := 0;
BEGIN
  FOR spec IN SELECT * FROM jsonb_array_elements(specs) LOOP
    r_id := (spec->>'retired')::int; s_id := (spec->>'survivor')::int;

    -- 1. lock and guard the two products
    SELECT * INTO r FROM public.products WHERE id = r_id FOR UPDATE;
    SELECT * INTO s FROM public.products WHERE id = s_id FOR UPDATE;
    IF r.id IS NULL OR s.id IS NULL THEN RAISE EXCEPTION 'product missing for pair %', spec; END IF;
    IF r.product_code IS DISTINCT FROM spec->>'retired_code' OR s.product_code IS DISTINCT FROM spec->>'survivor_code'
       OR r.is_active IS NOT TRUE OR s.is_active IS NOT TRUE THEN
      RAISE EXCEPTION 'GUARD pair state: retired % (%, active %), survivor % (%, active %)', r.id, r.product_code, r.is_active, s.id, s.product_code, s.is_active;
    END IF;
    before_snap := jsonb_build_object('retired', jsonb_build_object(
        'product', (SELECT to_jsonb(p) FROM public.products p WHERE p.id = r_id),
        'search_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_search_keywords k WHERE k.product_id = r_id), '[]'::jsonb),
        'exclude_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_exclude_keywords k WHERE k.product_id = r_id), '[]'::jsonb)), 'survivor', jsonb_build_object(
        'product', (SELECT to_jsonb(p) FROM public.products p WHERE p.id = s_id),
        'search_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_search_keywords k WHERE k.product_id = s_id), '[]'::jsonb),
        'exclude_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_exclude_keywords k WHERE k.product_id = s_id), '[]'::jsonb)));

    -- 2. ids of the rows that will be repointed, and exact-count guards
    ar_ids := COALESCE((SELECT jsonb_agg(id::text ORDER BY id::text) FROM public.analysis_results WHERE product_id = r_id), '[]'::jsonb);
    ei_ids := COALESCE((SELECT jsonb_agg(id::text ORDER BY id::text) FROM public.extraction_items WHERE resolved_product_code = r_id::text), '[]'::jsonb);
    bb_ids := COALESCE((SELECT jsonb_agg(id::text ORDER BY id::text) FROM public.buyback_shop_products WHERE product_id = r_id), '[]'::jsonb);
    sh_ids := COALESCE((SELECT jsonb_agg(id::text ORDER BY id::text) FROM public.extraction_shadow_results WHERE product_id = r_id), '[]'::jsonb);
    IF jsonb_array_length(ar_ids) <> (spec->>'ar')::int THEN RAISE EXCEPTION 'GUARD analysis_results for % = % (expected %)', r_id, jsonb_array_length(ar_ids), spec->>'ar'; END IF;
    IF jsonb_array_length(ei_ids) <> (spec->>'ei')::int THEN RAISE EXCEPTION 'GUARD extraction_items for % = % (expected %)', r_id, jsonb_array_length(ei_ids), spec->>'ei'; END IF;
    IF jsonb_array_length(bb_ids) <> (spec->>'bb')::int THEN RAISE EXCEPTION 'GUARD buyback_shop_products for % = % (expected %)', r_id, jsonb_array_length(bb_ids), spec->>'bb'; END IF;
    IF jsonb_array_length(sh_ids) <> (spec->>'sh')::int THEN RAISE EXCEPTION 'GUARD extraction_shadow_results for % = % (expected %)', r_id, jsonb_array_length(sh_ids), spec->>'sh'; END IF;
    SELECT count(*) INTO s_before FROM public.analysis_results WHERE product_id = s_id;
    IF s_before <> (spec->>'s_ar')::int THEN RAISE EXCEPTION 'GUARD survivor % analysis_results = % (expected %)', s_id, s_before, spec->>'s_ar'; END IF;
    SELECT count(*) INTO c FROM public.product_search_keywords WHERE product_id = s_id;
    IF c <> (spec->>'s_skw')::int THEN RAISE EXCEPTION 'GUARD survivor % search keywords = % (expected %)', s_id, c, spec->>'s_skw'; END IF;
    SELECT count(*) INTO c FROM public.product_exclude_keywords WHERE product_id = s_id;
    IF c <> (spec->>'s_ekw')::int THEN RAISE EXCEPTION 'GUARD survivor % exclude keywords = % (expected %)', s_id, c, spec->>'s_ekw'; END IF;
    SELECT count(*) INTO c FROM public.product_search_keywords WHERE product_id = r_id;
    IF c <> (spec->>'r_skw')::int THEN RAISE EXCEPTION 'GUARD retired % search keywords = % (expected %)', r_id, c, spec->>'r_skw'; END IF;
    SELECT count(*) INTO c FROM public.product_exclude_keywords WHERE product_id = r_id;
    IF c <> (spec->>'r_ekw')::int THEN RAISE EXCEPTION 'GUARD retired % exclude keywords = % (expected %)', r_id, c, spec->>'r_ekw'; END IF;

    -- 3. analysis_results.product_id retired -> survivor
    UPDATE public.analysis_results SET product_id = s_id
     WHERE product_id = r_id AND id::text IN (SELECT jsonb_array_elements_text(ar_ids));
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> (spec->>'ar')::int THEN RAISE EXCEPTION 'analysis_results UPDATE for % affected % rows (expected %)', r_id, c, spec->>'ar'; END IF;
    RAISE NOTICE 'pair % -> %: analysis_results repointed rows=%', r_id, s_id, c;

    -- 4. is_current recompute inside the affected partitions only, with the app's rule (backend/app/services/tcg_analyzer_svc.py:1759-1791):
    --    partition = (supplier channel, product, condition); newest source_messages.received_at wins, then analysis_results.computed_at DESC
    --    (+ is_current DESC, id as a deterministic tie-break that keeps the row that is current today);
    --    only pid_resolved rows with a product; conditions compare with "=" so NULL-condition rows are not touched (same as the app).
    flips := COALESCE((
      WITH aff AS (
        SELECT DISTINCT sm.supplier_channel_id AS ch, ar.condition_id
          FROM public.analysis_results ar
          JOIN public.extraction_items ei ON ei.id = ar.extraction_item_id
          JOIN public.extraction_jobs ej ON ej.id = ei.extraction_job_id
          JOIN public.source_messages sm ON sm.id = ej.source_message_id
         WHERE ar.id::text IN (SELECT jsonb_array_elements_text(ar_ids)) AND ar.pid_resolved = TRUE AND ar.condition_id IS NOT NULL),
      ranked AS (
        SELECT ar.id, ar.is_current AS old_cur, ar.updated_at AS old_upd,
               (row_number() OVER (PARTITION BY sm.supplier_channel_id, ar.condition_id ORDER BY sm.received_at DESC, ar.computed_at DESC, ar.is_current DESC, ar.id) = 1) AS should
          FROM public.analysis_results ar
          JOIN public.extraction_items ei ON ei.id = ar.extraction_item_id
          JOIN public.extraction_jobs ej ON ej.id = ei.extraction_job_id
          JOIN public.source_messages sm ON sm.id = ej.source_message_id
         WHERE ar.product_id = s_id AND ar.pid_resolved = TRUE
           AND EXISTS (SELECT 1 FROM aff WHERE aff.ch IS NOT DISTINCT FROM sm.supplier_channel_id AND aff.condition_id = ar.condition_id))
      SELECT jsonb_agg(jsonb_build_object('id', id::text, 'from', old_cur, 'to', should, 'old_updated_at', old_upd) ORDER BY id::text)
        FROM ranked WHERE old_cur IS DISTINCT FROM should), '[]'::jsonb);
    SELECT count(*) INTO n_to_true FROM jsonb_array_elements(flips) f WHERE (f->>'to')::boolean;
    IF jsonb_array_length(flips) <> (spec->>'flips')::int OR n_to_true <> (spec->>'flips_to_true')::int THEN
      RAISE EXCEPTION 'GUARD is_current flips for survivor % = % (to true %) (expected % / %)', s_id, jsonb_array_length(flips), n_to_true, spec->>'flips', spec->>'flips_to_true';
    END IF;
    UPDATE public.analysis_results ar SET is_current = (f->>'to')::boolean, updated_at = NOW()
      FROM jsonb_array_elements(flips) f
     WHERE ar.id::text = f->>'id' AND ar.product_id = s_id;
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> jsonb_array_length(flips) THEN RAISE EXCEPTION 'is_current UPDATE affected % rows (expected %)', c, jsonb_array_length(flips); END IF;
    RAISE NOTICE 'pair % -> %: is_current flips=% (to true %)', r_id, s_id, c, n_to_true;

    -- 5. extraction_items.resolved_product_code (text of the id)
    UPDATE public.extraction_items SET resolved_product_code = s_id::text
     WHERE resolved_product_code = r_id::text AND id::text IN (SELECT jsonb_array_elements_text(ei_ids));
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> (spec->>'ei')::int THEN RAISE EXCEPTION 'extraction_items UPDATE for % affected % rows (expected %)', r_id, c, spec->>'ei'; END IF;
    RAISE NOTICE 'pair % -> %: extraction_items repointed rows=%', r_id, s_id, c;

    -- 6. buyback_shop_products.product_id
    UPDATE public.buyback_shop_products SET product_id = s_id
     WHERE product_id = r_id AND id::text IN (SELECT jsonb_array_elements_text(bb_ids));
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> (spec->>'bb')::int THEN RAISE EXCEPTION 'buyback_shop_products UPDATE for % affected % rows (expected %)', r_id, c, spec->>'bb'; END IF;
    RAISE NOTICE 'pair % -> %: buyback_shop_products repointed rows=%', r_id, s_id, c;

    -- 7. extraction_shadow_results.product_id
    UPDATE public.extraction_shadow_results SET product_id = s_id
     WHERE product_id = r_id AND id::text IN (SELECT jsonb_array_elements_text(sh_ids));
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> (spec->>'sh')::int THEN RAISE EXCEPTION 'extraction_shadow_results UPDATE for % affected % rows (expected %)', r_id, c, spec->>'sh'; END IF;
    RAISE NOTICE 'pair % -> %: extraction_shadow_results repointed rows=%', r_id, s_id, c;

    -- 8. carry the retired row's keywords that the survivor does not have (list fixed in specs.json; compared with normalize_for_match when it was built)
    kw_ids := '[]'::jsonb;
    FOR kw IN SELECT * FROM jsonb_array_elements(spec->'kw') LOOP
      IF kw->>'kind' = 'search' THEN
        IF NOT EXISTS (SELECT 1 FROM public.product_search_keywords WHERE product_id = r_id AND keyword = kw->>'keyword') THEN RAISE EXCEPTION 'GUARD retired % lacks search keyword %', r_id, kw->>'keyword'; END IF;
        IF EXISTS (SELECT 1 FROM public.product_search_keywords WHERE product_id = s_id AND keyword = kw->>'keyword') THEN RAISE EXCEPTION 'GUARD survivor % already has search keyword %', s_id, kw->>'keyword'; END IF;
        SELECT COALESCE(max("position"), -1) + 1 INTO next_pos FROM public.product_search_keywords WHERE product_id = s_id;
        INSERT INTO public.product_search_keywords (keyword, "position", product_id, updated_at) VALUES (kw->>'keyword', next_pos, s_id, NOW()) RETURNING id INTO new_kw_id;
      ELSE
        IF NOT EXISTS (SELECT 1 FROM public.product_exclude_keywords WHERE product_id = r_id AND keyword = kw->>'keyword') THEN RAISE EXCEPTION 'GUARD retired % lacks exclude keyword %', r_id, kw->>'keyword'; END IF;
        IF EXISTS (SELECT 1 FROM public.product_exclude_keywords WHERE product_id = s_id AND keyword = kw->>'keyword') THEN RAISE EXCEPTION 'GUARD survivor % already has exclude keyword %', s_id, kw->>'keyword'; END IF;
        SELECT COALESCE(max("position"), -1) + 1 INTO next_pos FROM public.product_exclude_keywords WHERE product_id = s_id;
        INSERT INTO public.product_exclude_keywords (keyword, "position", product_id, updated_at) VALUES (kw->>'keyword', next_pos, s_id, NOW()) RETURNING id INTO new_kw_id;
      END IF;
      kw_ids := kw_ids || jsonb_build_array(jsonb_build_object('kind', kw->>'kind', 'id', new_kw_id, 'keyword', kw->>'keyword', 'position', next_pos));
    END LOOP;
    IF jsonb_array_length(kw_ids) <> jsonb_array_length(spec->'kw') THEN RAISE EXCEPTION 'keyword rows inserted for % = % (expected %)', s_id, jsonb_array_length(kw_ids), jsonb_array_length(spec->'kw'); END IF;
    RAISE NOTICE 'pair % -> %: keyword rows carried=%', r_id, s_id, jsonb_array_length(kw_ids);

    -- 9. retire the product (its own keyword rows stay)
    UPDATE public.products SET is_active = FALSE WHERE id = r_id AND is_active = TRUE;
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> 1 THEN RAISE EXCEPTION 'products is_active UPDATE for % affected % rows (expected 1)', r_id, c; END IF;
    RAISE NOTICE 'pair % -> %: product % retired rows=%', r_id, s_id, r_id, c;

    -- final state of this pair
    IF EXISTS (SELECT 1 FROM public.analysis_results WHERE product_id = r_id)
       OR EXISTS (SELECT 1 FROM public.extraction_items WHERE resolved_product_code = r_id::text)
       OR EXISTS (SELECT 1 FROM public.buyback_shop_products WHERE product_id = r_id)
       OR EXISTS (SELECT 1 FROM public.extraction_shadow_results WHERE product_id = r_id) THEN
      RAISE EXCEPTION 'FINAL STATE: references to retired % remain', r_id;
    END IF;
    SELECT count(*) INTO c FROM public.analysis_results WHERE product_id = s_id;
    IF c <> s_before + (spec->>'ar')::int THEN RAISE EXCEPTION 'FINAL STATE: survivor % has % analysis_results (expected %)', s_id, c, s_before + (spec->>'ar')::int; END IF;
    SELECT count(*) INTO c FROM public.product_search_keywords WHERE product_id = s_id;
    IF c <> (spec->>'s_skw')::int + (SELECT count(*) FROM jsonb_array_elements(spec->'kw') k WHERE k->>'kind' = 'search') THEN RAISE EXCEPTION 'FINAL STATE: survivor % has % search keyword rows', s_id, c; END IF;
    SELECT count(*) INTO c FROM public.product_exclude_keywords WHERE product_id = s_id;
    IF c <> (spec->>'s_ekw')::int + (SELECT count(*) FROM jsonb_array_elements(spec->'kw') k WHERE k->>'kind' = 'exclude') THEN RAISE EXCEPTION 'FINAL STATE: survivor % has % exclude keyword rows', s_id, c; END IF;

    -- 10. audit row (new_values carries the exact repointed ids for rollback)
    after_snap := jsonb_build_object('retired', jsonb_build_object(
        'product', (SELECT to_jsonb(p) FROM public.products p WHERE p.id = r_id),
        'search_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_search_keywords k WHERE k.product_id = r_id), '[]'::jsonb),
        'exclude_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_exclude_keywords k WHERE k.product_id = r_id), '[]'::jsonb)), 'survivor', jsonb_build_object(
        'product', (SELECT to_jsonb(p) FROM public.products p WHERE p.id = s_id),
        'search_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_search_keywords k WHERE k.product_id = s_id), '[]'::jsonb),
        'exclude_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_exclude_keywords k WHERE k.product_id = s_id), '[]'::jsonb)));
    merge_info := jsonb_build_object(
      'merge_id', 'dup-merge-2-20261005', 'retired', r_id, 'survivor', s_id,
      'counts', jsonb_build_object('analysis_results', jsonb_array_length(ar_ids), 'is_current_flips', jsonb_array_length(flips),
                                   'extraction_items', jsonb_array_length(ei_ids), 'buyback_shop_products', jsonb_array_length(bb_ids),
                                   'extraction_shadow_results', jsonb_array_length(sh_ids), 'keywords_inserted', jsonb_array_length(kw_ids), 'products_deactivated', 1),
      'ids', jsonb_build_object('analysis_results', ar_ids, 'is_current_flips', flips, 'extraction_items', ei_ids, 'buyback_shop_products', bb_ids,
                                'extraction_shadow_results', sh_ids, 'keywords_inserted', kw_ids));
    INSERT INTO public.audit_log (table_name, record_id, action, changed_by, old_values, new_values)
    VALUES ('products', gen_random_uuid(), 'UPDATE', 'claude-opus (PO承認 2026-10-05 dup-merge-2)', before_snap::text,
            (jsonb_build_object('retired_product_after', after_snap->'retired', 'survivor_after', after_snap->'survivor', 'merge', merge_info))::text);
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> 1 THEN RAISE EXCEPTION 'audit_log insert for % rows=% (expected 1)', r_id, c; END IF;
    touched := touched + 1;
  END LOOP;
  IF touched <> 10 THEN RAISE EXCEPTION 'touched % pairs (expected 10)', touched; END IF;
  RAISE NOTICE 'DONE: % pairs merged, % audit_log rows', touched, touched;
END
$do$;
SELECT p.id, p.product_code, p.mark, p.name, p.is_active,
       (SELECT count(*) FROM public.analysis_results ar WHERE ar.product_id = p.id) AS analysis_results,
       (SELECT count(*) FROM public.extraction_items ei WHERE ei.resolved_product_code = p.id::text) AS extraction_items,
       (SELECT count(*) FROM public.buyback_shop_products b WHERE b.product_id = p.id) AS buyback_shop_products,
       (SELECT count(*) FROM public.extraction_shadow_results sh WHERE sh.product_id = p.id) AS shadow_results,
       (SELECT count(*) FROM public.product_search_keywords k WHERE k.product_id = p.id) AS search_kw_rows,
       (SELECT count(*) FROM public.product_exclude_keywords k WHERE k.product_id = p.id) AS exclude_kw_rows
  FROM public.products p WHERE p.id IN (440573, 398, 1386, 440434, 1385, 440435, 1384, 440578, 1383, 440579, 1382, 440580, 1381, 440581, 1380, 440582, 1379, 440583, 1376, 440587) ORDER BY p.id;
ROLLBACK;
