-- precheck.sql (READ-ONLY)
-- RAISES unless the products and every count (and the predicted is_current flips and keyword carry) equal the expected numbers.
-- Target: DB jarvis_db, schema public. Merge 2 (merge_id dup-merge-2-20261005): 10 duplicate pairs, see specs.json. Generated by gen_sql.py; do not hand-edit.
\set ON_ERROR_STOP on
BEGIN READ ONLY;
SELECT p.id, p.product_code, p.mark, p.name, p.is_active,
       (SELECT count(*) FROM public.analysis_results ar WHERE ar.product_id = p.id) AS analysis_results,
       (SELECT count(*) FROM public.extraction_items ei WHERE ei.resolved_product_code = p.id::text) AS extraction_items,
       (SELECT count(*) FROM public.buyback_shop_products b WHERE b.product_id = p.id) AS buyback_shop_products,
       (SELECT count(*) FROM public.extraction_shadow_results sh WHERE sh.product_id = p.id) AS shadow_results,
       (SELECT count(*) FROM public.product_search_keywords k WHERE k.product_id = p.id) AS search_kw_rows,
       (SELECT count(*) FROM public.product_exclude_keywords k WHERE k.product_id = p.id) AS exclude_kw_rows
  FROM public.products p WHERE p.id IN (440573, 398, 1386, 440434, 1385, 440435, 1384, 440578, 1383, 440579, 1382, 440580, 1381, 440581, 1380, 440582, 1379, 440583, 1376, 440587) ORDER BY p.id;
DO $do$
DECLARE
  specs jsonb := $j$[
 {
  "retired": 440573,
  "retired_code": "PM0225",
  "survivor": 398,
  "survivor_code": "UA-PC02BT",
  "ar": 10,
  "flips": 0,
  "flips_to_true": 0,
  "ei": 0,
  "bb": 0,
  "sh": 0,
  "r_skw": 2,
  "r_ekw": 3,
  "s_skw": 2,
  "s_ekw": 0,
  "s_ar": 4,
  "kw": [
   {
    "kind": "search",
    "keyword": "UNION ARENA 勝利の女神NIKKE【PC02BT】"
   },
   {
    "kind": "exclude",
    "keyword": "WS"
   },
   {
    "kind": "exclude",
    "keyword": "ヴァイス"
   },
   {
    "kind": "exclude",
    "keyword": "ヴァイスシュヴァルツ"
   }
  ]
 },
 {
  "retired": 1386,
  "retired_code": "LOR-the-first-chapter",
  "survivor": 440434,
  "survivor_code": "PM0232",
  "ar": 11,
  "flips": 1,
  "flips_to_true": 0,
  "ei": 14,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 14,
  "kw": [
   {
    "kind": "search",
    "keyword": "THE FIRST CHAPTER 物語のはじまり"
   }
  ]
 },
 {
  "retired": 1385,
  "retired_code": "LOR-rise-of-the-floodborn",
  "survivor": 440435,
  "survivor_code": "PM0233",
  "ar": 7,
  "flips": 1,
  "flips_to_true": 0,
  "ei": 4,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 7,
  "kw": [
   {
    "kind": "search",
    "keyword": "RISE OF THE FLOODBORN フラッドボーンの渾沌"
   }
  ]
 },
 {
  "retired": 1384,
  "retired_code": "LOR-into-the-inklands",
  "survivor": 440578,
  "survivor_code": "PM0234",
  "ar": 8,
  "flips": 2,
  "flips_to_true": 0,
  "ei": 8,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 9,
  "kw": [
   {
    "kind": "search",
    "keyword": "INTO THE INKLANDS インクランド探訪"
   }
  ]
 },
 {
  "retired": 1383,
  "retired_code": "LOR-ursulas-return",
  "survivor": 440579,
  "survivor_code": "PM0235",
  "ar": 4,
  "flips": 1,
  "flips_to_true": 0,
  "ei": 4,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 4,
  "kw": [
   {
    "kind": "search",
    "keyword": "URSULA'S RETURN 逆襲のアースラ"
   }
  ]
 },
 {
  "retired": 1382,
  "retired_code": "LOR-shimmering-skies",
  "survivor": 440580,
  "survivor_code": "PM0236",
  "ar": 18,
  "flips": 2,
  "flips_to_true": 0,
  "ei": 22,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 15,
  "kw": [
   {
    "kind": "search",
    "keyword": "SHIMMERING SKIES 星々の輝き"
   }
  ]
 },
 {
  "retired": 1381,
  "retired_code": "LOR-azurite-sea",
  "survivor": 440581,
  "survivor_code": "PM0237",
  "ar": 12,
  "flips": 1,
  "flips_to_true": 0,
  "ei": 16,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 11,
  "kw": [
   {
    "kind": "search",
    "keyword": "AZURITE SEA 大いなるアズライト"
   }
  ]
 },
 {
  "retired": 1380,
  "retired_code": "LOR-archazias-island",
  "survivor": 440582,
  "survivor_code": "PM0238",
  "ar": 4,
  "flips": 1,
  "flips_to_true": 0,
  "ei": 4,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 4,
  "kw": [
   {
    "kind": "search",
    "keyword": "ARCHAZIAS ISLAND アーケイジアと魔法の島"
   }
  ]
 },
 {
  "retired": 1379,
  "retired_code": "LOR-reign-of-jafar",
  "survivor": 440583,
  "survivor_code": "PM0239",
  "ar": 1,
  "flips": 0,
  "flips_to_true": 0,
  "ei": 1,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 0,
  "kw": [
   {
    "kind": "search",
    "keyword": "REIGN OF JAFAR ジャファーの王権"
   }
  ]
 },
 {
  "retired": 1376,
  "retired_code": "LOR-wilds-unknown",
  "survivor": 440587,
  "survivor_code": "PM0243",
  "ar": 0,
  "flips": 0,
  "flips_to_true": 0,
  "ei": 0,
  "bb": 0,
  "sh": 0,
  "r_skw": 1,
  "r_ekw": 0,
  "s_skw": 1,
  "s_ekw": 0,
  "s_ar": 3,
  "kw": [
   {
    "kind": "search",
    "keyword": "WILDS UNKNOWN 未知なる彼方へ!"
   }
  ]
 }
]$j$::jsonb;
  spec jsonb; r record; s record; n int; f_false int; f_true int; kw jsonb;
BEGIN
  FOR spec IN SELECT * FROM jsonb_array_elements(specs) LOOP
    SELECT * INTO r FROM public.products WHERE id = (spec->>'retired')::int;
    SELECT * INTO s FROM public.products WHERE id = (spec->>'survivor')::int;
    IF r.id IS NULL OR s.id IS NULL THEN RAISE EXCEPTION 'product missing for pair %', spec; END IF;
    IF r.product_code IS DISTINCT FROM spec->>'retired_code' OR s.product_code IS DISTINCT FROM spec->>'survivor_code'
       OR r.is_active IS NOT TRUE OR s.is_active IS NOT TRUE THEN
      RAISE EXCEPTION 'PAIR state differs: retired % (%, active %), survivor % (%, active %)', r.id, r.product_code, r.is_active, s.id, s.product_code, s.is_active;
    END IF;
    SELECT count(*) INTO n FROM public.analysis_results WHERE product_id = r.id;
    IF n <> (spec->>'ar')::int THEN RAISE EXCEPTION 'analysis_results for % = % (expected %)', r.id, n, spec->>'ar'; END IF;
    SELECT count(*) INTO n FROM public.analysis_results WHERE product_id = s.id;
    IF n <> (spec->>'s_ar')::int THEN RAISE EXCEPTION 'analysis_results for survivor % = % (expected %)', s.id, n, spec->>'s_ar'; END IF;
    SELECT count(*) INTO n FROM public.extraction_items WHERE resolved_product_code = r.id::text;
    IF n <> (spec->>'ei')::int THEN RAISE EXCEPTION 'extraction_items for % = % (expected %)', r.id, n, spec->>'ei'; END IF;
    SELECT count(*) INTO n FROM public.buyback_shop_products WHERE product_id = r.id;
    IF n <> (spec->>'bb')::int THEN RAISE EXCEPTION 'buyback_shop_products for % = % (expected %)', r.id, n, spec->>'bb'; END IF;
    SELECT count(*) INTO n FROM public.extraction_shadow_results WHERE product_id = r.id;
    IF n <> (spec->>'sh')::int THEN RAISE EXCEPTION 'extraction_shadow_results for % = % (expected %)', r.id, n, spec->>'sh'; END IF;
    SELECT count(*) INTO n FROM public.product_search_keywords WHERE product_id = r.id;
    IF n <> (spec->>'r_skw')::int THEN RAISE EXCEPTION 'search keywords of retired % = % (expected %)', r.id, n, spec->>'r_skw'; END IF;
    SELECT count(*) INTO n FROM public.product_exclude_keywords WHERE product_id = r.id;
    IF n <> (spec->>'r_ekw')::int THEN RAISE EXCEPTION 'exclude keywords of retired % = % (expected %)', r.id, n, spec->>'r_ekw'; END IF;
    SELECT count(*) INTO n FROM public.product_search_keywords WHERE product_id = s.id;
    IF n <> (spec->>'s_skw')::int THEN RAISE EXCEPTION 'search keywords of survivor % = % (expected %)', s.id, n, spec->>'s_skw'; END IF;
    SELECT count(*) INTO n FROM public.product_exclude_keywords WHERE product_id = s.id;
    IF n <> (spec->>'s_ekw')::int THEN RAISE EXCEPTION 'exclude keywords of survivor % = % (expected %)', s.id, n, spec->>'s_ekw'; END IF;
    FOR kw IN SELECT * FROM jsonb_array_elements(spec->'kw') LOOP
      IF kw->>'kind' = 'search' THEN
        IF NOT EXISTS (SELECT 1 FROM public.product_search_keywords WHERE product_id = r.id AND keyword = kw->>'keyword') THEN RAISE EXCEPTION 'retired % lacks search keyword %', r.id, kw->>'keyword'; END IF;
        IF EXISTS (SELECT 1 FROM public.product_search_keywords WHERE product_id = s.id AND keyword = kw->>'keyword') THEN RAISE EXCEPTION 'survivor % already has search keyword %', s.id, kw->>'keyword'; END IF;
      ELSE
        IF NOT EXISTS (SELECT 1 FROM public.product_exclude_keywords WHERE product_id = r.id AND keyword = kw->>'keyword') THEN RAISE EXCEPTION 'retired % lacks exclude keyword %', r.id, kw->>'keyword'; END IF;
        IF EXISTS (SELECT 1 FROM public.product_exclude_keywords WHERE product_id = s.id AND keyword = kw->>'keyword') THEN RAISE EXCEPTION 'survivor % already has exclude keyword %', s.id, kw->>'keyword'; END IF;
      END IF;
    END LOOP;
    -- predicted is_current flips under the app rule (tcg_analyzer_svc.py:1759-1791), computed as if the retired rows already pointed at the survivor
    WITH x AS (
      SELECT ar.id, ar.condition_id, ar.is_current, ar.computed_at, sm.received_at, sm.supplier_channel_id AS ch,
             (ar.product_id = r.id) AS is_retired
        FROM public.analysis_results ar
        JOIN public.extraction_items ei ON ei.id = ar.extraction_item_id
        JOIN public.extraction_jobs ej ON ej.id = ei.extraction_job_id
        JOIN public.source_messages sm ON sm.id = ej.source_message_id
       WHERE ar.product_id IN (r.id, s.id) AND ar.pid_resolved = TRUE),
    aff AS (SELECT DISTINCT ch, condition_id FROM x WHERE is_retired AND condition_id IS NOT NULL),
    ranked AS (
      SELECT x.id, x.is_current,
             (row_number() OVER (PARTITION BY x.ch, x.condition_id ORDER BY x.received_at DESC, x.computed_at DESC, x.is_current DESC, x.id) = 1) AS should
        FROM x WHERE EXISTS (SELECT 1 FROM aff WHERE aff.ch IS NOT DISTINCT FROM x.ch AND aff.condition_id = x.condition_id))
    SELECT count(*) FILTER (WHERE is_current AND NOT should), count(*) FILTER (WHERE NOT is_current AND should)
      INTO f_false, f_true FROM ranked;
    IF f_false <> (spec->>'flips')::int OR f_true <> (spec->>'flips_to_true')::int THEN
      RAISE EXCEPTION 'predicted flips for survivor % = to_false % / to_true % (expected % / %)', s.id, f_false, f_true, spec->>'flips', spec->>'flips_to_true';
    END IF;
    RAISE NOTICE 'OK pair % -> %: ar % / flips % / ei % / bb % / sh % / keywords to carry %', r.product_code, s.product_code, spec->>'ar', spec->>'flips', spec->>'ei', spec->>'bb', spec->>'sh', jsonb_array_length(spec->'kw');
  END LOOP;
END
$do$;
ROLLBACK;
