-- rollback.sql (WRITES; needs a NEW PO decision before running)
-- Restores exactly the rows saved in the apply audit rows (merge_id dup-merge-2-20261005): product_id, is_current + updated_at, resolved_product_code, buyback and shadow product_id, inserted keyword rows deleted, is_active.
-- Target: DB jarvis_db, schema public. Merge 2 (merge_id dup-merge-2-20261005): 10 duplicate pairs, see specs.json. Generated by gen_sql.py; do not hand-edit.
\set ON_ERROR_STOP on
BEGIN;
SET LOCAL app.is_operator = 'true';
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';
DO $do$
DECLARE
  a record; nv jsonb; m jsonb; r_id int; s_id int; c int; seen int := 0; touched_flips int; kw jsonb;
BEGIN
  FOR a IN SELECT id, new_values FROM public.audit_log
            WHERE table_name = 'products' AND changed_by = 'claude-opus (PO承認 2026-10-05 dup-merge-2)' AND new_values LIKE '%dup-merge-2-20261005%'
              AND NOT EXISTS (SELECT 1 FROM public.audit_log rb
                               WHERE rb.table_name = 'products' AND rb.changed_by = 'claude-opus (rollback dup-merge-2; PO decision required)'
                                 AND CASE WHEN rb.new_values LIKE '{%' THEN (rb.new_values::jsonb->>'rolled_back_audit_id')::bigint END = audit_log.id)
            ORDER BY id LOOP
    nv := a.new_values::jsonb; m := nv->'merge';
    IF m->>'merge_id' IS DISTINCT FROM 'dup-merge-2-20261005' THEN CONTINUE; END IF;
    seen := seen + 1;
    r_id := (m->>'retired')::int; s_id := (m->>'survivor')::int;
    IF EXISTS (SELECT 1 FROM public.products WHERE id = r_id AND is_active) THEN RAISE EXCEPTION 'GUARD: retired % is already active', r_id; END IF;

    -- analysis_results.product_id back to the retired product (only the saved ids)
    UPDATE public.analysis_results SET product_id = r_id
     WHERE product_id = s_id AND id::text IN (SELECT jsonb_array_elements_text(m#>'{ids,analysis_results}'));
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> jsonb_array_length(m#>'{ids,analysis_results}') THEN RAISE EXCEPTION 'rollback analysis_results % -> %: % rows (expected %)', s_id, r_id, c, jsonb_array_length(m#>'{ids,analysis_results}'); END IF;
    RAISE NOTICE 'rollback % : analysis_results restored rows=%', r_id, c;

    -- is_current and updated_at back to their old values (only the saved flip rows; they are the rows flipped to FALSE or TRUE by apply)
    UPDATE public.analysis_results ar SET is_current = (f->>'from')::boolean, updated_at = (f->>'old_updated_at')::timestamptz
      FROM jsonb_array_elements(m#>'{ids,is_current_flips}') f
     WHERE ar.id::text = f->>'id' AND ar.is_current IS NOT DISTINCT FROM (f->>'to')::boolean;
    GET DIAGNOSTICS touched_flips = ROW_COUNT;
    IF touched_flips <> jsonb_array_length(m#>'{ids,is_current_flips}') THEN RAISE EXCEPTION 'rollback is_current %: % rows (expected %)', r_id, touched_flips, jsonb_array_length(m#>'{ids,is_current_flips}'); END IF;
    RAISE NOTICE 'rollback % : is_current restored rows=%', r_id, touched_flips;

    UPDATE public.extraction_items SET resolved_product_code = r_id::text
     WHERE resolved_product_code = s_id::text AND id::text IN (SELECT jsonb_array_elements_text(m#>'{ids,extraction_items}'));
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> jsonb_array_length(m#>'{ids,extraction_items}') THEN RAISE EXCEPTION 'rollback extraction_items %: % rows (expected %)', r_id, c, jsonb_array_length(m#>'{ids,extraction_items}'); END IF;
    RAISE NOTICE 'rollback % : extraction_items restored rows=%', r_id, c;

    UPDATE public.buyback_shop_products SET product_id = r_id
     WHERE product_id = s_id AND id::text IN (SELECT jsonb_array_elements_text(m#>'{ids,buyback_shop_products}'));
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> jsonb_array_length(m#>'{ids,buyback_shop_products}') THEN RAISE EXCEPTION 'rollback buyback_shop_products %: % rows (expected %)', r_id, c, jsonb_array_length(m#>'{ids,buyback_shop_products}'); END IF;
    RAISE NOTICE 'rollback % : buyback_shop_products restored rows=%', r_id, c;

    UPDATE public.extraction_shadow_results SET product_id = r_id
     WHERE product_id = s_id AND id::text IN (SELECT jsonb_array_elements_text(m#>'{ids,extraction_shadow_results}'));
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> jsonb_array_length(m#>'{ids,extraction_shadow_results}') THEN RAISE EXCEPTION 'rollback extraction_shadow_results %: % rows (expected %)', r_id, c, jsonb_array_length(m#>'{ids,extraction_shadow_results}'); END IF;
    RAISE NOTICE 'rollback % : extraction_shadow_results restored rows=%', r_id, c;

    -- delete exactly the keyword rows that apply inserted (guard: id, survivor and text still match)
    FOR kw IN SELECT * FROM jsonb_array_elements(m#>'{ids,keywords_inserted}') LOOP
      IF kw->>'kind' = 'search' THEN
        DELETE FROM public.product_search_keywords WHERE id = (kw->>'id')::int AND product_id = s_id AND keyword = kw->>'keyword';
      ELSE
        DELETE FROM public.product_exclude_keywords WHERE id = (kw->>'id')::int AND product_id = s_id AND keyword = kw->>'keyword';
      END IF;
      GET DIAGNOSTICS c = ROW_COUNT;
      IF c <> 1 THEN RAISE EXCEPTION 'rollback keyword row % (%) on % affected % rows (expected 1)', kw->>'id', kw->>'kind', s_id, c; END IF;
    END LOOP;
    RAISE NOTICE 'rollback % : keyword rows deleted=%', r_id, jsonb_array_length(m#>'{ids,keywords_inserted}');

    UPDATE public.products SET is_active = TRUE WHERE id = r_id AND is_active = FALSE;
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> 1 THEN RAISE EXCEPTION 'rollback products %: % rows (expected 1)', r_id, c; END IF;

    INSERT INTO public.audit_log (table_name, record_id, action, changed_by, old_values, new_values)
    VALUES ('products', gen_random_uuid(), 'UPDATE', 'claude-opus (rollback dup-merge-2; PO decision required)', a.new_values,
            jsonb_build_object('rolled_back_merge_id', 'dup-merge-2-20261005', 'rolled_back_audit_id', a.id, 'retired', r_id, 'survivor', s_id)::text);
  END LOOP;
  IF seen <> 10 THEN RAISE EXCEPTION 'rollback expected 10 audit rows, found %', seen; END IF;
  RAISE NOTICE 'ROLLBACK DONE: % pairs restored', seen;
END
$do$;
SELECT p.id, p.product_code, p.mark, p.name, p.is_active,
       (SELECT count(*) FROM public.analysis_results ar WHERE ar.product_id = p.id) AS analysis_results,
       (SELECT count(*) FROM public.extraction_items ei WHERE ei.resolved_product_code = p.id::text) AS extraction_items,
       (SELECT count(*) FROM public.buyback_shop_products b WHERE b.product_id = p.id) AS buyback_shop_products,
       (SELECT count(*) FROM public.extraction_shadow_results sh WHERE sh.product_id = p.id) AS shadow_results,
       (SELECT count(*) FROM public.product_search_keywords k WHERE k.product_id = p.id) AS search_kw_rows,
       (SELECT count(*) FROM public.product_exclude_keywords k WHERE k.product_id = p.id) AS exclude_kw_rows
  FROM public.products p WHERE p.id IN (440573, 398, 1386, 440434, 1385, 440435, 1384, 440578, 1383, 440579, 1382, 440580, 1381, 440581, 1380, 440582, 1379, 440583, 1376, 440587) ORDER BY p.id;
COMMIT;
