"""create_tcg_analysis_tables_v1

Revision ID: 51c0207e4db4
Revises: 
Create Date: 2026-08-30 18:02:10.857984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c0207e4db4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_changed_at', 'audit_log', ['changed_at'], unique=False)
    op.create_index('ix_audit_log_table_record', 'audit_log', ['table_name', 'record_id'], unique=False)
    op.create_table('conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('canonical', sa.Text(), nullable=False),
    sa.Column('app_kubun', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tcg_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('japanese_title', sa.Text(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('category_class', sa.Text(), nullable=False),
    sa.Column('division_id', sa.UUID(), nullable=True),
    sa.Column('work_id', sa.UUID(), nullable=True),
    sa.Column('manufacturer_id', sa.UUID(), nullable=True),
    sa.Column('product_category_id', sa.UUID(), nullable=True),
    sa.Column('required_output_value', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tcg_suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('canonical', sa.Text(), nullable=False),
    sa.Column('kubun', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('condition_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('condition_id', sa.UUID(), nullable=False),
    sa.Column('alias_text', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_text', 'lang', name='uq_condition_aliases_text_lang')
    )
    op.create_index('ix_condition_aliases_condition_id', 'condition_aliases', ['condition_id'], unique=False)
    op.create_table('product_exclude_keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['tcg_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_exclude_keywords_product_id', 'product_exclude_keywords', ['product_id'], unique=False)
    op.create_table('product_search_keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['tcg_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_search_keywords_product_id', 'product_search_keywords', ['product_id'], unique=False)
    op.create_table('products_logistics',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['tcg_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('supplier_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['tcg_suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'external_id', name='uq_supplier_channels_channel_external')
    )
    op.create_table('unit_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('alias_text', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_text', 'lang', name='uq_unit_aliases_text_lang')
    )
    op.create_index('ix_unit_aliases_unit_id', 'unit_aliases', ['unit_id'], unique=False)
    op.create_table('source_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_channel_id', sa.UUID(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('raw_sha256', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['superseded_by'], ['source_messages.id'], ),
    sa.ForeignKeyConstraint(['supplier_channel_id'], ['supplier_channels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_message_id'], ['source_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extraction_job_id', sa.UUID(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('raw_product_name', sa.Text(), nullable=True),
    sa.Column('raw_quantity', sa.Text(), nullable=True),
    sa.Column('raw_price', sa.Text(), nullable=True),
    sa.Column('raw_unit', sa.Text(), nullable=True),
    sa.Column('raw_state', sa.Text(), nullable=True),
    sa.Column('raw_memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_job_id'], ['extraction_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extraction_item_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('pid_resolved', sa.Boolean(), nullable=False),
    sa.Column('pid_basis', sa.String(length=100), nullable=True),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('unit_canonical', sa.String(length=50), nullable=True),
    sa.Column('unit_resolved', sa.Boolean(), nullable=False),
    sa.Column('condition_id', sa.UUID(), nullable=True),
    sa.Column('condition_canonical', sa.String(length=100), nullable=True),
    sa.Column('condition_basis', sa.String(length=100), nullable=True),
    sa.Column('quantity_normalized', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_normalized', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('note_ja', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('exclusion', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_reasons', sa.Text(), nullable=True),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ),
    sa.ForeignKeyConstraint(['extraction_item_id'], ['extraction_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['tcg_products.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extraction_item_id')
    )
    op.create_index('ix_analysis_results_needs_review', 'analysis_results', ['needs_review'], unique=False)
    op.create_index('ix_analysis_results_pid_resolved', 'analysis_results', ['pid_resolved'], unique=False)
    op.create_index('ix_analysis_results_unit_resolved', 'analysis_results', ['unit_resolved'], unique=False)
    op.create_table('item_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extraction_item_id', sa.UUID(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_item_id'], ['extraction_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_item_notes_extraction_item_id', 'item_notes', ['extraction_item_id'], unique=False)
    op.create_table('unparsed_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extraction_item_id', sa.UUID(), nullable=False),
    sa.Column('line_text', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_item_id'], ['extraction_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unparsed_lines')
    op.drop_index('ix_item_notes_extraction_item_id', table_name='item_notes')
    op.drop_table('item_notes')
    op.drop_index('ix_analysis_results_unit_resolved', table_name='analysis_results')
    op.drop_index('ix_analysis_results_pid_resolved', table_name='analysis_results')
    op.drop_index('ix_analysis_results_needs_review', table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_table('extraction_items')
    op.drop_table('extraction_jobs')
    op.drop_table('source_messages')
    op.drop_index('ix_unit_aliases_unit_id', table_name='unit_aliases')
    op.drop_table('unit_aliases')
    op.drop_table('supplier_channels')
    op.drop_table('products_logistics')
    op.drop_index('ix_product_search_keywords_product_id', table_name='product_search_keywords')
    op.drop_table('product_search_keywords')
    op.drop_index('ix_product_exclude_keywords_product_id', table_name='product_exclude_keywords')
    op.drop_table('product_exclude_keywords')
    op.drop_index('ix_condition_aliases_condition_id', table_name='condition_aliases')
    op.drop_table('condition_aliases')
    op.drop_table('units')
    op.drop_table('tcg_suppliers')
    op.drop_table('tcg_products')
    op.drop_table('conditions')
    op.drop_index('ix_audit_log_table_record', table_name='audit_log')
    op.drop_index('ix_audit_log_changed_at', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
