/**
 * Generated from src/tokens.css by scripts/generate-icon-sizes.js.
 * Do not edit this file. Run npm run generate:icon-sizes after editing the CSS source.
 */
export const ICON = {
  sm: 14,
  md: 16,
  base: 20,
  lg: 24,
  xl: 48,
} as const;

export type IconSize = (typeof ICON)[keyof typeof ICON];
