import React from 'react';
import { StatusBadge } from './components/StatusBadge';
import { productMetadataIssueBadges, reviewIssueBadges, type ReviewIssuePresentation } from './reviewIssues';
import './item-comparison-readonly.css';

export type AnalysisReviewItem = { extraction_item_id: string; source_message_id: string; provider: string; raw_text: string; gemini: Record<string, string>; system: Record<string, string>; review_issues?: string[] };
export type CorrectionValues = { corrected_product_name: string; corrected_quantity: string; corrected_price: string; corrected_unit: string; corrected_condition: string; corrected_memo: string };
export type CorrectionOptions = { units: string[]; conditions: string[] };

const fieldOrder: Array<[string, string]> = [['name', '商品名'], ['quantity', '数量'], ['price', '単価'], ['unit', '単位'], ['state', '状態'], ['memo', 'メモ']];
const correctionFields: Array<[keyof CorrectionValues, string, 'text' | 'number' | 'select-unit' | 'select-condition' | 'textarea']> = [['corrected_product_name', '商品名', 'text'], ['corrected_quantity', '数量', 'number'], ['corrected_price', '単価', 'number'], ['corrected_unit', '単位', 'select-unit'], ['corrected_condition', '状態', 'select-condition'], ['corrected_memo', 'メモ', 'textarea']];
const rawValue = (value: string | undefined) => value || '未記載';
const emptyCorrections = (): CorrectionValues => ({ corrected_product_name: '', corrected_quantity: '', corrected_price: '', corrected_unit: '', corrected_condition: '', corrected_memo: '' });

function SystemValue({ value, source }: { value: string; source: string }) { return <><span>{value}</span><small>{source}</small></>; }
function FinalSystemValue({ item, keyName }: { item: AnalysisReviewItem; keyName: string }) { const system = item.system; if (keyName === 'name' || keyName === 'quantity' || keyName === 'price') return <SystemValue value={item.gemini[keyName] || '未解決'} source={item.gemini[keyName] ? 'Gemini抽出値を採用' : '未解決'} />; if (keyName === 'unit') return <SystemValue value={system.unit || '未解決'} source={system.unit && system.unit_resolved === 'YES' ? 'System確定' : '未解決'} />; if (keyName === 'state') return <SystemValue value={system.condition || '未解決'} source={system.condition ? 'System確定' : '未解決'} />; return system.note ? <SystemValue value={system.note} source="System確定" /> : <span>なし</span>; }
function ManualInput({ values, field, options, onChange }: { values: CorrectionValues; field: typeof correctionFields[number]; options?: CorrectionOptions; onChange: (key: keyof CorrectionValues, value: string) => void }) { const [key, label, kind] = field; if (kind === 'textarea') return <textarea value={values[key]} maxLength={2000} aria-label={`手動修正 ${label}`} onChange={(event) => onChange(key, event.target.value)} />; if (kind === 'select-unit' || kind === 'select-condition') { const choices = kind === 'select-unit' ? options?.units : options?.conditions; return <select value={values[key]} disabled={!options} aria-label={`手動修正 ${label}`} onChange={(event) => onChange(key, event.target.value)}><option value="">修正なし</option>{choices?.map((value) => <option key={value} value={value}>{value}</option>)}</select>; } return <input type={kind} min={kind === 'number' ? '0' : undefined} step={kind === 'number' ? 'any' : undefined} value={values[key]} maxLength={kind === 'text' ? 500 : undefined} aria-label={`手動修正 ${label}`} onChange={(event) => onChange(key, event.target.value)} />; }
function ComparisonMetadataRow({ label, value, badges = [] }: { label: string; value: React.ReactNode; badges?: ReviewIssuePresentation[] }) { return <div className="comparison-metadata-row"><b>{label}</b><span className="comparison-metadata-value">{value}{badges.map((badge) => <StatusBadge key={badge.id} label={badge.label} tone={badge.tone} />)}</span></div>; }
function sourceLine(span: string) { const match = span.match(/L?0*(\d+)/i); return match ? Number(match[1]) : undefined; }

export function ItemComparison({ item, values = emptyCorrections(), options, correctionState, note = '', noteState, noteDiagnostic, onCorrectionChange = () => {}, onCorrectionSave = () => {}, onNoteChange = () => {}, onNoteSave = () => {}, onJumpToSourceLine, readOnly = false }: { item: AnalysisReviewItem; values?: CorrectionValues; options?: CorrectionOptions; correctionState?: 'idle' | 'saving' | 'saved' | 'error'; note?: string; noteState?: 'idle' | 'saving' | 'saved' | 'error'; noteDiagnostic?: { error_code: string; stage: string; extraction_item_id: string; source_message_id: string; build_sha: string; request_id: string }; onCorrectionChange?: (key: keyof CorrectionValues, value: string) => void; onCorrectionSave?: () => void; onNoteChange?: (value: string) => void; onNoteSave?: () => void; onJumpToSourceLine: (line: number) => void; readOnly?: boolean }) {
  const corrected = Object.values(values).some(Boolean), issueBadges = reviewIssueBadges(item.review_issues || []), productIssueBadges = productMetadataIssueBadges(item.review_issues || []), lineSpan = item.gemini.span || '', line = sourceLine(lineSpan);
  return <article className={readOnly ? 'item-comparison item-comparison--readonly' : 'item-comparison'}><div className="item-head-grid"><h3>Gemini抽出</h3><div><h3>システム最終結果</h3><span className="inline-badges">{issueBadges.map((badge) => <StatusBadge key={badge.id} label={badge.label} tone={badge.tone} />)}</span></div>{!readOnly && <div><h3>手動修正</h3><span className={`badge ${corrected ? 'badge-warning' : 'badge-neutral'}`}>{corrected ? '手動修正あり' : '未修正'}</span></div>}</div><div className="aligned-fields">{fieldOrder.map(([key, label], index) => <React.Fragment key={key}><div className="comparison-field"><b>{label}</b><span>{rawValue(item.gemini[key])}</span></div><div className="comparison-field system-field"><b>{label}</b><FinalSystemValue item={item} keyName={key} /></div>{!readOnly && <div className="comparison-field manual-field"><b>{label}</b><ManualInput values={values} field={correctionFields[index]} options={options} onChange={onCorrectionChange} /></div>}</React.Fragment>)}</div><div className="item-extra-grid"><div className="comparison-extra"><ComparisonMetadataRow label="原文位置" value={line ? <button className="line-jump" type="button" onClick={() => onJumpToSourceLine(line)}>{lineSpan}</button> : rawValue(lineSpan)} /></div><div className="system-extra"><ComparisonMetadataRow label="商品ID" value={item.system.product_id || '未解決'} badges={productIssueBadges} /><ComparisonMetadataRow label="販売状況" value={item.system.status || '未解決'} /></div>{!readOnly && <div className="manual-actions"><label htmlFor={`note-${item.extraction_item_id}`}>あなたのメモ</label><textarea id={`note-${item.extraction_item_id}`} value={note} maxLength={2000} onChange={(event) => onNoteChange(event.target.value)} /><div><button type="button" disabled={true} onClick={onCorrectionSave}>{correctionState === 'saving' ? '保存中…' : '修正内容を保存'}</button><button type="button" disabled={true} onClick={onNoteSave}>{noteState === 'saving' ? '保存中…' : 'メモを保存'}</button></div>{correctionState === 'saved' && <span className="note-saved">修正内容を保存しました</span>}{correctionState === 'error' && <span className="note-error">修正内容の保存に失敗しました</span>}{noteState === 'saved' && <span className="note-saved">保存しました</span>}{noteState === 'error' && <span className="note-error">保存に失敗しました{noteDiagnostic && <><br /><small>エラー: {noteDiagnostic.error_code}<br />処理: {noteDiagnostic.stage}<br />対象ID: {noteDiagnostic.extraction_item_id || '未取得'}<br />要求ID: {noteDiagnostic.request_id}</small></>}</span>}</div>}</div></article>;
}
