-- apply.sql (WRITES, one transaction, ends with COMMIT)
-- UPDATE products SET mark = 'M2a' for id 440559 only; keywords unchanged; one audit_log row.
-- Target: DB jarvis_db, schema public. Product 440559 (PM0198 MEGAドリームex). Generated by gen_sql.py; do not hand-edit.
\set ON_ERROR_STOP on
BEGIN;
SET LOCAL app.is_operator = 'true';
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '60s';
DO $do$
DECLARE
  spec jsonb;
  specs jsonb := $j$[
 {
  "id": 440559,
  "code": "PM0198",
  "old": {
   "mark": "M3",
   "name": "MEGAドリームex",
   "search": [
    "MEGAドリームex",
    "MEGA Dream",
    "メガドリーム"
   ],
   "exclude": [
    "AR",
    "PSA",
    "PSA10",
    "PSA9",
    "SAR",
    "SR",
    "パラレル",
    "マスターボールミラー"
   ]
  },
  "new": {
   "mark": "M2a",
   "name": "MEGAドリームex",
   "search": [
    "MEGAドリームex",
    "MEGA Dream",
    "メガドリーム"
   ],
   "exclude": [
    "AR",
    "PSA",
    "PSA10",
    "PSA9",
    "SAR",
    "SR",
    "パラレル",
    "マスターボールミラー"
   ]
  }
 }
]$j$::jsonb;
  pid int; c int; r record;
  cur_s text[]; cur_e text[]; from_s text[]; from_e text[]; to_s text[]; to_e text[];
  before_snap jsonb; after_snap jsonb; touched int := 0;
BEGIN
  FOR spec IN SELECT * FROM jsonb_array_elements(specs) LOOP
    pid := (spec->>'id')::int;
    -- lock + guard on the values we expect to replace (mirrors FOR UPDATE + revision check in update_product_detail)
    SELECT * INTO r FROM public.products WHERE id = pid FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'product % not found', pid; END IF;
    cur_s := ARRAY(SELECT keyword FROM public.product_search_keywords WHERE product_id = pid ORDER BY position, id);
    cur_e := ARRAY(SELECT keyword FROM public.product_exclude_keywords WHERE product_id = pid ORDER BY position, id);
    from_s := ARRAY(SELECT jsonb_array_elements_text(spec->'old'->'search'));
    from_e := ARRAY(SELECT jsonb_array_elements_text(spec->'old'->'exclude'));
    to_s := ARRAY(SELECT jsonb_array_elements_text(spec->'new'->'search'));
    to_e := ARRAY(SELECT jsonb_array_elements_text(spec->'new'->'exclude'));
    IF r.product_code IS DISTINCT FROM spec->>'code' OR r.mark IS DISTINCT FROM spec->'old'->>'mark'
       OR r.name IS DISTINCT FROM spec->'old'->>'name' OR r.is_active IS NOT TRUE
       OR cur_s IS DISTINCT FROM from_s OR cur_e IS DISTINCT FROM from_e THEN
      RAISE EXCEPTION 'GUARD id=%: unexpected current state code=% mark=% name=% search=% exclude=%',
        pid, r.product_code, r.mark, r.name, cur_s, cur_e;
    END IF;
    -- this fix changes the mark only: the keyword lists must be identical before and after
    IF to_s IS DISTINCT FROM from_s OR to_e IS DISTINCT FROM from_e OR spec->'new'->>'name' IS DISTINCT FROM spec->'old'->>'name' THEN
      RAISE EXCEPTION 'SPEC id=%: this script must change the mark only', pid;
    END IF;

    before_snap := jsonb_build_object(
      'product', (SELECT to_jsonb(p) FROM public.products p WHERE p.id = pid),
      'search_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_search_keywords k WHERE k.product_id = pid), '[]'::jsonb),
      'exclude_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_exclude_keywords k WHERE k.product_id = pid), '[]'::jsonb));

    UPDATE public.products SET mark = spec->'new'->>'mark'
     WHERE id = pid AND name = spec->'old'->>'name' AND mark = spec->'old'->>'mark';
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> 1 THEN RAISE EXCEPTION 'UPDATE products id=% affected % rows (expected 1)', pid, c; END IF;
    RAISE NOTICE 'id=% products UPDATE rows=%: mark % -> %', pid, c, spec->'old'->>'mark', spec->'new'->>'mark';

    -- final state of this product must equal the target (keyword rows untouched)
    SELECT * INTO r FROM public.products WHERE id = pid;
    cur_s := ARRAY(SELECT keyword FROM public.product_search_keywords WHERE product_id = pid ORDER BY position, id);
    cur_e := ARRAY(SELECT keyword FROM public.product_exclude_keywords WHERE product_id = pid ORDER BY position, id);
    IF r.mark IS DISTINCT FROM spec->'new'->>'mark' OR r.name IS DISTINCT FROM spec->'new'->>'name'
       OR cur_s IS DISTINCT FROM to_s OR cur_e IS DISTINCT FROM to_e THEN
      RAISE EXCEPTION 'FINAL STATE id=% differs from target: mark=% name=% search=% exclude=%', pid, r.mark, r.name, cur_s, cur_e;
    END IF;

    after_snap := jsonb_build_object(
      'product', (SELECT to_jsonb(p) FROM public.products p WHERE p.id = pid),
      'search_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_search_keywords k WHERE k.product_id = pid), '[]'::jsonb),
      'exclude_keywords', COALESCE((SELECT jsonb_agg(to_jsonb(k) ORDER BY k.position, k.id) FROM public.product_exclude_keywords k WHERE k.product_id = pid), '[]'::jsonb));

    -- same shape as update_product_detail's audit row (record_id is a fresh uuid there too; old/new are TEXT)
    INSERT INTO public.audit_log (table_name, record_id, action, changed_by, old_values, new_values)
    VALUES ('products', gen_random_uuid(), 'UPDATE', 'claude-opus (PO承認 2026-10-05)', before_snap::text, after_snap::text);
    GET DIAGNOSTICS c = ROW_COUNT;
    IF c <> 1 THEN RAISE EXCEPTION 'audit_log insert id=% rows=% (expected 1)', pid, c; END IF;
    touched := touched + 1;
  END LOOP;
  IF touched <> 1 THEN RAISE EXCEPTION 'touched % products (expected 1)', touched; END IF;
  RAISE NOTICE 'DONE: % products changed, % audit_log rows', touched, touched;
END
$do$;
SELECT p.id, p.product_code, p.mark, p.name, p.is_active,
       (SELECT string_agg(k.position || ':' || k.keyword, ' | ' ORDER BY k.position, k.id)
          FROM public.product_search_keywords k WHERE k.product_id = p.id) AS search_keywords,
       (SELECT string_agg(k.position || ':' || k.keyword, ' | ' ORDER BY k.position, k.id)
          FROM public.product_exclude_keywords k WHERE k.product_id = p.id) AS exclude_keywords,
       p.updated_at
  FROM public.products p WHERE p.id IN (440559) ORDER BY p.id;
COMMIT;
