-- postcheck.sql (READ-ONLY)
-- RAISES unless product 440559 has mark M2a and unchanged keywords; lists the audit row.
-- Target: DB jarvis_db, schema public. Product 440559 (PM0198 MEGAドリームex). Generated by gen_sql.py; do not hand-edit.
\set ON_ERROR_STOP on
BEGIN READ ONLY;
SELECT p.id, p.product_code, p.mark, p.name, p.is_active,
       (SELECT string_agg(k.position || ':' || k.keyword, ' | ' ORDER BY k.position, k.id)
          FROM public.product_search_keywords k WHERE k.product_id = p.id) AS search_keywords,
       (SELECT string_agg(k.position || ':' || k.keyword, ' | ' ORDER BY k.position, k.id)
          FROM public.product_exclude_keywords k WHERE k.product_id = p.id) AS exclude_keywords,
       p.updated_at
  FROM public.products p WHERE p.id IN (440559) ORDER BY p.id;
DO $do$
DECLARE
  spec jsonb;
  specs jsonb := $j$[
 {
  "id": 440559,
  "code": "PM0198",
  "old": {
   "mark": "M3",
   "name": "MEGAドリームex",
   "search": [
    "MEGAドリームex",
    "MEGA Dream",
    "メガドリーム"
   ],
   "exclude": [
    "AR",
    "PSA",
    "PSA10",
    "PSA9",
    "SAR",
    "SR",
    "パラレル",
    "マスターボールミラー"
   ]
  },
  "new": {
   "mark": "M2a",
   "name": "MEGAドリームex",
   "search": [
    "MEGAドリームex",
    "MEGA Dream",
    "メガドリーム"
   ],
   "exclude": [
    "AR",
    "PSA",
    "PSA10",
    "PSA9",
    "SAR",
    "SR",
    "パラレル",
    "マスターボールミラー"
   ]
  }
 }
]$j$::jsonb;
  pid int; r record; cur_s text[]; cur_e text[]; want_s text[]; want_e text[];
BEGIN
  FOR spec IN SELECT * FROM jsonb_array_elements(specs) LOOP
    pid := (spec->>'id')::int;
    SELECT * INTO r FROM public.products WHERE id = pid;
    IF NOT FOUND THEN RAISE EXCEPTION 'product % not found', pid; END IF;
    cur_s := ARRAY(SELECT keyword FROM public.product_search_keywords WHERE product_id = pid ORDER BY position, id);
    cur_e := ARRAY(SELECT keyword FROM public.product_exclude_keywords WHERE product_id = pid ORDER BY position, id);
    want_s := ARRAY(SELECT jsonb_array_elements_text(spec->'new'->'search'));
    want_e := ARRAY(SELECT jsonb_array_elements_text(spec->'new'->'exclude'));
    IF r.product_code IS DISTINCT FROM spec->>'code' OR r.mark IS DISTINCT FROM spec->'new'->>'mark'
       OR r.name IS DISTINCT FROM spec->'new'->>'name' OR r.is_active IS NOT TRUE
       OR cur_s IS DISTINCT FROM want_s OR cur_e IS DISTINCT FROM want_e THEN
      RAISE EXCEPTION 'MISMATCH (new) id=%: code=% mark=% name=% active=% search=% exclude=%',
        pid, r.product_code, r.mark, r.name, r.is_active, cur_s, cur_e;
    END IF;
    RAISE NOTICE 'OK (new) id=% code=% mark=% name=%', pid, r.product_code, r.mark, r.name;
  END LOOP;
END
$do$;
SELECT id, table_name, action, changed_by, changed_at, length(old_values) AS old_len, length(new_values) AS new_len
  FROM public.audit_log WHERE table_name = 'products' AND changed_by = 'claude-opus (PO承認 2026-10-05)' ORDER BY id DESC LIMIT 5;
ROLLBACK;
